Invalidate email registration URL upon their timeout
inverse-inc/packetfence pull request #1671
Opened 2016-08-24 16:33 UTC by louismunro

# Description
Email activations URLs were hard-coded to expire after 31 days.
This makes them expire when the email source times out.

# Impacts
Try to use a registration URL after the email source has timed out (e.g. 10 minutes).
It should not be allowed.

# Issue
fixes #1670

# Delete branch after merge
YES 

## Bug Fixes
* Fixes email registration URL not expiring at same time as the source times out (#1670)

2016-08-31 17:35 UTC, cgx commented on lib/pf/activation.pm
> +    $mac = $args->{'mac'};
Duplicated code.

2016-09-27 13:31 UTC, dwlfrth requested changes

2016-09-27 13:31 UTC, dwlfrth commented on lib/pf/activation.pm
> +	mac 	=> $mac,  pid 	 => $pid, 	pending => $pending_addr,
One per line is better (coding style)

2016-09-27 13:31 UTC, dwlfrth commented on lib/pf/activation.pm
> +	mac  => $mac,  pid    => $pid,    pending     => $phone_number,
Again, one per line is better (coding style)

2016-09-27 13:32 UTC, dwlfrth commented
Fix duplicate code mentionned by @cgx and requested changes by me and we are golden to merge.

2016-09-27 13:45 UTC, louismunro commented on lib/pf/activation.pm
> +	mac 	=> $mac,  pid 	 => $pid, 	pending => $pending_addr,
I disagree in this case.
It makes the subroutine too long.
A tabular format is better if there are a lot of arguments.
Conciseness is also a virtue.

2016-09-27 13:48 UTC, louismunro commented on lib/pf/activation.pm
> +	mac 	=> $mac,  pid 	 => $pid, 	pending => $pending_addr,
Come to think of it.
You are right.
I am changing it.

2016-09-27 13:50 UTC, dwlfrth commented on lib/pf/activation.pm
> +	mac 	=> $mac,  pid 	 => $pid, 	pending => $pending_addr,
Looks great when printed but PITA when it comes to editing and other.

2016-09-27 13:51 UTC, louismunro commented on lib/pf/activation.pm
> +	mac  => $mac,  pid    => $pid,    pending     => $phone_number,
Done.

2016-09-27 13:53 UTC, dwlfrth approved these changes

2016-09-27 13:54 UTC, merged