feature/eap-fast-integration2
inverse-inc/packetfence pull request #1700
Opened 2016-09-14 18:15 UTC by jrouzierinverse

Description
-----------
Integrate eap fast 
Allow EAP types to be configured from the GUI

Impacts
-----------
freeradius config

NEWS file entries
-------

New Features
++++++++++++
* EAP type configuration from the admin GUI

Delete branch after merge
-------------------------
NO

2016-09-14 18:55 UTC, julsemaan commented on conf/radiusd/eap.conf.example
> +		pac_opaque_key = "0123456789abcdef0123456789ABCDEF"
This should be taking the value from pf.conf

2016-09-14 18:56 UTC, julsemaan commented on conf/radiusd/eap.conf.example
> +		virtual_server = inner-tunnel
This should use packetfence-tunnel

2016-09-14 18:56 UTC, julsemaan requested changes

2016-09-14 19:14 UTC, jrouzierinverse commented on conf/radiusd/eap.conf.example
> +		virtual_server = inner-tunnel
fixed

2016-09-14 19:14 UTC, jrouzierinverse commented on conf/radiusd/eap.conf.example
> +		pac_opaque_key = "0123456789abcdef0123456789ABCDEF"
fixed

2016-09-14 19:53 UTC, julsemaan approved these changes

2016-09-16 18:49 UTC, louismunro commented
Please rebase

2016-09-16 19:29 UTC, merged