Fix/rhel7 domain join
inverse-inc/packetfence pull request #1701
Opened 2016-09-14 19:01 UTC by tlaurion

# Description
(REQUIRED)
Fixes domain join issues encountered with CentOS7 linked to passing to Samba4 and tighter ip namespace implementation.

Fixes:
-Path to Samba credential cache is not overwritten anymore every time winbind is relaunched, resulting in a a possible testjoin. 
-Using chroot inside a ip netns invalidates netns automatic usage of netns's resolv.conf. Introduction of overlay filesystem so that the resolv.conf file is the one defined in ip netns.
-Leaving a domain wasn't done in the chroot.
-Winbind pid watch was done in the old centos directory, which was the cause of superlong winbind restarts (timeout, then active validation of process existence)
-Domain join was made with "-S IP DOMAIN_NAME". Joining domain with -S required PDC name, and fails with errors when an IP address is given, and also fails when provided with domain_name since its not what is required. How was working with prior version?

# Impacts
-pid watch routine may need to be wrapped in version validation code for CentOS6.
-overlay fs is not available in CentOS6. How do we deal with this?
-Debian?

# Code / PR Dependencies
-Overlay fs is available in kernel 3.12+, butwas backported in CentOS 3.10.x.
-pid watch is now relative to samba4 new file names. May need to be wrapped for CentOS6/Debian.

# Issue
fixes #1661 

# Delete branch after merge
YES

## Bug Fixes
* Issue with joining multiple domains with CentOS7  (#1661)

2016-09-14 19:07 UTC, tlaurion commented on lib/pf/domain.pm
> -        $logger->info("netns deletion : ".run("/usr/bin/sudo /sbin/ip netns delete $domain"));
Oups. deleted that. Testing revert and pushing changes.

2016-09-14 19:55 UTC, julsemaan commented on addons/create_chroot.sh
> +    if [[ "$dir" != "etc" ]]; then
tabulation is wrong for this whole block

2016-09-14 19:55 UTC, julsemaan commented on lib/pf/domain.pm
> +    use Data::Dumper;
Remove those

2016-09-14 19:56 UTC, julsemaan commented on lib/pf/domain.pm
> +    use Data::Dumper;
Remove those

2016-09-14 19:57 UTC, julsemaan commented on lib/pf/services/manager/winbindd_child.pm
> +This setups a watch on the run directory to wait for the pid to
*This setups a watch on the run directory and its childs to wait for the pid to appear

2016-09-14 19:58 UTC, julsemaan commented on addons/create_chroot.sh
> +DIRS=(proc var etc lib lib64 usr sbin bin var/cache/samba sys var/lib/samba dev tmp run/samba var/log/samba var/lock var/run)
Attempt removing var/lock and var/run to see if all still succeeds as I believe the issue you fixed isn't tied to that

2016-09-14 19:58 UTC, julsemaan requested changes

2016-09-14 20:10 UTC, tlaurion commented on lib/pf/domain.pm
> +    use Data::Dumper;
oupsi

2016-09-14 21:27 UTC, tlaurion commented
Current state should work on all CentOS7.

2016-09-22 17:25 UTC, tlaurion commented on lib/pf/services/manager/winbindd_child.pm
> -        my $DOMAIN_IF="$domain-b";
That is not working in debian.

2016-09-28 18:28 UTC, julsemaan approved these changes

2016-09-28 18:30 UTC, julsemaan commented
Changing milestone to 6.3 as this can't be cherry-picked into maintenance as it changes the samba cache directory which would make working installations break

2016-09-28 18:30 UTC, merged