Security_onion parser unit test
inverse-inc/packetfence pull request #1759
Opened 2016-10-13 15:50 UTC by tlaurion

# Description
Quick unit test to validate if there was format change in the way SecurityOnion was logging things up.
No change. Now we have a unit test!

# Impacts
none

# Delete branch after merge
YES

2016-10-13 16:29 UTC, fdurand commented on t/unittest/detect/parser/securityonion.t
> +Copyright (C) 2005-2015 Inverse inc.
2016

2016-10-13 16:59 UTC, fdurand requested changes

2016-10-13 16:59 UTC, fdurand commented on t/unittest/detect/parser/securityonion.t
> +#
remove

2016-10-13 16:59 UTC, fdurand commented on t/unittest/detect/parser/securityonion.t
> +#my $alert = 'Oct 28 13:37:42 poulichefencer sguil_alert: 13:37:42 pid(3403)  Alert Received: 0 2 misc-attack securityonion1-eth1 {2015-10-28 13:37:42} 3 88707 {ET TOR Known Tor Relay/Router (Not Exi
remove

2016-10-13 16:59 UTC, fdurand commented on t/unittest/detect/parser/securityonion.t
> +example pf test
Be more explicit

2016-10-13 16:59 UTC, fdurand commented on t/unittest/detect/parser/securityonion.t
> +=head1 DESCRIPTION
Be more explicit

2016-10-13 16:59 UTC, fdurand commented on t/unittest/detect/parser/securityonion.t
> +example pf test script
Be more explicit

2016-10-13 17:09 UTC, tlaurion reviewed
Done

2016-10-29 00:02 UTC, fdurand approved these changes

2016-10-29 00:02 UTC, merged