Replace perl by rest api for radius accounting
inverse-inc/packetfence pull request #1760
Opened 2016-10-13 20:19 UTC by fdurand

# Description
Use rest call for radius accounting instead of perl

# Impacts
RADIUS accounting workflow

# Delete branch after merge
YES

# NEWS file entries

## Enhancements
* Use rest call for radius accounting instead of perl

2016-10-14 12:48 UTC, julsemaan requested changes

2016-10-14 12:48 UTC, julsemaan commented on lib/pf/api.pm
> +    if ($RAD_REQUEST{'Acct-Status-Type'} == 1) {
constant for this

2016-10-14 12:48 UTC, julsemaan commented on lib/pf/api.pm
> +    if ($RAD_REQUEST{'Acct-Status-Type'} == 2){
constant for that

2016-10-14 12:48 UTC, julsemaan commented on lib/pf/api.pm
> +    if ($RAD_REQUEST{'Acct-Status-Type'} == 2 || $RAD_REQUEST{'Acct-Status-Type'} == 3 ) {
constants everywhere

2016-11-02 12:39 UTC, fdurand commented
Bump

2016-11-02 13:33 UTC, merged