Added a timeout for the sponsor to click on the link
inverse-inc/packetfence pull request #1777
Opened 2016-10-19 23:33 UTC by fdurand

# Description
Added an activation timeout on sponsor source

# Impacts
Sponsor source

# Delete branch after merge
YES

# NEWS file entries
## Enhancements
* Added an activation timeout on sponsor source

2016-11-01 19:57 UTC, julsemaan requested changes

2016-11-01 19:57 UTC, julsemaan commented on html/pfappserver/lib/pfappserver/Form/Config/Authentication/Source/SponsorEmail.pm
> +             help => 'This is the delay given to a sponsor to click the activation link.' },
Change to 'Delay given to a sponsor to click the activation link.'

2016-11-01 19:57 UTC, julsemaan commented on html/pfappserver/lib/pfappserver/Form/Config/Authentication/Source/SponsorEmail.pm
> +   default => pfappserver::Form::Field::Duration->duration_inflate(pf::Authentication::Source::EmailSource->meta->get_attribute('email_activation_timeout')->default),
Should be taken from SponsorSource not EmailSource

2016-11-01 19:57 UTC, julsemaan commented on html/pfappserver/lib/pfappserver/Form/Config/Authentication/Source/SponsorEmail.pm
> +has_field 'email_activation_timeout' =>
You need to add the field `email_activation_timeout` to the SponsorEmailSource module as it doesn't seem to be there..

2016-11-02 12:46 UTC, fdurand commented
Done

2016-11-02 13:58 UTC, merged