fix/iplog_history_rotate_index
inverse-inc/packetfence pull request #1790
Opened 2016-10-24 20:38 UTC by jrouzierinverse

Description
-----------
Fixes issue where iplog rotate is taking a log time

Impacts
-----------
Database indexes

Issue
------------
Issue #1754

NEWS file entries
-------

Enhancements
++++++++++++
* Improve speed of iplog_history rotation

Delete branch after merge
-------------------------
NO

2016-10-25 17:50 UTC, dwlfrth commented
Let's add it to the 'iplog_archive' table as well.
Can we also add one on the 'start_time' ?

2016-10-25 18:28 UTC, jrouzierinverse commented
Are we performing any searches on the start_time for iplog_history and iplog_archive?

2016-10-25 18:32 UTC, dwlfrth commented
Yes

2016-11-01 12:48 UTC, extrafu commented
Rebase

2016-11-01 18:48 UTC, dwlfrth requested changes
Please add index on "start_time" also.
Both indexes should also exists in "iplog_archive"

2016-11-02 10:56 UTC, jrouzierinverse commented
done

2016-11-02 14:07 UTC, dwlfrth requested changes

2016-11-02 14:07 UTC, dwlfrth commented on db/upgrade-X.X.X-X.Y.Z.sql
> +ALTER TABLE iplog_history ADD INDEX end_time (end_time) ADD INDEX start_time (end_time);
second column name need to be adjusted

2016-11-02 14:07 UTC, dwlfrth commented on db/upgrade-X.X.X-X.Y.Z.sql
> +ALTER TABLE iplog_archive ADD INDEX end_time (end_time) ADD INDEX start_time (end_time);
second column name need to be adjusted

2016-11-02 14:52 UTC, jrouzierinverse commented
fixed

James Rouzier
jrouzier@inverse.ca :: +1.514.447.4918 (x115)  ::  http://www.inverse.ca
Inverse inc. :: Leaders behind SOGo (http://www.sogo.nu) and PacketFence (http://www.packetfence.org)

On 2016-11-02 10:07 AM, Derek Wuelfrath wrote:
>
> *@dwlfrth* requested changes on this pull request.
>
> ------------------------------------------------------------------------
>
> In db/upgrade-X.X.X-X.Y.Z.sql 
> <https://github.com/inverse-inc/packetfence/pull/1790#pullrequestreview-6819502>:
>
> > @@ -316,3 +316,15 @@ DROP INDEX mac ON violation;
>   --
>   
>   DROP INDEX ip on inline_accounting;
> +
> +--
> +-- Alter table iplog_history
> +--
> +
> +ALTER TABLE iplog_history ADD INDEX end_time (end_time) ADD INDEX start_time (end_time);
>
> second column name need to be adjusted
>
> ------------------------------------------------------------------------
>
> In db/upgrade-X.X.X-X.Y.Z.sql 
> <https://github.com/inverse-inc/packetfence/pull/1790#pullrequestreview-6819502>:
>
> > @@ -316,3 +316,15 @@ DROP INDEX mac ON violation;
>   --
>   
>   DROP INDEX ip on inline_accounting;
> +
> +--
> +-- Alter table iplog_history
> +--
> +
> +ALTER TABLE iplog_history ADD INDEX end_time (end_time) ADD INDEX start_time (end_time);
> +
> +--
> +-- Alter table iplog_archive
> +--
> +
> +ALTER TABLE iplog_archive ADD INDEX end_time (end_time) ADD INDEX start_time (end_time);
>
> second column name need to be adjusted
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/inverse-inc/packetfence/pull/1790#pullrequestreview-6819502>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ACmeMQzQ1d3ZyuuYNJqMZUnbKZ7dN8TIks5q6JkpgaJpZM4KfQYL>.
>

2016-11-02 14:52 UTC, dwlfrth requested changes

2016-11-02 14:52 UTC, dwlfrth commented on db/upgrade-X.X.X-X.Y.Z.sql
> +ALTER TABLE iplog_history ADD INDEX end_time (end_time) ADD INDEX start_time (start_time);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ADD INDEX start_time (start_time)' at line 1

Missing comma before second ADD

2016-11-02 14:52 UTC, dwlfrth commented on db/upgrade-X.X.X-X.Y.Z.sql
> +ALTER TABLE iplog_archive ADD INDEX end_time (end_time) ADD INDEX start_time (start_time);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ADD INDEX start_time (start_time)' at line 1

Missing comma before second ADD

2016-11-02 14:54 UTC, jrouzierinverse commented
Fixed

James Rouzier
jrouzier@inverse.ca :: +1.514.447.4918 (x115)  ::  http://www.inverse.ca
Inverse inc. :: Leaders behind SOGo (http://www.sogo.nu) and PacketFence (http://www.packetfence.org)

On 2016-11-02 10:52 AM, Derek Wuelfrath wrote:
>
> *@dwlfrth* requested changes on this pull request.
>
> ------------------------------------------------------------------------
>
> In db/upgrade-X.X.X-X.Y.Z.sql 
> <https://github.com/inverse-inc/packetfence/pull/1790#pullrequestreview-6830534>:
>
> > @@ -316,3 +316,15 @@ DROP INDEX mac ON violation;
>   --
>   
>   DROP INDEX ip on inline_accounting;
> +
> +--
> +-- Alter table iplog_history
> +--
> +
> +ALTER TABLE iplog_history ADD INDEX end_time (end_time) ADD INDEX start_time (start_time);
>
> ERROR 1064 (42000): You have an error in your SQL syntax; check the 
> manual that corresponds to your MariaDB server version for the right 
> syntax to use near 'ADD INDEX start_time (start_time)' at line 1
>
> Missing comma before second ADD
>
> ------------------------------------------------------------------------
>
> In db/upgrade-X.X.X-X.Y.Z.sql 
> <https://github.com/inverse-inc/packetfence/pull/1790#pullrequestreview-6830534>:
>
> > @@ -316,3 +316,15 @@ DROP INDEX mac ON violation;
>   --
>   
>   DROP INDEX ip on inline_accounting;
> +
> +--
> +-- Alter table iplog_history
> +--
> +
> +ALTER TABLE iplog_history ADD INDEX end_time (end_time) ADD INDEX start_time (start_time);
> +
> +--
> +-- Alter table iplog_archive
> +--
> +
> +ALTER TABLE iplog_archive ADD INDEX end_time (end_time) ADD INDEX start_time (start_time);
>
> ERROR 1064 (42000): You have an error in your SQL syntax; check the 
> manual that corresponds to your MariaDB server version for the right 
> syntax to use near 'ADD INDEX start_time (start_time)' at line 1
>
> Missing comma before second ADD
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/inverse-inc/packetfence/pull/1790#pullrequestreview-6830534>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ACmeMYci_CCSrmiR5cOjx5tVYevjdrUFks5q6KO_gaJpZM4KfQYL>.
>

2016-11-02 14:55 UTC, merged