feature/pfdetect-regex-parser
inverse-inc/packetfence pull request #1838
Opened 2016-11-16 18:10 UTC by jrouzierinverse

Description
-----------
A generic parser for defining action for syslog entries

Impacts
-----------
pfdetect

NEWS file entries
-------

New Features
++++++++++++
* A new generic pfdetect parser for custom actions

Bug Fixes
+++++++++

Delete branch after merge
-------------------------
NO

2016-11-25 15:32 UTC, jrouzierinverse commented
This is ready for review

2017-01-19 21:31 UTC, jrouzierinverse commented
Please review me

2017-01-19 21:57 UTC, jrouzierinverse commented
What still needs to be done is was which Api Actions are going to be allowed to be displayed in the choice list.

@fdurand is this something you can help me with?

2017-01-19 22:43 UTC, julsemaan commented
TBH reviewing a PR of 118 commits containing 2000+ lines doesn't really seem like something that should be for 6.5 with the release window we have

I'll leave the call to @extrafu but considering the huge amount of code there is, it doesn't look like it can be reviewed+tested correctly in the limited amount of time we have, especially considering there is still a missing piece in the PR and the end of the merge window was a few hours ago

There's nothing stopping us from having a small 6.6 with this being the main feature in 4-5 weeks

![image](https://cloud.githubusercontent.com/assets/3857942/22128436/912dc2bc-de6e-11e6-9b8b-3dfc62e67b72.png)

2017-01-20 13:38 UTC, extrafu commented
Please @fdurand and @julsemaan give it a try and we'll advise after.

2017-01-20 13:56 UTC, julsemaan commented
What I can see missing now (didn't fully look at the code yet):
- Review+adjust documentation of admin guide for syslog parsers creation (like suricata MD5, security onion, ...)
- Documentation on new regex parsers and how to use them (especially for the actions)

Will test it out, but I still maintain my point of this being too last minute. Because even if the code works it doesn't mean it can be reviewed correctly.

2017-01-20 14:24 UTC, julsemaan reviewed
The detect parsers unit test are broken because of the logic change in the factory

2017-01-20 14:26 UTC, julsemaan requested changes
for now found:
- missing doc
- broken unit tests

2017-01-20 14:30 UTC, julsemaan commented
Suricata/snort parser is working as expected in an integration test

2017-01-20 14:34 UTC, julsemaan requested changes
Suricata parser shows as disabled in the admin, but the pfdetect process is started and working

Note that this is an existing parser I had and not one I created while testing

conf:
[suricata]
type=suricata
path=/usr/local/pf/var/suricata_alert

![image](https://cloud.githubusercontent.com/assets/3857942/22153048/9129e4fa-def3-11e6-8745-268cf6bf53d7.png)

2017-01-20 14:36 UTC, julsemaan commented on lib/pf/detect/parser.pm
> +has enabled => (is => 'rw', default =>  sub { "enabled" });
Same semantic logic as in pfmon, we should use status and not enabled as the attribute name

2017-01-20 14:40 UTC, julsemaan requested changes
When creating a new regex syslog parser, clicking save doesn't do a thing (Firefox on Ubuntu 16)

Config I have:
![image](https://cloud.githubusercontent.com/assets/3857942/22153229/737847d4-def4-11e6-9b22-878e6e17a460.png)

EDIT: I found the issue. Its that nothing was defined in the rule and the mandatory fields in it were required. Nothing indicated were the issue was. Should there be an issue with a rule, it should expand the rule so we can see the error

2017-01-20 14:43 UTC, julsemaan requested changes
Success/error should display below the navigation bar like in other sections

![image](https://cloud.githubusercontent.com/assets/3857942/22153333/e9a61936-def4-11e6-94f8-50e193b89065.png)

2017-01-20 14:45 UTC, julsemaan requested changes
The help contains a lorem ipsum instead of real help

2017-01-20 14:47 UTC, julsemaan commented
I'll stop here for now and let @jrouzierinverse review the requested changes and we'll continue after

With the amount of new UI and the alpha stage were that code is, I don't really consider this as 6.5 material as we'll have to spend quite a bit of time testing + adjusting this instead of focusing on the already big amount of features that have been merged in 6.5 which also require to be tested

2017-01-20 15:06 UTC, fdurand commented
When i try to create a dhcp parser.

 httpd.admin(11338) ERROR: Caught exception in pfappserver::Controller::Config::Pfdetect->view "Can't call method "process" on an undefined value at /usr/local/pf/html/pfappserver/lib/pfappserver/Base/Controller/Crud.pm line 206." (pfappserver::PacketFence::Controller::Root::end)

2017-01-20 16:22 UTC, jrouzierinverse commented
Fixed
* Tests 
* Creating a dhcp parser
* Poddoc
* Upgrade instructions
* Expand accordions on error.

Updating the documentation is the next thing to complete.

2017-02-13 15:16 UTC, extrafu commented
What is the status of the PR? We need to merge it ASAP to begin testing.

2017-02-13 15:30 UTC, julsemaan commented
Won't re-read the whole code so I'd say this is fairly ready.

As long as @jrouzierinverse reviewed the admin guide to make sure syslog parser sections are still relevant for this new PR, then this is ready for testing/merging

2017-02-13 15:30 UTC, julsemaan approved these changes

2017-02-13 20:40 UTC, jrouzierinverse commented
Check documentation update please

2017-02-13 22:15 UTC, extrafu commented
@julsemaan said ".. As long as @jrouzierinverse reviewed the admin guide ... " - have you done so?

2017-02-13 22:35 UTC, merged

2017-02-13 22:43 UTC, extrafu commented
@jrouzierinverse You haven't answered my question before merging.

2017-02-13 23:10 UTC, jrouzierinverse commented
Sorry