Select radius interface
inverse-inc/packetfence pull request #1887
Opened 2016-12-06 18:34 UTC by fdurand

# Description
Define for an interface if you want to have radius available

# Impacts
Radius Workflow

# Delete branch after merge
YES

# NEWS file entries
## New Features
* Define on interface if radius must listen on.

2017-01-04 16:12 UTC, julsemaan commented on lib/pf/Switch.pm
> +    my $int = $chi->compute($dst_ip, sub {
We need to validate that the result of this is a valid interface configured in PacketFence

2017-01-04 16:12 UTC, julsemaan commented on lib/pf/services/manager/keepalived.pm
> +    my @ints = uniq(@listen_ints,@dhcplistener_ints, map { $_->{'Tint'} } @portal_ints, @radius_ints);
wrap the map in parentheses so its clearer what you are mapping and to make sure it only applies to what you want:
`uniq(@listen_ints,@dhcplistener_ints, (map { $_->{'Tint'} } @portal_ints, @radius_ints));`

2017-01-04 16:49 UTC, julsemaan commented
I'll find some time to test it a bit

2017-01-04 16:56 UTC, julsemaan commented on lib/pf/Switch.pm
> +        $logger->warn("Interface $int has not been found in the configuration, using the management interface");
that logger is not defined

2017-01-04 19:01 UTC, julsemaan commented
If I add radius as an additional listening daemon on a registration network, it doesn't add it in pf.conf and makes the interface become of the 'Other' type in the admin

2017-01-04 19:03 UTC, julsemaan commented
Also, there is no way to put an interface in type 'radius' from the admin, its only possible to put it as an additionnal listening daemon

2017-01-04 19:11 UTC, julsemaan commented
Other than my 2 comments above it seems to do what it says

2017-02-07 14:30 UTC, julsemaan requested changes
A few changes here and there and we're good to merge

2017-02-07 14:30 UTC, julsemaan commented on lib/pf/ConfigStore/Network.pm
> +        my @types = split(',',$network->{type});
split while cleaning up spaces

2017-02-07 14:30 UTC, julsemaan commented on lib/pf/Switch.pm
> +                                         my @interface_src = split(" ", `LANG=C sudo ip route get $dst_ip`);
Use pf_run ?

2017-02-07 14:30 UTC, julsemaan commented on lib/pf/services/manager/radsniff.pm
> +sub make_filter {
Missing perldoc

2017-02-07 14:30 UTC, julsemaan commented on lib/pfconfig/namespaces/interfaces/radius_ints.pm
> +package pfconfig::namespaces::interfaces::radius_ints;
perldoc for the two subs in this module

2017-02-08 01:13 UTC, extrafu commented
Bump

2017-02-08 14:28 UTC, merged