Let's haproxy listen on portal interfaces
inverse-inc/packetfence pull request #1893
Opened 2016-12-09 19:12 UTC by fdurand

# Description
Enable haproxy on portal interfaces

# Impacts
Portal

# Issue
If we define portal interfaces in cluster mode in another place than on the management interface then haproxy will not listen on the vip

# Delete branch after merge
YES

# NEWS file entries

## Bug Fixes
* Enable haproxy on portal interface

2016-12-23 18:49 UTC, fdurand commented
Bump

2017-01-03 14:12 UTC, julsemaan requested changes

2017-01-03 14:12 UTC, julsemaan commented on lib/pf/services/manager/haproxy.pm
> +        if ($cfg->{'type'} =~ /internal/ | $cfg->{'type'} =~ /portal/) {
Not sure that binary OR is really doing what you want

Should be `||`

2017-01-04 14:27 UTC, fdurand commented
Change done

2017-01-04 15:02 UTC, merged