feature/proxy-auth
inverse-inc/packetfence pull request #1998
Opened 2017-01-31 19:42 UTC by jrouzierinverse

Description
-----------
New Source that allows users to log in using an http proxy

Impacts
-----------
Admin GUI login

NEWS file entries
-------

New Features
++++++++++++
* New source for logging into the Admin GUI using an http proxy

Delete branch after merge
-------------------------
NO

2017-01-31 19:46 UTC, jrouzierinverse commented
Review me

2017-02-07 16:12 UTC, julsemaan commented
This needs a documentation section in the admin guide

2017-02-07 16:24 UTC, julsemaan requested changes

2017-02-07 16:24 UTC, julsemaan commented on html/pfappserver/lib/pfappserver/Authentication/Credential/Proxy.pm
> +
Missing perldoc on subs

2017-02-07 16:24 UTC, julsemaan commented on html/pfappserver/lib/pfappserver/Form/Config/Authentication/Source/AdminProxy.pm
> +has_field 'proxy_addresses' => (
Can there be multiple addresses ? If so, this needs a validator as well as help text on how to separate the addresses

2017-02-07 16:24 UTC, julsemaan commented on html/pfappserver/lib/pfappserver/I18N/i_default.po
> -en.po
Not sure that you should modify this to put the strings back in it. My understanding was that en.po was the only place where they needed to be

2017-02-07 16:24 UTC, julsemaan commented on lib/pf/Authentication/Source/AdminProxySource.pm
> +package pf::Authentication::Source::AdminProxySource;
I might be wrong, but I don't see anything preventing this source from being put on a portal profile by mistake

If its only for use in the admin, it should be removed from the portal profiles sources choices

2017-02-07 17:24 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/I18N/i_default.po
> -en.po
That was a rebase issue I will fix that

2017-02-22 14:28 UTC, jrouzierinverse commented
Bump

2017-02-22 20:35 UTC, julsemaan commented
Please rebase onto devel and I'll take a look at it for the required changes

2017-02-22 20:41 UTC, jrouzierinverse commented
Done

2017-02-22 20:50 UTC, merged