trigger a violation when node is discovered (added)
inverse-inc/packetfence pull request #2008
Opened 2017-02-03 19:11 UTC by julsemaan

# Description
Allow to trigger a violation when a node is discovered (added)

# Impacts
node_add flow

# Delete branch after merge
YES

# NEWS file entries
## New Features

## Enhancements
* Allow to trigger a violation and its actions when a node is discovered

2017-02-03 19:51 UTC, jrouzierinverse requested changes
Looks good outside of the configuration issue.

2017-02-03 19:51 UTC, jrouzierinverse commented on conf/pfqueue.conf.example
> +has_delayed_queue=enabled
Should be in conf/pfqueue.conf.defaults

2017-02-07 13:29 UTC, fdurand commented
Except the comment of James i am ok to merge.

2017-02-07 13:50 UTC, julsemaan commented
Fixed according to james comment

2017-02-07 13:58 UTC, merged