added mikrotik webauth support
inverse-inc/packetfence pull request #2056
Opened 2017-02-28 16:29 UTC by julsemaan

# Description
Adds support to Mikrotik webauth

## WARNING: This is not fully tested as I don't have access to the equipment

# Impacts
Mikrotik

# Delete branch after merge
YES

# NEWS file entries
## New Features
* Added support for web authentication for the Mikrotik access points

2017-02-28 16:30 UTC, julsemaan commented
@dwlfrth, I developped this under a pre-webauth-refactor version

Could you make sure I followed the appropriate steps to have it working under the current version

2017-03-08 20:43 UTC, extrafu commented
Bump - @dwlfrth what's up on this?

2017-03-09 19:17 UTC, dwlfrth requested changes
Other than the one comment, LGTM

2017-03-09 19:17 UTC, dwlfrth commented on lib/pf/Switch/Mikrotik.pm
> +        ssid            => undef,
No need to specify undef parameters since they are undef by default in lib/pf/web/externalportal.pm

2017-03-09 19:19 UTC, julsemaan commented
fixaide

2017-03-09 19:43 UTC, merged