Feature/replace portal by connection
inverse-inc/packetfence pull request #2066
Opened 2017-03-01 19:34 UTC by whitx

# Description
It is time to move out from portal profile to connection profile

# Impacts
Portal, portal profile, connection

# Delete branch after merge
YES

# NEWS file entries
## Enhancements
* Portal Profile has been renamed as Connection Profile

# UPGRADE file entries

2017-03-01 19:41 UTC, whitx commented
Tested the flow with 2 different connection profile, the user is properly send to the wanted connection profile.

2017-03-01 20:34 UTC, julsemaan commented on lib/pf/Portal/Profile.pm
I was expecting this file to be renamed as well to lib/pf/Connection/Profile.pm and the class name to be changed

2017-03-01 20:34 UTC, julsemaan commented on lib/pf/Portal/Session.pm
> +Returns the proper captive connection profile for the current session.
captive connection profile->connection profile

2017-03-01 20:40 UTC, whitx commented on lib/pf/Portal/Profile.pm
Alright make sense, working on it

2017-03-13 15:05 UTC, extrafu commented
Reybaisse

2017-03-14 18:22 UTC, whitx commented
rebaissed

2017-03-14 18:24 UTC, extrafu commented
@julsemaan and @dwlfrth BUMP! This needs to be merged ASAP to get good testing and easy other PRs.

2017-03-14 18:28 UTC, dwlfrth commented
Not quite sure the "Enhancement" section is really an ... enhancement ?
Also, missing UPGRADE notes which seems to be mandatory due to configuration file change

2017-03-14 18:44 UTC, dwlfrth requested changes
Not sure we want to move Portal::Session to Connection::Session

Also, is everything working fine following the changes ?

2017-03-14 18:44 UTC, dwlfrth commented on docs/PacketFence_Cisco_MSE_Quick_Install_Guide.asciidoc
>  image::docs/images/Portal_filter.png[scaledwidth="100%",alt="Portal Filter"]
Should we adjust the screenshots ? (and image path / alt text)

2017-03-14 18:44 UTC, dwlfrth commented on docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
> -Add the authentication for the Captive Portal Profile via `Security -> Authentication -> L3 Authentication -> Captive Portal Authentication Profile -> Server Group`:
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
> -Now add the newly created policy to the Captive Portal Profile, `Security -> User Roles`:
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on html/captive-portal/lib/captiveportal.pm
> -    return $c->model('Portal::Session');
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on html/captive-portal/lib/captiveportal/Model/Connection/Session.pm
> -package captiveportal::Model::Portal::Session;
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on html/captive-portal/lib/captiveportal/Model/Connection/Session.pm
> -extends 'captiveportal::PacketFence::Model::Portal::Session';
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on html/captive-portal/lib/captiveportal/Model/Connection/Session.pm
> -captiveportal::Model::Portal::Session - Catalyst Model
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on html/captive-portal/lib/captiveportal/PacketFence/Controller/Activate/Email.pm
> -use pf::Portal::Session;
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on html/captive-portal/lib/captiveportal/PacketFence/Controller/Root.pm
> -use pf::Portal::Session;
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Root.pm
> -use pf::Portal::Session;
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Root.pm
> -    my $session = new pf::Portal::Session()->session;
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on html/captive-portal/lib/captiveportal/PacketFence/Model/Connection/Session.pm
> +package captiveportal::PacketFence::Model::Connection::Session;
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on html/captive-portal/lib/captiveportal/PacketFence/Model/Connection/Session.pm
> +captiveportal::PacketFence::Model::Connection::Session - Catalyst Model
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on html/captive-portal/lib/captiveportal/PacketFence/Model/Connection/Session.pm
> -    my $session = new pf::Portal::Session()->session;
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on html/captive-portal/lib/captiveportal/PacketFence/Model/Connection/Session.pm
> +    my $session = new pf::Connection::Session()->session;
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on lib/pf/Connection/Session.pm
> +package pf::Connection::Session;
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on lib/pf/Connection/Session.pm
> +pf::Connection::Session
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on lib/pf/Connection/Session.pm
> +pf::Connection::Session wraps several parameter we often need from the captive
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on lib/pf/web/dispatcher.pm
> -use pf::Portal::Session;
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on lib/pf/web/externalportal.pm
> -use pf::Portal::Session;
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on lib/pf/web/externalportal.pm
> -    my $portalSession = pf::Portal::Session->new(%info);
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on lib/pf/web/release.pm
> -use pf::Portal::Session;
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on lib/pf/web/release.pm
> -  my $portalSession     = pf::Portal::Session->new();
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on lib/pf/web/wispr.pm
> -use pf::Portal::Session;
Nope !

2017-03-14 18:44 UTC, dwlfrth commented on lib/pf/web/wispr.pm
> -    my $portalSession = pf::Portal::Session->new();
Nope !

2017-03-14 20:28 UTC, extrafu commented
Rebase

2017-03-17 14:36 UTC, dwlfrth approved these changes

2017-03-17 14:37 UTC, merged