X-Frame-Options SAMEORIGIN enforced for browsers that supports it.
inverse-inc/packetfence pull request #2111
Opened 2017-03-22 18:10 UTC by tlaurion

# Description
X-Frame-Options informs browsers if it should render a webpage in a frame for a specific domain.
We now instruct that only the domain associated with pf should render pages for its domain in a frame.

This is mitigates clickjacking attacks.

# Impacts
(REQUIRED)
Describe what to reviewer should look at. Will also help for testing purposes.
ie: - RADIUS authorize workflow

# Code / PR Dependencies
(OPTIONAL. REMOVE IF NOT NEEDED)
List the PRs or other factors on which this PR depends

# NEW Package(s) required
(OPTIONAL. REMOVE IF NOT NEEDED)
Which new package(s) (all supported distributions) are required for this PR to work.

# Issue
(OPTIONAL. REMOVE IF NOT NEEDED)
The following syntax 'fixes #ISSUE_NUMBER' will automatically closes a Github issue on pull-request merge time.
Modify the ISSUE_NUMBER in order to reflect the Github issue that need to be closed
fixes #ISSUE_NUMBER

# Delete branch after merge
(REQUIRED)
YES | NO

# NEWS file entries
(REQUIRED, but may be optional...)
## New Features
* Feature 1
* Feature 2

## Enhancements
* Enhancement 1
* Enhancement 2

## Bug Fixes
If an issue exists on Github, please refer to it (name) along with it's number...
* Issue with Zammitbug in sandwich context (#42)
* Issue with Zammitbug in dinde context (#43)

# UPGRADE file entries
(OPTIONAL, but may be required...)

2017-03-24 19:39 UTC, jrouzierinverse requested changes

2017-03-24 19:39 UTC, jrouzierinverse commented on conf/httpd.conf.d/httpd.webservices.tt.example
> +Header always append X-Frame-Options SAMEORIGIN
We do not need it here

2017-03-24 19:39 UTC, jrouzierinverse commented on conf/httpd.conf.d/httpd.proxy.tt.example
> +Header always append X-Frame-Options SAMEORIGIN
I am not sure if this is should be here as it may break external sites

2017-03-24 21:01 UTC, jrouzierinverse commented
rebase

2017-03-24 21:18 UTC, tlaurion commented
rabayzed.

2017-03-26 16:22 UTC, merged

2017-05-23 17:00 UTC, tlaurion commented
@jrouzierinverse : Could you validate that Mirapay was manually tested against a recent PF7 deployment just to make sure that the headers didn't break that feature? (it shouldn't but we were unsure)