Use returned radius attributes in order to tests them in rules
inverse-inc/packetfence pull request #2369
Opened 2017-05-31 16:12 UTC by fdurand

# Description
When you do radius authentication (radius source) you can use the radius attributes returned in the answer in order to use it to compute some rules.

# Impacts
Authentication flow

# Delete branch after merge
YES

# NEWS file entries

## Enhancements
* Use the attributes returned by a radius use source as attributes to compute the rules.

2017-06-14 14:12 UTC, dwlfrth commented
@jrouzierinverse see if it conflicts with authentication sources rework. Let @fdurand know and adjust.
Depending on the work, we aim at 7.2

2017-06-14 15:57 UTC, jrouzierinverse commented
There are no conflicts

2017-06-14 20:42 UTC, jrouzierinverse requested changes
Extra is not used for matching here
html/captive-portal/lib/captiveportal/PacketFence/Controller/DeviceRegistration.pm

Extra is not save in the session here
html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Login.pm

In create_local_account extra is not used for matching there

html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication.pm

Should we use extra here even though these sources do not return the extra field
html/captive-portal/lib/captiveportal/PacketFence/Controller/Activate/Email.pm
html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Sponsor.pm

2017-06-14 20:42 UTC, jrouzierinverse commented on lib/pf/Authentication/Source/RADIUSSource.pm
> +        for my $attribute (@{ $extra->{attributes}} ) {
Add a check to make sure extra is defined

2017-06-15 12:28 UTC, fdurand commented
Extra is save in the session here
html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Login.pm +207

Also not sure we have to use the extra field in email and sponsor. Right now only radius source support this extra field.

2017-06-15 13:33 UTC, jrouzierinverse reviewed
Has compile errors

2017-06-15 13:33 UTC, jrouzierinverse commented on lib/pf/Authentication/Source/RADIUSSource.pm
> +        if defined($extra->{attributes}) {
That would not compile you forgot to put () around your condition. 
Yes switching between go and perl is annoying
Just check if $extra is defined
if (defined $extra) {

2017-06-15 18:40 UTC, jrouzierinverse approved these changes

2017-06-15 18:40 UTC, merged