Fix/2377 fix permissions from gui
inverse-inc/packetfence pull request #2398
Opened 2017-06-14 19:32 UTC by dwlfrth

# Description
Add the ability to "fix permissions" from the GUI

# Impacts
Admin GUI

# Issue
fixes #2377

# Delete branch after merge
YES

# NEWS file entries
## Enhancements
* Ability to run "fixpermissions" from the web admin GUI

## Bug Fixes
* fixpermission from the webadmin (#2377)

2017-06-15 14:39 UTC, jrouzierinverse requested changes
After performing a fix permissions.

The fix permission option in the menu is no longer available unless I refresh the page.

The same behavior is found in perform checkup.

2017-06-15 14:39 UTC, jrouzierinverse commented on lib/pf/util.pm
> +=item fix_files_permissions
Maybe a better name fix_permissions_all.
I find the name to close to the other function.

2017-06-15 14:42 UTC, julsemaan commented
@jrouzierinverse, the checkup already had that behavior to prevent doing it 5 times if the user wanted to refer to it 5 different times given it takes a lot of time to accomplish.

IMO, I'd leave it to that behavior for all items of this menu but in the end you guys can decide together what is best

2017-06-15 14:42 UTC, julsemaan approved these changes

2017-06-15 14:45 UTC, jrouzierinverse commented
@julsemaan As a policy you should clear a review unless you have done it.

2017-06-15 14:46 UTC, jrouzierinverse commented
There was an additional issue there that was not addressed

2017-06-15 14:49 UTC, jrouzierinverse commented
There should be at least a way to clear and rerun the results since some people would not know how rerun those commands.

2017-06-15 14:51 UTC, cgx commented
I agree with @jrouzierinverse.

@dwlfrth: let me know if you need help.

2017-06-15 14:51 UTC, julsemaan commented
@jrouzierinverse

I didn't clear your review, I just approved the PR since my review was requested on it yesterday

If you look, yours is still in place and left the PR in 'Changes requested'

2017-06-15 14:55 UTC, jrouzierinverse commented
@julsemaan Sorry you are correct

2017-06-15 15:21 UTC, julsemaan commented
@jrouzierinverse 

No problem, this gave me an idea for your next Christmas gift:
![image](https://user-images.githubusercontent.com/3857942/27188593-9498536a-51bc-11e7-991d-24a274b2a741.png)

2017-06-15 15:25 UTC, jrouzierinverse commented
Thanks!

2017-06-16 19:27 UTC, dwlfrth commented
@jrouzierinverse maybe you could have a look at that additional issue (Option to have it automated when we detect a file permission issue.)

2017-06-19 14:58 UTC, dwlfrth commented
GUI is adjusted.
@jrouzierinverse, are you taking care of the additional issue ?

2017-06-19 15:03 UTC, merged