run the 6+ upgrade scripts as the PF user
inverse-inc/packetfence pull request #2509
Opened 2017-07-20 20:12 UTC by julsemaan

# Description
run the 6+ upgrade scripts as the PF user

# Impacts
Upgrade scripts

# Issue
part of the fix for #2378 

# Delete branch after merge
YES

# NEWS file entries
## Bug Fixes
* Run the 6.0+ upgrade scripts as the pf user to prevent permissions issues after running them

2017-08-17 23:30 UTC, fdurand commented
Agree to merge

2017-08-22 18:28 UTC, jrouzierinverse requested changes

2017-08-22 18:28 UTC, jrouzierinverse commented on lib/pf/util.pm
> +    my (undef, undef,$uid,$gid) = getpwnam('pf');
Check if current user if already pf before running setgid and setuid.

2017-08-22 18:28 UTC, jrouzierinverse commented on lib/pf/util.pm
> +    setgid($gid);
Check for errors and log them

2017-08-22 18:28 UTC, jrouzierinverse commented on lib/pf/util.pm
> +    setuid($uid);
Check for errors and log them

2017-08-24 12:29 UTC, julsemaan commented
Should be all polished up, ready for another review

2017-08-24 12:44 UTC, jrouzierinverse requested changes

2017-08-24 12:44 UTC, jrouzierinverse commented on lib/pf/util.pm
> +    my (undef, undef,$uid,$gid) = getpwnam('pf');
Just compare $< to $uid instead of using running_as since the environmental variables could be modified.

2017-08-24 12:52 UTC, julsemaan commented
done

2017-08-24 13:54 UTC, jrouzierinverse approved these changes

2017-08-24 13:54 UTC, merged