fix/violation-delete
inverse-inc/packetfence pull request #2541
Opened 2017-08-09 14:34 UTC by jrouzierinverse

Description
===========
Removes violation from database when deleting violation from config

Impacts
=======
Violation handling in the config

Issue
=====
Fixes #2539

Delete branch after merge
=========================
NO

NEWS file entries
=================

Bug Fixes
------------
* Fixes violation definition sync when removing a violation from the config

2017-08-17 23:38 UTC, fdurand commented
It fix an issue when you remove a violation config but also delete the current open violation for this violation id.
Do we have to archive instead of removing ?

2017-08-18 14:18 UTC, jrouzierinverse commented
Remove class not in config

2017-08-18 14:20 UTC, jrouzierinverse commented
- [ ] Delete violation show message before deleting. 
- [ ] Disable from the index page.

2017-08-21 16:35 UTC, jrouzierinverse commented
Please review

2017-08-25 14:05 UTC, fdurand commented on html/pfappserver/lib/pfappserver/PacketFence/Controller/Violation.pm
> +    ); # TODO: localize error message
Todo

2017-08-25 16:39 UTC, jrouzierinverse commented
Done

2017-08-29 18:23 UTC, fdurand requested changes

2017-08-29 18:23 UTC, fdurand commented on html/pfappserver/root/violation/list.tt
> +          <p>[% l('Deleting this violation will close all triggered violations associated with this violation.') %]</p>
Deleting this violation will remove ...

2017-08-29 18:45 UTC, jrouzierinverse commented
Done

2017-08-29 19:29 UTC, merged