Feature/self service by profile
inverse-inc/packetfence pull request #2546
Opened 2017-08-10 18:24 UTC by whitx

# Description
Allow the creation of device registration profile to be associated with connection profile

# Impacts
Device registration workflow, connection profile workflow

# Delete branch after merge
NO

# NEWS file entries
## Enhancements
* Improved device registration to be able to create profiles, this allow you to associate device registration profile by connection profile

# UPGRADE file entries
You will need to remove anything related [device_registration] in the conf/pf.conf file.

2017-08-10 18:39 UTC, extrafu commented on docs/PacketFence_Administration_Guide.asciidoc
> +This will allow you to configure who is able to register which type of device. For instance a person connection from the public WiFi can only register Android but a person from the intern network can
For instance a person connection from the public WiFi can only register Android but a person from the intern network can register Windows and Mac. => For instance a person connecting from the public WiFi can only register an Android device but a person from the internal network can register Windows and MacOS computers.

2017-08-10 18:39 UTC, extrafu commented on html/pfappserver/lib/pfappserver/Form/Config/DeviceRegistration.pm
> +   messages => { required => 'Please specify the ID of the Device Registration entry.' },
Not very clear

2017-08-10 18:40 UTC, extrafu commented on html/pfappserver/lib/pfappserver/Form/Config/DeviceRegistration.pm
> +             help => 'List of OS which will be allowed to register via the self service portal.' },
will be allowed to be registered

2017-08-17 23:39 UTC, fdurand commented
I like this feature, just need to test it before merging

2017-08-18 18:49 UTC, fdurand commented on html/captive-portal/lib/captiveportal/PacketFence/Controller/Status.pm
> +    if (defined( $c->profile{'device_registration'} ) ) {
$c->profile->{'device_registration'}   ?

2017-08-18 19:22 UTC, fdurand commented on html/pfappserver/lib/pfappserver/Form/Config/ProfileCommon.pm
> +has_field 'devices_registration' =>
device_registration or devices_registration ?

2017-08-18 19:23 UTC, fdurand commented on html/pfappserver/lib/pfappserver/PacketFence/Controller/Config/DeviceRegistration.pm
> +#use pf::factory::device_registration;
remove

2017-08-18 20:04 UTC, fdurand commented on html/captive-portal/lib/captiveportal/PacketFence/Controller/Status.pm
> +    if (defined( $c->profile{'device_registration'} ) ) {
$c->profile->{'_devices_registration'}

2017-08-18 20:25 UTC, fdurand commented
Still have $Config{'device_registration'}{'status'} in the code

2017-08-25 20:15 UTC, fdurand commented
Tested and works.
It just miss the packaging stuff.

2017-08-29 19:38 UTC, fdurand requested changes

2017-08-29 19:38 UTC, fdurand commented on addons/packages/packetfence.spec
> +%config                 /usr/local/pf/conf/device_registration.conf.example
Remove %config for example file

2017-08-29 19:38 UTC, fdurand commented on html/pfappserver/lib/pfappserver/Form/Config/DeviceRegistration.pm
> +   messages => { required => 'Please specify an name of the Device Registration entry.' },
Please specify a name ...

2017-08-29 19:38 UTC, fdurand commented on html/pfappserver/lib/pfappserver/Form/Config/DeviceRegistration.pm
> +   messages => { required => 'Please specify the Description of the Device Registration entry.' },
Please specify the description.

2017-08-29 19:38 UTC, fdurand commented on html/pfappserver/lib/pfappserver/Form/Config/ProfileCommon.pm
> +has_field 'device_registration' =>
Can it be unique ?

2017-08-29 19:38 UTC, fdurand commented on html/pfappserver/lib/pfappserver/Model/Config/DeviceRegistration.pm
> +
Remove spaces

2017-08-31 17:49 UTC, fdurand commented
ERROR: [mac:unknown] Caught exception in pfappserver::Controller::Config::Profile->view "isa check for "cachedConfig" failed: Use of uninitialized value in subroutine entry at /usr/local/pf/lib/pf/ConfigStore.pm line 34." (pfappserver::PacketFence::Controller::Root::end)

2017-08-31 18:12 UTC, merged