Fix/2815
inverse-inc/packetfence pull request #2893
Opened 2018-01-15 15:40 UTC by julsemaan

# Description
Don't allow the portal FQDN as a passthrough

# Impacts
Passthroughs + the admin interface

# Issue
fixes #2815 

# Delete branch after merge
YES

# NEWS file entries
## Bug Fixes
* Don't allow the portal domain name as a passthrough (#2815)

2018-01-16 19:20 UTC, extrafu commented
Looks good to me. @jrouzierinverse please also review.

2018-01-16 21:36 UTC, jrouzierinverse requested changes

2018-01-16 21:36 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/Pf.pm
> +        "fencing.isolation_passthroughs" => sub { validate_fqdn_not_in_passthroughs(@_, "isolation_passthroughs") },
This would be better as static lookup hash to avoid creating the same data multiple times.

2018-01-16 21:36 UTC, jrouzierinverse commented on lib/pf/util/dns.pm
> +    return _matches_passthrough(eval("\\%$zone"), $domain);
Avoid the use of eval as it is unsafe.

A safer approach is to create a lookup table for which hash to use.

2018-01-16 21:36 UTC, jrouzierinverse commented on t/unittest/util/dns.t
> +($match, $ports) = pf::util::dns::matches_passthrough(undef, 'passthroughs');
Add a test for undef zone also.

2018-01-16 21:36 UTC, jrouzierinverse commented on t/unittest/util/dns.t
> +($match, $ports) = pf::util::dns::matches_passthrough(undef, 'passthroughs');
Add a test for wild-isolation.zammitcorp.com

2018-01-16 21:36 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/Pf.pm
> +        "fencing.isolation_passthroughs" => sub { validate_fqdn_not_in_passthroughs(@_, "isolation_passthroughs") },
Also there should also be a check if someone changes the hostname or domain to a current passthrough domain.

2018-01-17 02:06 UTC, jrouzierinverse commented on lib/pf/util/dns.pm
> +    return _matches_passthrough(eval("\\%$zone"), $domain);
Example

```bash
perl -I/usr/local/pf/lib -Mpf::util::dns -e'pf::util::dns::matches_passthrough(undef, "passthroughs,print(\"gotcha\\n\"),\%passthroughs");'```

2018-01-18 19:26 UTC, julsemaan commented
Performed the requested adjustments, please re-review

2018-01-18 21:19 UTC, jrouzierinverse approved these changes

2018-01-18 21:19 UTC, merged