Feature/multitenant api violations
inverse-inc/packetfence pull request #2914
Opened 2018-01-28 21:13 UTC by satkunas

# Description
Add violations to multitenant UnifiedAPI

# Impacts
None

# Delete branch after merge
YES

# NEWS file entries
## New Features
* Add violations to multitenant UnifiedAPI

2018-01-29 14:28 UTC, julsemaan commented
For violations, we also need violation_trigger to be exposed through the API

2018-01-29 14:28 UTC, julsemaan commented on t/unittest/UnifiedApi/Controller/Violations.t
> +my $violation_status = pf::violation::violation_add($mac, $vid, (
Posting to /violations should do exactly this behavior, so use it instead of calling pf::violation::violation_add

2018-01-29 16:53 UTC, jrouzierinverse requested changes

2018-01-29 16:53 UTC, jrouzierinverse commented on lib/pf/UnifiedApi/Controller/Violations.pm
> +has resource_id => 'pid';
Needs to be the database primary key 'id'
Replace this
```perl
resource_id => 'pid';
```
With this
```perl
resource_id => 'id';
```

2018-01-30 21:25 UTC, jrouzierinverse approved these changes

2018-01-30 21:25 UTC, merged