Feature/api ip4log
inverse-inc/packetfence pull request #2952
Opened 2018-02-14 17:31 UTC by satkunas

# Description
Adds ip4logs to API

# Impacts
Exposes ip4log, ip4log_history and ip4log_archive to API

# Delete branch after merge
YES 

# NEWS file entries
## New Features
* Add ip4logs to API

2018-02-14 17:45 UTC, jrouzierinverse requested changes

2018-02-14 17:45 UTC, jrouzierinverse commented on lib/pf/UnifiedApi/Controller/Ip4logs.pm
> +has id_key => 'ip4log_id';
```perl
has url_param_name => 'ip4log_id';
```

2018-02-14 17:45 UTC, jrouzierinverse commented on lib/pf/UnifiedApi/Controller/Ip4logs.pm
> +has resource_id => 'tenant_id';
```perl
has primary_key => 'ip';
```

2018-02-15 18:07 UTC, extrafu commented
@jrouzierinverse Please review and merge.

2018-02-15 18:25 UTC, jrouzierinverse requested changes

2018-02-15 18:25 UTC, jrouzierinverse commented on lib/pf/UnifiedApi.pm
> +                'search/:search' => { get => 'search' },
Rename search route and method

2018-02-16 13:47 UTC, extrafu commented
@jrouzierinverse Please merge if all is good. We need this done.

2018-02-16 15:41 UTC, rouzier requested changes

2018-02-16 15:41 UTC, rouzier commented on lib/pf/UnifiedApi/Controller/Ip4logs.pm
> +has id_key => 'ip4log_id';
url_param_name

2018-02-16 15:41 UTC, rouzier commented on lib/pf/UnifiedApi/Controller/Ip4logs.pm
> +    return $self->render(json => $iplog[0]) if $iplog[0];
Put this as an {item => }
```perl
return $self->render(json => {item => $iplog[0]}) if $iplog[0];
 ```

2018-02-19 22:26 UTC, merged