feature/enable-disable-profiles
inverse-inc/packetfence pull request #3175
Opened 2018-04-23 19:56 UTC by jrouzierinverse

Description
===========
Allow profiles to enabled/disabled

Impacts
=======
Captive Portal/ ProfileFactory

Issue
=====
Fixes #3170

NEWS file entries
=================

Enhancements
------------
* Allow profiles to be enabled/disabled

2018-05-25 18:17 UTC, jrouzierinverse commented
Bump!
https://www.youtube.com/watch?v=UfM3kMz-6c4

2018-05-26 03:19 UTC, fdurand commented
it miss status parameter in the checkup.

2018-05-31 01:31 UTC, fdurand requested changes

2018-05-31 01:31 UTC, fdurand commented on html/pfappserver/lib/pfappserver/Form/Config/ProfileCommon.pm
> +             help => 'If profile is disabled it will not be presented to the user' },
Not really true, a connection profile is instantiate in multiples cases.
So something like that: If profile is disabled it will not be used.

2018-05-31 14:49 UTC, jrouzierinverse commented
Updated

2018-06-01 15:10 UTC, fdurand commented
Can you rebase ?

2018-06-01 16:32 UTC, jrouzierinverse commented
Done

2018-06-01 18:15 UTC, fdurand approved these changes

2018-06-01 18:15 UTC, merged