rework maintenance script to be able to patch golang binaries
inverse-inc/packetfence pull request #3214
Opened 2018-05-03 12:36 UTC by julsemaan

# Missing
- Debian handling

# Description
Allow to patch Golang binaries through the maintenance branch

# Impacts
Maintenance script

# Delete branch after merge
YES

# NEWS file entries
## Enhancements
* Can now patch the Golang binaries through the maintenance script (addons/pf-maint.pl)

2018-05-03 12:40 UTC, extrafu commented on addons/pf-maint.pl
> +    "pfdhcp",
How about pfstats?

2018-05-03 12:41 UTC, extrafu commented on addons/pf-maint.pl
> +        write_file("/usr/local/pf/bin/$binary", $data);
Proper error-handling there too?

2018-05-03 13:21 UTC, julsemaan commented on addons/pf-maint.pl
> +    "pfdhcp",
Just added it

2018-05-03 14:12 UTC, jrouzierinverse requested changes

2018-05-03 14:12 UTC, jrouzierinverse commented on addons/pf-maint.pl
>          chmod 0755, "$binary_path";
Change the ownership of the files to match what ever it is when it is packaged.

2018-05-07 13:51 UTC, julsemaan commented
@jrouzierinverse and @fdurand 

Please perform a final review and approve the PR if everything is fine.

I'll perform the merge since I'll be testing it right after putting it in the maintenance

2018-05-07 14:49 UTC, jrouzierinverse requested changes

2018-05-07 14:49 UTC, jrouzierinverse commented on addons/pf-maint.pl
> +    my $rc = system("gpg --list-keys | grep $BINARIES_SIGN_KEY_ID");
use 
```bash 
gpg --list-keys $BINARIES_SIGN_KEY_ID
```
To avoid additional call to grep

2018-05-07 18:15 UTC, fdurand commented
Tested on debian, ok to merge

2018-05-08 12:55 UTC, julsemaan commented
@jrouzierinverse 

Adjusted based on the comments

2018-05-08 14:00 UTC, jrouzierinverse approved these changes

2018-05-08 14:00 UTC, merged