Feature/rapid7 scan
inverse-inc/packetfence pull request #3242
Opened 2018-05-17 13:14 UTC by julsemaan

# Description
Adds Rapid7 scanning capability
Adds syslog parser to receive nexpose events

# Impacts
Scan engines (ainejaihne like @lzammit would say)

# Delete branch after merge
YES

# NEWS file entries
## New Features
* Added ability to launch Rapid7 scans from PacketFence
* Added Nexpose syslog handler
* Added ability to launch scans when receiving accounting packets

2018-05-17 14:01 UTC, jrouzierinverse commented
This should be handled the the new go pfdetect service

2018-05-17 14:02 UTC, jrouzierinverse commented
The detect parser part not everything else

2018-05-17 14:39 UTC, jrouzierinverse requested changes

2018-05-17 14:39 UTC, jrouzierinverse commented on lib/pf/condition/matches.pm
> +    return $arg =~ /\Q$match\E/i;
This will change behavior for people who depends on a case sensitive match.

List of possible solutions 

* If a case insensitive is needed recommend a regex condition with a modifier - (?i)pattern

* Create new case insensitive conditions.

* Create case sensitive conditions then document the changes in the Upgrade Guide if you have a case sensitive match start using the new match conditions.

* Don't change anything document the changes in the Upgrade Guide recommend people to change the all their conditions that are case sensitive using the regex condition.

To create an easier Upgrade path for everyone and to avoid surprises in production.
I would recommend to create two a case insensitive conditions 
* pf::condition::imatches 
* pf::condition::not_imatches

2018-05-17 14:39 UTC, jrouzierinverse commented on lib/pf/condition/not_matches.pm
> +    return $arg !~ /\Q$match\E/i;
Look comment in lib/pf/condition/matches.pm

2018-05-17 15:44 UTC, julsemaan commented on lib/pf/condition/matches.pm
> +    return $arg =~ /\Q$match\E/i;
Not sure why that was put there, this is a merge of 2 PRs

No need for this, I think thomas wanted to do that to make it easier for users.

I'll revert that change for now

2018-05-30 18:35 UTC, jrouzierinverse reviewed
Remove nexpose perl detect parser

2018-05-30 18:35 UTC, jrouzierinverse commented on lib/pf/detect/parser/nexpose.pm
> +package pf::detect::parser::nexpose;
Remove since this is done with the gopfdetect

2018-05-30 18:35 UTC, jrouzierinverse commented on t/data/pfdetect.conf
> +
Remove

2018-05-30 18:35 UTC, jrouzierinverse commented on t/unittest/detect/parser/nexpose.t
> +=head1 NAME
Remove

2018-05-31 20:26 UTC, lzammit commented
Missing the engineId parameter in the admin interface configuration

2018-06-01 15:24 UTC, julsemaan commented
I've done the code adjustments, IDK what we do with the documentation

Perhaps @extrafu can shed some light on this

2018-06-01 18:19 UTC, jrouzierinverse requested changes
Update the Copyright date then I will merge

2018-06-01 18:19 UTC, jrouzierinverse commented on docs/PacketFence_Rapid7NexposeInsightVM_Quick_Install_Guide-docinfo.xml
> +  <year>2017</year>
2017?

2018-06-01 18:19 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/Pfdetect/nexpose.pm
> +Copyright (C) 2005-2017 Inverse inc.
2018

2018-09-06 20:02 UTC, julsemaan commented
Copyright updated + some other polishing code was added.

Please review again.

2018-09-10 06:12 UTC, nqb commented on docs/PacketFence_Rapid7NexposeInsightVM_Quick_Install_Guide.asciidoc
> +
```asciidoc
// to display images directly on GitHub
ifdef::env-github[]
:imagesdir: images
endif::[]
```

2018-09-11 21:24 UTC, julsemaan commented
Everything should be adjusted now

2018-09-12 16:06 UTC, jrouzierinverse requested changes

2018-09-12 16:06 UTC, jrouzierinverse commented on lib/pf/scan/rapid7.pm
> +sub buildApiUri {
document

2018-09-12 16:06 UTC, jrouzierinverse commented on lib/pf/scan/rapid7.pm
> +=head2 listSites
Wrong name

2018-09-12 16:06 UTC, jrouzierinverse commented on lib/pf/scan/rapid7.pm
> +sub doRequest {
document

2018-09-12 16:06 UTC, jrouzierinverse commented on lib/pf/scan/rapid7.pm
> +sub buildUA {
document

2018-09-12 16:06 UTC, jrouzierinverse commented on lib/pf/scan/rapid7.pm
> +sub wrapRequest {
document

2018-09-12 16:06 UTC, jrouzierinverse commented on lib/pf/scan/rapid7.pm
> +    }
it would be simpler to use ```List::MoreUtils::last_value```
```perl
  use List::MoreUtils qw(last_value);
  my $entry = last_value {$_->{type} eq 'SCAN' } @$history;
  my $scan_id = defined $entry ? $entry->{scanId} // undef;
```

2018-09-12 16:06 UTC, jrouzierinverse commented on lib/pf/scan/rapid7.pm
> +    return [@sorted[0..$amount]];
If the amount is less than sorted count it will always return +1 item

2018-09-14 18:03 UTC, julsemaan commented
addressed @jrouzierinverse's comments

Should be ready to merge

2018-09-26 19:49 UTC, extrafu commented
@julsemaan Take a decision regarding documentation and let's merge this.

2018-09-27 15:50 UTC, julsemaan commented
I added the doc for Rapid7 scans, integrated the nexpose syslog doc in the install guide and polished it.

Docs should be good now, so if @extrafu confirms the doc is fine and @jrouzierinverse confirms the code is good (should be), then we're good to merge

2018-10-01 18:44 UTC, merged