Feature/fingerbank manufacturer info
inverse-inc/packetfence pull request #3253
Opened 2018-05-25 15:14 UTC by julsemaan

# Description
Display the hardware manufacturer info in the Fingerbank tab

# Impacts
Fingerbank integration

# NEW Package(s) required
fingerbank-4.0.1
fingerbank-collector-1.0.1

# Issue
fixes #3211 

# Delete branch after merge
YES

# NEWS file entries
## Enhancements
* Support displaying the device manufacturer in the Fingerbank node tab

2018-05-25 15:19 UTC, extrafu commented
Looks good to me. @jrouzierinverse please check the DAL part and merge if all fine.

2018-05-25 15:19 UTC, cgx commented
I know we haven't been consistent in the past, but we should capitalize the first letter of each word in labels. So let's use *Device Manufacturer* everywhere.

2018-05-25 15:52 UTC, julsemaan commented
Both new packages for RHEL are in the devel repo

2018-05-25 15:55 UTC, julsemaan commented
@cgx 

Casing fixed

2018-05-25 18:11 UTC, jrouzierinverse requested changes

2018-05-25 18:11 UTC, jrouzierinverse commented on db/upgrade-X.X.X-X.Y.Z.sql
> +
Merge this with the previous ALTER TABLE of node.

2018-06-01 16:51 UTC, julsemaan commented
Adjusted based on comments, ready for another review/merge

2018-06-01 18:12 UTC, merged