Feature/pfappserver nodes update
inverse-inc/packetfence pull request #3267
Opened 2018-05-31 19:37 UTC by satkunas

# Description
Continue work on the pfappserver nodes

# Impacts
Increased coffee intake

# Delete branch after merge
YES

2018-06-01 16:05 UTC, cgx requested changes

2018-06-01 16:05 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfSearch.vue
> +    <div class="input-group">
Please fix the indentation of this `<div>` block.

2018-06-01 16:05 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfSearchBoolean.vue
> +<style lang="scss" scoped>
`rc-b, rc-br, rc-l, rc-tl, rc-tr` don't seem to be used.

2018-06-01 16:05 UTC, cgx commented on html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesSearch.vue
> +        // items[index]._rowVariant = checkedRows.includes(item) ? 'info' : ''
Remove this line.

2018-06-04 17:38 UTC, cgx commented on html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesSearch.vue
> +        // })
Can those commented lines be removed?

2018-06-04 17:40 UTC, cgx commented on html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesSearch.vue
> +      if (this.$route.query.query) {
I guess this should be exposed as a prop and access through `this.query`.

2018-06-04 18:05 UTC, cgx approved these changes

2018-06-04 18:05 UTC, merged

2018-06-04 19:02 UTC, satkunas commented
Attempting to re-open w/ new branch