Radius Proxy integration
inverse-inc/packetfence pull request #3278
Opened 2018-06-06 17:15 UTC by fdurand

# Description
Configure in PacketFence RADIUS Proxy based on the realm of the user. (Authentication and Accounting)

# Impacts
RADIUS workflow

# Delete branch after merge
YES

# NEWS file entries
## New Features
* RADIUS Proxy integration from admin gui

2018-11-13 19:24 UTC, fdurand commented
Ready for review

2018-11-15 14:50 UTC, nqb commented on debian/control
> + freeradius (>= 3.0.18), freeradius-ldap,
I didn't see Debian packages for freeradius 3.0.18

2018-11-15 14:52 UTC, nqb commented on html/pfappserver/lib/pfappserver/Form/Config/Source/DUMMY.pm
> +Form definition to create or update an DUMMY authentication source.
an DUMMY -> a DUMMY

2018-11-23 15:37 UTC, MuriloCalegari commented
Hi @fdurand,

We're super excited to have a proper eduroam wifi integrated with Packetfence here at our school. Do you have a date for when this RADIUS proxy will be available?

2018-11-23 15:46 UTC, fdurand commented
Hi MuriloCalegari,
the code works, i just need to do some small change.
It will be part of the 8.3 release (near the new the year).

2018-12-19 19:30 UTC, extrafu commented
@jrouzierinverse What's the status on this?

2018-12-20 15:18 UTC, jrouzierinverse commented
rebase

2018-12-20 15:38 UTC, fdurand commented
Done

2018-12-20 19:32 UTC, jrouzierinverse commented
rebase again

2018-12-20 19:40 UTC, fdurand commented
done

2018-12-21 18:05 UTC, jrouzierinverse commented
Looks good

2018-12-21 18:07 UTC, fdurand commented
Can you merge it ?

2018-12-21 18:14 UTC, jrouzierinverse requested changes
Create an upgrade script to move old configuration to the new location

2018-12-21 18:14 UTC, jrouzierinverse commented on conf/pf.conf.defaults
> +# advanced.filter_in_authorize
Change the name
advanced.* -> radius_configuration.*

2018-12-21 18:14 UTC, jrouzierinverse commented on conf/pf.conf.defaults
> +# advanced.filter_in_post_proxy
advanced.* -> radius_configuration.*

2018-12-21 18:14 UTC, jrouzierinverse commented on conf/pf.conf.defaults
> +# advanced.filter_in_pre_proxy
advanced.* -> radius_configuration.*

2018-12-21 19:06 UTC, fdurand commented
Change done

2018-12-21 19:12 UTC, julsemaan commented
Just a note so you guys don't forget the upgrade notes for the script @jrouzierinverse created

2018-12-21 19:31 UTC, merged