Feature/cambium ap modules
inverse-inc/packetfence pull request #3282
Opened 2018-06-08 20:17 UTC by atran-inverse

# Description
New Cambium AP module for 802.1x, MAC Auth and Web auth.
Added documentation

# Impacts
Allows PF to use Cambium AP

# Delete branch after merge
YES

2018-06-08 20:28 UTC, cgx commented on docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
> +image::docs/images/cambium-dot1x-basic.png[scaledwidth="100%",alt="Cambium WLAN Basic"]
The image is missing.

2018-06-13 02:48 UTC, fdurand requested changes

2018-06-13 02:48 UTC, fdurand commented on lib/pf/Switch/Cambium.pm
> +Implements a Cambium AP which supports 802.1x in wireless
mac-auth and webauth

2018-06-13 02:48 UTC, fdurand commented on lib/pf/Switch/Cambium.pm
> +
sub inlineCapabilities { return ($MAC,$PORT); }

2018-06-13 02:48 UTC, fdurand commented on lib/pf/Switch/Cambium.pm
> +    $logger->info(Dumper(\%params));
remove

2018-06-13 02:48 UTC, fdurand commented on lib/pf/Switch/Cambium.pm
> +    my $logger = $self->logger;
remove

2018-06-13 02:48 UTC, fdurand commented on lib/pf/Switch/Cambium.pm
> +    use Data::Dumper;
remove

2018-06-13 02:48 UTC, fdurand commented on lib/pf/Switch/Cambium.pm
> +    $MAC
useless

2018-06-13 02:48 UTC, fdurand commented on lib/pf/Switch/Cambium.pm
> +    $SSID
useless

2018-06-13 02:48 UTC, fdurand commented on lib/pf/Switch/Cambium.pm
> +    $WIRELESS_MAC_AUTH
useless

2018-06-13 02:48 UTC, fdurand commented on lib/pf/Switch/Cambium.pm
> +use Try::Tiny;
useless

2018-06-13 02:48 UTC, fdurand commented on lib/pf/Switch/Cambium.pm
> +use POSIX;
useless

2018-06-13 02:48 UTC, fdurand commented on lib/pf/Switch/Cambium.pm
> +use pf::node;
useless

2018-06-13 02:52 UTC, extrafu commented on docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
> +802.1x
802.1x -> 802.1X everywhere

2018-06-13 02:52 UTC, extrafu commented on docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
> +In the *Radius Server* tab, enter the management IP address of PacketFence (VIP in case of a cluster) and the Radius secret for Authentication and Accounting servers.
Radius -> RADIUS

2018-06-13 02:53 UTC, extrafu commented on lib/pf/Switch/Cambium.pm
> +    $logger->debug("Generated the following html form : ".$html_form);
Remove?

2018-06-13 02:54 UTC, fdurand commented on lib/pf/Switch/Cambium.pm
> +    $logger->debug("Generated the following html form : ".$html_form);
IMO no, it can be usefull

2018-06-14 19:59 UTC, merged