Pfappserver Updates
inverse-inc/packetfence pull request #3289
Opened 2018-06-13 17:18 UTC by satkunas

# Description
Continue work on the pfappserver

# Impacts
Increased PR count :100: 

# Delete branch after merge
YES

2018-06-18 16:02 UTC, cgx requested changes

2018-06-18 16:02 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfSearch.vue
> +              <b-dropdown-item @click="showSaveSearchModal=true">
Why not using the [v-b-modal](https://bootstrap-vue.js.org/docs/components/modal/#using-v-b-modal-directive-recommended-) directive?

2018-06-18 16:02 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfSearch.vue
> +              <b-dropdown-item @click="showExportJsonModal=true">
Why not using the [v-b-modal](https://bootstrap-vue.js.org/docs/components/modal/#using-v-b-modal-directive-recommended-) directive?

2018-06-18 16:02 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfSearch.vue
> +              <b-dropdown-item @click="showImportJsonModal=true">
Why not using the [v-b-modal](https://bootstrap-vue.js.org/docs/components/modal/#using-v-b-modal-directive-recommended-) directive?

2018-06-18 16:02 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfSearch.vue
> +      document.execCommand('copy')
Make sure the command is available using `document.queryCommandSupported('copy')`.

2018-06-18 16:02 UTC, cgx commented on html/pfappserver/root/static.alt/src/views/Nodes/index.vue
> +  },
You can remove the `data` block.

2018-06-18 16:02 UTC, cgx commented on html/pfappserver/root/static.alt/src/views/Nodes/index.vue
> +      return '/nodes/search?query=' + JSON.stringify(search.query)
Use the `this.$router` instance instead.

2018-06-18 21:05 UTC, satkunas commented on html/pfappserver/root/static.alt/src/components/pfSearch.vue
> +              <b-dropdown-item @click="showExportJsonModal=true">
There needed to be more granular control on when/how to close the modals (alt methods), thus the simpler v-b-modal wasn't sufficient.

2018-06-19 13:37 UTC, cgx approved these changes

2018-06-19 13:37 UTC, merged