Feature/pfconfigpool locking timeout
inverse-inc/packetfence pull request #3374
Opened 2018-07-06 13:32 UTC by julsemaan

# Description
Reworks the pfconfig pool locking strategy to use channels instead of sync.Mutex

# Impacts
pfconfig in golang

# Issue
fixes #3360 

# Delete branch after merge
YES

# NEWS file entries
## Bug Fixes
* Reworked the Golang pfconfig locking to prevent deadlocks while refreshing the configuration

2018-07-06 13:33 UTC, julsemaan commented
This is a bit late for the party for 8.1 especially considering it touches the core of the golang services.

So I guess this can be reviewed and merged post 8.1 and put in the maintenance

2018-10-31 16:34 UTC, julsemaan commented
Like for 8.1, this seems to be late for the party, I think the best course of action would be to have this reviewed ASAP, then after 8.2 is released, merge this into devel and potentially put it in the maintenance after we validate it doesn't cause trouble in devel.

Or, since this is bugfixing, we rush this into devel but the risk seems to be fairly high although this locking strategy is working great in the fingerbank collector

2018-10-31 16:45 UTC, extrafu commented
👍

2018-10-31 17:56 UTC, jrouzierinverse requested changes
The public interface of timed rwlock does not match it's internal implementation.
Since returned id is not used for updating any internal state.
It would be better to simplify the return values to either just return a boolean or an error.

2018-10-31 17:56 UTC, jrouzierinverse commented on go/timedlock/rw_lock.go
> +var chanPool = &sync.Pool{
The channel pool is not used

2018-10-31 17:56 UTC, jrouzierinverse commented on go/timedlock/rw_lock.go
> +	doneChans    map[uint64]chan int
doneChans is not used

2018-10-31 17:56 UTC, jrouzierinverse commented on go/timedlock/rw_lock.go
> +	id := l.getNextId()
It looks like id is not used.
Return an error instead.

2018-10-31 17:56 UTC, jrouzierinverse commented on go/timedlock/rw_lock.go
> +}
Is id used?

2018-10-31 17:56 UTC, jrouzierinverse commented on go/timedlock/rw_lock.go
> +			timeoutTimer.Stop()
Won't this happen when you release the timer?

2018-10-31 17:56 UTC, jrouzierinverse commented on go/timedlock/rw_lock.go
> +func (l *RWLock) RUnlock(id uint64) {
It looks like id is not used.
Return an error instead.

2018-11-01 11:14 UTC, julsemaan commented
Performed the cleanup and the signature changes as verbally discussed

2018-11-01 20:18 UTC, jrouzierinverse commented on go/timedlock/rw_lock.go
> +			}
In this busy loop call time.Sleep() or runtime.Goscheld() after a few iterations do a avoid pegging the CPU to 100%

2018-11-02 12:02 UTC, julsemaan commented
Adjusted, ready for another review

2018-11-20 21:39 UTC, julsemaan commented
@jrouzierinverse 

Can you re-review this and merge if the changes are fine

2018-11-20 22:23 UTC, merged