Violation : improve doc
inverse-inc/packetfence pull request #3500
Opened 2018-08-23 19:41 UTC by nqb

# Description
Add detail on role returned for a "Change network access on violation"

# Impacts
- Violation.pm
- API specs

# Delete branch after merge
YES

2018-08-24 00:13 UTC, jrouzierinverse requested changes
No need to update openapi spec it will be done automatically by /usr/local/pf/docs/api/spec/generate-openapi-from-routes.pl.

2018-08-24 00:13 UTC, jrouzierinverse commented on docs/api/spec/components/schemas/configviolation.yaml
> +        access on violation</em> action).
No need to update openapi spec

2018-08-24 00:13 UTC, jrouzierinverse commented on docs/api/spec/openapi.yaml
> +            network access on violation</em> action).
No need to update openapi spec

2018-08-24 00:13 UTC, jrouzierinverse commented on docs/api/spec/openapi.json
> +                  "description" : "Destination Role where PacketFence should put the client when a violation of this type is open (only for <em>Change network access on violation</em> action).",
No need to update openapi spec

2018-08-24 13:21 UTC, julsemaan commented on docs/api/spec/components/schemas/configviolation.yaml
> +        access on violation</em> action).
To prevent this from happening, probably putting a comment at the top of the auto-generated spec files would be good. 

That way, people won't have a tendency to modify them

2018-08-24 13:22 UTC, julsemaan commented
Other than the changes in the auto-gen files @jrouzierinverse, this looks good to me

2018-08-24 13:22 UTC, julsemaan approved these changes

2018-08-31 16:49 UTC, nqb commented
Ready to merge ?

2018-09-26 19:19 UTC, merged