feature/test_source_from_api
inverse-inc/packetfence pull request #3589
Opened 2018-08-31 18:55 UTC by jrouzierinverse

Fixes #3555

Description
===========

Add endpoint POST config/source/:id/test

2018-09-14 13:44 UTC, julsemaan commented on lib/pf/UnifiedApi/Controller/Config/Sources.pm
> +sub test {
perldoc

2018-09-14 13:47 UTC, julsemaan commented on lib/pf/UnifiedApi/Controller/Config/Sources.pm
> +            return $self->render_error(HTTP_BAD_REQUEST, $message);
Not sure 400 is the right code for a failure to test an auth source

Perhaps 422 would be better

2018-09-14 13:47 UTC, julsemaan commented on lib/pf/UnifiedApi/Controller/Config/Sources.pm
> +        return $self->render_error(HTTP_BAD_REQUEST, "$@");
Same comment about return code

Also, some places you use constants, some the number, I don't care if its any of them but I believe it should be consistent

2018-09-14 16:48 UTC, jrouzierinverse commented
Ready for review

2018-09-14 20:17 UTC, julsemaan commented
Does the spec need to be manually adjusted for this or will it be automagically adjusted ?

2018-09-14 20:17 UTC, julsemaan commented
Also this needs a rebase

2018-09-14 20:29 UTC, jrouzierinverse commented
I am confused which spec and why?

2018-09-17 14:15 UTC, julsemaan commented
openapi spec sorry

2018-10-02 17:54 UTC, julsemaan commented
Still missing the doc in the openapi spec

2018-10-05 14:49 UTC, julsemaan commented
@jrouzierinverse 

Do you want to write the spec so we can merge this or should this be postponed to 8.3 ?

2018-10-11 14:38 UTC, extrafu commented
Bump - what's the status on this one?

2018-10-14 22:46 UTC, jrouzierinverse commented
Add API Spec for sources/test

2018-10-14 22:46 UTC, jrouzierinverse commented
Done

2018-10-17 18:51 UTC, extrafu commented
Bump.

2018-10-18 11:46 UTC, julsemaan requested changes

2018-10-18 11:46 UTC, julsemaan commented on html/pfappserver/lib/pfappserver/Form/Config/Source/Htpasswd.pm
> +    unless (defined $path && -r $path) {
We should use the same styling as everywhere else when there are 2 conditions
```suggestion
    unless (defined($path) && -r $path) {
```

2018-10-18 14:01 UTC, jrouzierinverse commented
Done

2018-10-18 19:13 UTC, extrafu commented
@julsemaan Ready for merging?

2018-10-22 17:57 UTC, extrafu commented
@julsemaan ping!

2018-10-23 18:37 UTC, merged