Pfappserver Updates
inverse-inc/packetfence pull request #3639
Opened 2018-09-24 20:44 UTC by satkunas

# Description
Continue work on the pfappserver

# Impacts
Increased PR count :100: 

# Issue
* Fixes #3618 

# Delete branch after merge
YES

2018-10-10 20:09 UTC, cgx requested changes

2018-10-10 20:09 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfFormChosen.vue
> +    :state="isValid()" :invalid-feedback="getInvalidFeedback()" :class="['chosen-element', { 'mb-0': !columnLabel }, { 'is-focus': focus}]">
`class` and `v-bind:class` can co-exist, so I propose:

```html
  <b-form-group .. class="chosen-element" :class="{'mb-0': !columnLabel, 'is-focus': focus }">
```

2018-10-10 20:09 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfFormChosen.vue
> +  name: 'pf-form-input',
*pf-form-chosen*

2018-10-10 20:09 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfFormChosen.vue
> +    <b-input-group class="input-group-chosen">
Where is this class defined?

2018-10-10 20:09 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfFormDatetime.vue
> +    :state="isValid()" :invalid-feedback="getInvalidFeedback()" :class="['datetime-element', { 'mb-0': !columnLabel }, { 'is-focus': focus}]">
Again, I propose:

```html
<b-form-group .. class="datetime-element" :class="{ 'mb-0': !columnLabel, 'is-focus': focus }">
```

2018-10-10 20:09 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfFormInput.vue
> +    :state="isValid()" :invalid-feedback="getInvalidFeedback()" :class="['input-element', { 'mb-0': !columnLabel }]">
```html
<b-form-group .. class="input-element" :class="{ 'mb-0': !columnLabel }">
```

2018-10-10 20:09 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfFormPrefixMultiplier.vue
> +    :state="isValid()" :invalid-feedback="getInvalidFeedback()" :class="['prefixmultiplier-element', { 'mb-0': !columnLabel }, { 'is-focus': focus}]">
```html
<b-form-group .. class="prefixmultiplier-element" :class="{ 'mb-0': !columnLabel, 'is-focus': focus }">
```

2018-10-10 20:09 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfFormPrefixMultiplier.vue
>  <style lang="scss" scoped>
Does it really need to be scoped?

2018-10-10 20:09 UTC, cgx commented on html/pfappserver/root/static.alt/src/globals/pfValidators.js
> +          return (parent[param].$model.type === fieldType) ? true : fieldType
We should return immediately when the condition is true.

2018-10-10 20:09 UTC, cgx commented on html/pfappserver/root/static.alt/src/globals/pfValidators.js
> +          return (parent[param].$model.type === fieldType) ? true : fieldType
We should return immediately when the condition is true.

2018-10-10 20:09 UTC, cgx commented on html/pfappserver/root/static.alt/src/views/Users/_components/UsersCreate.vue
> +            :column-label="$t('Actions')"
The label will be localized by the component.

2018-10-10 20:09 UTC, cgx commented on html/pfappserver/root/static.alt/src/views/Users/_components/UsersCreate.vue
> +          -->
Remove comments.

2018-10-10 20:09 UTC, cgx commented on html/pfappserver/root/static.alt/src/views/Users/_components/UsersCreate.vue
>      'pf-form-toggle': pfFormToggle
When the component's name is properly defined, you can omit the keys:

```javascript
components: {
    pfFormDatetime,
    pfFormInput,
    pfFormSortableFields,
    pfFormTextarea,
    pfFormToggle
}
```

2018-10-10 20:09 UTC, cgx commented on html/pfappserver/root/static.alt/src/utils/bytes.js
> +    if (bytes === 0) return bytes.toString()
We need to append a space at the end.

2018-10-10 20:09 UTC, cgx commented on html/pfappserver/root/static.alt/src/globals/pfValidators.js
> +      for (let i = 0; i < params.length; i++) {
We could add a condition to return sooner if the count is bigger than the limit.

2018-10-10 20:09 UTC, cgx commented on html/pfappserver/root/static.alt/src/views/Users/_components/UsersCreate.vue
> +      actions: JSON.parse('[ { "type": "set_bandwidth_balance", "value": 64 }, { "type": "set_access_duration", "value": "" }, { "type": "set_access_level", "value": "User Manager" }, { "type": "mark
Values for testing?

2018-10-10 20:28 UTC, satkunas commented on html/pfappserver/root/static.alt/src/views/Users/_components/UsersCreate.vue
> +      actions: JSON.parse('[ { "type": "set_bandwidth_balance", "value": 64 }, { "type": "set_access_duration", "value": "" }, { "type": "set_access_level", "value": "User Manager" }, { "type": "mark
Yes, exact

2018-10-11 11:30 UTC, satkunas commented on html/pfappserver/root/static.alt/src/utils/bytes.js
> +    if (bytes === 0) return bytes.toString()
Nice catch, good :eye:

2018-10-11 12:48 UTC, satkunas commented on html/pfappserver/root/static.alt/src/components/pfFormPrefixMultiplier.vue
>  <style lang="scss" scoped>
Yes, normally the inputValue/value is used directly in the form input element. In this component the component uses a different model which differs from what's displayed in the form input (depending on the selected `prefix`.

2018-10-11 17:57 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfFormChosen.vue
> +    class="chosen-element" :class="[{ 'mb-0': !columnLabel }, { 'is-focus': focus}]">
You can simplify to a single object literal: `:class="{ 'mb-0': !columnLabel, 'is-focus': focus}"`

2018-10-11 17:58 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfFormDatetime.vue
> +    class="datetime-element" :class="[{ 'mb-0': !columnLabel }, { 'is-focus': focus}]">
You can simplify to a single object literal: `:class="{ 'mb-0': !columnLabel, 'is-focus': focus }"`

2018-10-11 17:58 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfFormPrefixMultiplier.vue
> +    class="prefixmultiplier-element" :class="[{ 'mb-0': !columnLabel }, { 'is-focus': focus}]">
You can simplify to a single object literal: `:class="{ 'mb-0': !columnLabel, 'is-focus': focus }"`

2018-10-11 17:59 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfFormSortableFields.vue
> +    class="sortablefields-element" :class="[{ 'is-focus': drag }, { 'mb-0': !columnLabel }]"
You can simplify to a single object literal: `:class="{ 'is-focus': drag, 'mb-0': !columnLabel }"`

2018-10-11 18:15 UTC, cgx approved these changes

2018-10-11 18:18 UTC, merged