Added callingstationssid and nasidentifierin radius_acct sql table
inverse-inc/packetfence pull request #3648
Opened 2018-09-27 16:43 UTC by fdurand

# Description
Added callingstationssid and nasidentifier in the radacct sql table

# Impacts
RADIUS accounting workflow

# Delete branch after merge
YES

# NEWS file entries

## Enhancements
* Added SSID and NAS identifier in the radacct table (accounting)

2018-12-18 15:54 UTC, satkunas requested changes

2018-12-18 15:54 UTC, satkunas commented on db/pf-schema-X.Y.Z.sql
>      IN p_tenant_id int
int(11) unsigned

2018-12-18 15:54 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +    IN p_tenant_id int
int(11) unsigned

2018-12-18 15:54 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +DECLARE Previous_Session_Time int(12);
unsigned?

2018-12-18 15:54 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  IN p_acctsessiontime int(12),
unsigned?

2018-12-18 15:54 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  IN p_acctinputoctets bigint(20),
unsigned?

2018-12-18 15:54 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  IN p_acctoutputoctets bigint(20),
unsigned?

2018-12-18 15:54 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  IN p_tenant_id int
int(11) unsigned

2018-12-18 15:54 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  DECLARE Previous_Session_Time int(12);
unsigned?

2018-12-18 15:54 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  DECLARE Previous_Output_Octets bigint(20);
unsigned?

2018-12-18 15:54 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  DECLARE Previous_Input_Octets bigint(20);
unsigned?

2018-12-18 15:54 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  IN p_acctsessiontime int(12),
unsigned?

2018-12-18 15:54 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  IN p_acctinputoctets bigint(20),
unsigned?

2018-12-18 15:54 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  IN p_acctoutputoctets bigint(20),
unsigned?

2018-12-18 15:54 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  IN p_tenant_id int
int(11) unsigned

2018-12-18 15:54 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  DECLARE Previous_Session_Time int(12);
unsigned?

2018-12-18 15:54 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  DECLARE Opened_Sessions int(12);
unsigned?

2018-12-18 15:54 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  DECLARE cnt int(12);
unsigned?

2018-12-18 15:54 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  DECLARE countmac int(12);
unsigend?

2018-12-19 16:04 UTC, fdurand commented
Done

2018-12-20 14:32 UTC, satkunas approved these changes

2018-12-20 14:38 UTC, merged