Feature/cluster zones
inverse-inc/packetfence pull request #3656
Opened 2018-10-02 21:25 UTC by julsemaan

# Description
Adds the ability to have clusters that are spread across multiple L3 networks.

# NEW Package(s) required
fingerbank-collector-1.1.0

# Impacts
Pretty much all PF as I had to rework stuff in pfconfig

# Delete branch after merge
YES

# NEWS file entries
(REQUIRED, but may be optional...)
## New Features
* Added support for clusters that have servers in different layer 3 networks

2018-10-03 12:33 UTC, extrafu commented
I suggest also:

1- some documentation that explains this feature
2- a procedure to take a server from a L2 cluster and moving it into a separate cluster zone

2018-10-03 12:34 UTC, nqb commented
Agree with @extrafu

2018-10-03 12:40 UTC, julsemaan commented
Documentation will be for 9.0 :)

Jokes aside, yes I'll attack the documentation when I get back from vacation after the rush of 8.2 is over

2018-10-03 15:57 UTC, extrafu commented
@jrouzierinverse Make sure your review this ASAP to make some iterations before next week.

2018-10-03 17:26 UTC, jrouzierinverse requested changes

2018-10-03 17:26 UTC, jrouzierinverse commented on lib/pf/cluster.pm
> +use Carp; carp "here";
The ``` carp "here"; ``` is causes a lot of tests to fail.

2018-10-03 17:26 UTC, jrouzierinverse commented on lib/pfconfig/namespaces/resource/clusters_hostname_map.pm
> +sub init {
pod doc

2018-10-03 17:26 UTC, jrouzierinverse commented on lib/pfconfig/namespaces/resource/clusters_hostname_map.pm
> +sub build {
pod doc

2018-10-03 17:26 UTC, jrouzierinverse commented on lib/pfconfig/namespaces/resource/all_cluster_hosts.pm
> +sub init {
pod doc

2018-10-03 17:26 UTC, jrouzierinverse commented on lib/pfconfig/namespaces/resource/all_cluster_hosts.pm
> +sub build {
pod doc

2018-10-03 17:26 UTC, jrouzierinverse commented on lib/pfconfig/namespaces/resource/all_cluster_servers.pm
> +pfconfig::namespaces::resource::all_cluster_servers
Better description

2018-10-03 17:26 UTC, jrouzierinverse commented on lib/pfconfig/namespaces/resource/all_cluster_servers.pm
> +sub init {
pod doc

2018-10-03 17:26 UTC, jrouzierinverse commented on lib/pfconfig/namespaces/resource/all_cluster_servers.pm
> +sub build {
pod doc

2018-10-03 17:26 UTC, jrouzierinverse commented on lib/pfconfig/namespaces/resource/all_cluster_hosts.pm
> +pfconfig::namespaces::resource::all_cluster_hosts
Better description

2018-10-03 17:26 UTC, jrouzierinverse commented on lib/pfconfig/namespaces/resource/clusters_hostname_map.pm
> +pfconfig::namespaces::resource::clusters_hostname_map
better description

2018-10-03 17:26 UTC, jrouzierinverse commented on sbin/pf-mariadb
> +    return ($alive > (scalar(pf::cluster::db_enabled_hosts()) / 2));
I understand that these are the same underneath.
However It is confusing to see two different functions to get the same array.
Suggestion to make thing clearer
```perl
my @servers = pf::cluster::mysql_servers();
foreach my $server (@servers) {
        if(ping($server->{management_ip})) {
            $alive ++;
        }
}
return ($alive > (scalar(@servers) / 2));
````

2018-10-03 17:26 UTC, jrouzierinverse commented on lib/pf/cluster.pm
> +    return map { (-f node_disabled_file($_->{host})) ? () : $_ } @db_cluster_servers;
grep would be more appropriate.

```perl
     return grep { -f node_disabled_file($_->{host}) }  @db_cluster_servers;
```

2018-10-03 17:26 UTC, jrouzierinverse commented on lib/pf/cluster.pm
> +    return map { (-f node_disabled_file($_)) ? () : $_ } @db_cluster_hosts;
grep would be more appropriate.

2018-10-03 17:26 UTC, jrouzierinverse commented on lib/pf/cluster.pm
> +    return map { (-f node_disabled_file($_)) ? () : $_ } @config_cluster_hosts;
grep would be more appropriate.

2018-10-03 17:26 UTC, jrouzierinverse commented on lib/pf/cluster.pm
> +    return map { (-f node_disabled_file($_->{host})) ? () : $_ } @config_cluster_servers;
grep would be more appropriate.

2018-10-03 17:26 UTC, jrouzierinverse commented on lib/pf/cluster.pm
> +    if(scalar(db_enabled_hosts()) >= 1){
just return

```perl
  return reverse db_enabled_hosts();
```
Simplifies the logic and has the same results.

2018-10-04 15:18 UTC, jrouzierinverse commented on sbin/pf-mariadb
> +    return ($alive > (scalar(pf::cluster::db_enabled_hosts()) / 2));
Missed this?

2018-10-04 18:41 UTC, jrouzierinverse commented
Is there still more work to be done?

2018-10-04 18:56 UTC, julsemaan commented
Some adjustments based on my tests and I still need to complete the adjustments you put comments

2018-10-05 14:20 UTC, julsemaan commented
Its ready for another review

2018-10-15 16:41 UTC, jrouzierinverse commented
Were the dependencies updated for fingerbank-collector

2018-10-15 16:50 UTC, jrouzierinverse commented on lib/pf/api.pm
> +    my $master_server = firstval { $_->{host} eq $postdata{server} } pf::cluster::config_enabled_servers;
Minor stuff make this a function.

2018-10-15 16:50 UTC, jrouzierinverse commented on lib/pf/api.pm
> +    my $master_server = firstval { $_->{host} eq $postdata{server} } pf::cluster::config_enabled_servers;
Then I will run a smoke test then merge.

2018-10-15 18:24 UTC, merged