fix/openapi-doc
inverse-inc/packetfence pull request #3663
Opened 2018-10-09 19:26 UTC by jrouzierinverse

Description
===========
Fixes the OpenAPI documentation and generation

Impacts
=======
The OpenAPI documentation

2018-10-10 17:17 UTC, cgx commented on docs/api/spec/components/schemas/configsource.yaml
> +          to fill the pin code.
Use uppercase letters for *sms* and *pin*.

2018-10-10 17:20 UTC, cgx commented on docs/api/spec/components/schemas/configsource.yaml
>          description: The length of the PIN code to be sent over sms
`s/sms/SMS/`

2018-10-10 18:04 UTC, cgx requested changes
ApiUser and ApiUsersList should be deleted.

2018-10-11 18:23 UTC, cgx commented
Ready to merge?

2018-10-29 18:16 UTC, jrouzierinverse commented
Rebased and ready to merge.

2018-10-30 18:53 UTC, cgx approved these changes

2018-10-30 18:55 UTC, merged