adjust locationlog to have its own voip column
inverse-inc/packetfence pull request #3679
Opened 2018-10-15 15:51 UTC by julsemaan

# Description
Prevent joining the locationlog to the node table to obtain the voip info

# Impacts
locationlog view/create

# Issue
fixes #3677 

# Delete branch after merge
YES

# NEWS file entries
## Bug Fixes
* Prevent costly join with node table when searching latest locationlog entries for a node (#3677)

2018-10-15 15:52 UTC, julsemaan commented
@satkunas, @jrouzierinverse, @fdurand 

Could you guys take a look at this solution and let me know if there will be objection to the integration of this fix before I have it applied at my customer deployment.

2018-10-15 16:57 UTC, jrouzierinverse commented
Calls to locationlog_insert_start do not include voip.

2018-10-15 17:00 UTC, julsemaan commented
I'm not actually fully done, haven't even tested if it compiles yet :P

Just wanted to know if anybody objects to the general idea before putting more energy into it

2018-10-15 17:01 UTC, jrouzierinverse commented
Why not just add the tenant_id in the join criteria for node and location in maintenance since that would fix the issue with out any database changes.
Now that fix can be a +1.

2018-10-15 17:14 UTC, julsemaan commented
that would be perfect for fixing the performance issue in an immediate manner and we'll backlog the other improvement (having the latest voip state) for 8.3 and not rush it

2019-03-21 14:53 UTC, extrafu commented
Please rebase and let's get this in v9 as it's easier to get schema changes in big fat releases.

2019-03-21 15:06 UTC, julsemaan commented
PF v9 codename: My big fat greek release

2019-03-21 15:10 UTC, extrafu commented
Rebase the gyros @jrouzierinverse

2019-03-22 15:35 UTC, julsemaan commented
Just rebased it and added some of them garlic potatos with that

2019-03-22 15:48 UTC, extrafu commented
@jrouzierinverse Please review and merge ASAP.

2019-03-22 17:24 UTC, jrouzierinverse commented on db/upgrade-X.X.X-X.Y.Z.sql
> +    ADD `potd` enum('no','yes') NOT NULL DEFAULT 'no';
I am not sure since belongs here.

No change to the pf-schema-X.Y.Z.sql

2019-03-22 17:28 UTC, jrouzierinverse commented
t/serialized_unittests/db/apply_upgrade.t failed.

2019-03-25 15:22 UTC, julsemaan commented
apply upgrade now works fine

2019-03-25 15:52 UTC, jrouzierinverse requested changes
VOIP status is never passed into the locationlog_insert_start function.

https://github.com/inverse-inc/packetfence/blob/2536d0df5057fd4b4fe061ccd77a761d217440c4/lib/pf/locationlog.pm#L387
https://github.com/inverse-inc/packetfence/blob/2536d0df5057fd4b4fe061ccd77a761d217440c4/lib/pf/locationlog.pm#L433

2019-03-26 13:11 UTC, julsemaan commented
> VOIP status is never passed into the locationlog_insert_start function.
> 
> [packetfence/lib/pf/locationlog.pm](https://github.com/inverse-inc/packetfence/blob/2536d0df5057fd4b4fe061ccd77a761d217440c4/lib/pf/locationlog.pm#L387)
> 
> Line 387 in [2536d0d](/inverse-inc/packetfence/commit/2536d0df5057fd4b4fe061ccd77a761d217440c4)
> 
>  locationlog_insert_start($switch, $switch_ip, $switch_mac, $ifIndex, $vlan, $mac, $connection_type, $connection_sub_type, $user_name, $ssid, $stripped_user_name, $realm, $role, $locationlog_mac, $ifDesc); 
> 
> [packetfence/lib/pf/locationlog.pm](https://github.com/inverse-inc/packetfence/blob/2536d0df5057fd4b4fe061ccd77a761d217440c4/lib/pf/locationlog.pm#L433)
> 
> Line 433 in [2536d0d](/inverse-inc/packetfence/commit/2536d0df5057fd4b4fe061ccd77a761d217440c4)
> 
>  locationlog_insert_start($switch, $switch_ip, $switch_mac, $ifIndex, $vlan, $mac, $connection_type, $connection_sub_type, $user_name, $ssid, $stripped_user_name, $realm, $role, undef, $ifDesc)

Good catch, just fixed it

2019-03-26 14:42 UTC, jrouzierinverse approved these changes

2019-03-26 14:57 UTC, merged