Pfappserver updates
inverse-inc/packetfence pull request #3700
Opened 2018-10-23 20:47 UTC by satkunas

# Description
Continue work on the pfappserver

# Impacts
Increased PR count :100: 

# Delete branch after merge
YES

2018-11-02 18:49 UTC, cgx requested changes

2018-11-02 18:49 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfConfigList.vue
> +      :fields="fields" :store="$store" :advanced-mode="false" :condition="condition"
Maybe a good time to remove the `store` property from pfSearch/pfSearchBoolean as it doesn't seem to be used? ✂️

2018-11-02 18:49 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfConfigList.vue
> +            <b-button variant="outline-primary" :to="{}">{{ $t('Add') }}</b-button>
I understand that this act as the default content, but I would remove it since it's not functional.

2018-11-02 18:49 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfConfigView.vue
> +          <pf-button-delete v-if="!isNew" class="ml-1" :disabled="isLoading" :confirm="$t('Delete Config?')" @on-delete="remove()"/>
We should conditionally render those buttons based on the active user's ACLs (`v-can`, `this.$can`).

2018-11-02 18:49 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfConfigView.vue
> +      console.log('isNew', this.form.fields, this.form.fields.filter(field => field.key === 'id').length === 0)
Remove debugging output.

2018-11-02 18:49 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfConfigView.vue
> +      }, 100)
It could even be more ..

2018-11-02 18:49 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfMixinEscapeKey.js
> +      this.$router.push({ name: 'roles' })
As the default behaviour, it should throw an exception when in *debug mode* (`process.env.VUE_APP_DEBUG`).

2018-11-02 18:49 UTC, cgx commented on html/pfappserver/root/static.alt/src/views/Configuration/_components/RoleView.vue
> +              [this.$i18n.t('Maximum 3 characters.')]: maxLength(3)
Really?

2018-11-02 18:49 UTC, cgx commented on html/pfappserver/root/static.alt/src/views/Configuration/_components/RoleView.vue
> +              [this.$i18n.t('Alphanumeric value required')]: alphaNum
Validation sentences should end with a period.

2018-11-02 18:49 UTC, cgx commented on html/pfappserver/root/static.alt/src/views/Configuration/_components/RoleView.vue
> +              [this.$i18n.t('Integer value required')]: integer
Validation sentences should end with a period.

2018-11-02 19:29 UTC, satkunas commented on html/pfappserver/root/static.alt/src/components/pfConfigList.vue
> +            <b-button variant="outline-primary" :to="{}">{{ $t('Add') }}</b-button>
Would it help us to put a warning placeholder here to remind us to use the slot? Or simply omit it?

2018-11-07 21:49 UTC, satkunas commented on html/pfappserver/root/static.alt/src/components/pfConfigList.vue
> +      :fields="fields" :store="$store" :advanced-mode="false" :condition="condition"
Removed in https://github.com/inverse-inc/packetfence/pull/3700/commits/4fee5785db6903a14ef8421f644d1b58e756cecd

2018-11-08 02:53 UTC, cgx approved these changes

2018-11-08 02:53 UTC, merged