Feature/ssl inspection module
inverse-inc/packetfence pull request #3705
Opened 2018-10-24 19:25 UTC by atran-inverse

# Description
New portal module for SSL Inspection. 
Direct users automatically on captive portal to correct page with instructions on installing certificate.

# Impacts
New portal module. Could be used in a chain.

# Delete branch after merge
YES

# NEWS file entries
## New Features
* SSL Inspection Portal Module

2018-10-24 19:32 UTC, extrafu commented
@cgx Please review the UI side and @julsemaan the backend side.

2018-10-24 19:45 UTC, julsemaan commented
I always liked to review backends

2018-10-25 14:31 UTC, cgx requested changes

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/content/sslinspection.js
> +
Replace the content of this file by the JavaScript you defined in `html/captive-portal/templates/ssl_inspection/common.html`. Your `testFailed` function could be directly integrated in the failure callback since it is called only at this place.

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection.html
> +  <p>Please install the certificate.</p>
String must be localized.

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/android.html
> +                        <li class="o-list-inline__item u-padding-horizontal-tiny"><a href="/ssl_inspection/unsupported">Unsupported</a></li>
Replace `Unsupported` by `Other` and localize the string.

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/android.html
> +		</nav>
The `nav` block should be moved to its own file and inserted using an `INCLUDE` directive. Repeat for all files.

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/android.html
> +                        		[% i18n('<font color="red"><u>Note:</u></font> If you have a district owned Android device, <i>please</i> visit the Android Enrollment Portal <u><a href="http://ipad.wcr7.or
This seems specific to a client.

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/android.html
> +				[% i18n("First, click the <i>Download Certificate</i> button below; this will download the certificate file to a temporary location on your device.") | none %]
I would simplify this sentence to *Download the certificate to your device.* Repeat for all files.

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/android.html
> +        			<a href="[%ssl_path%]" class="c-btn c-btn--secondary c-btn--ghost u-1/1">[% i18n('Download Certificate') %]</a>
Pad the Template Toolkit variable with spaces (`[% ssl_path %]`).

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/android.html
> +				<img src="/common/ssl_inspection/android-01-certificate-name.png" alt="Android certificate name prompt" >
The *alt* string must be localized.

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/android.html
> +				[% i18n("You will be prompted to enter a name for the certificate. Enter whatever you like (<i>WebbCity</i> is recommended), and then tap <i>OK</i> or the Enter button on the keyboard.") | none %
I propose the following text:

> `You will be prompted to enter a name for the certificate. Enter a meaningful name for this network and click <i>OK</i>.`

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/android.html
> +				[% i18n("(Note: Android devices vary greatly, so you may not see exactly the same thing if you are using another device or a different version of Android; however, the general process and wording
Remove the surrounding parentheses.

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/android.html
> +			</p>
Wrap this note as a `o-media` *warning* object.

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/android.html
> +				<img src="/common/ssl_inspection/android-02-installed.png" alt="Android certificate installation confirmation" >
Localize the string of the *alt* attribute. Repeat for all files.

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/chrome.html
> +			[% i18n("(Note: These images show Chrome running on Chrome OS version 47; you may not see exactly the same thing if you are using Chrome for Linux; however, the general process and wording should
Remove the parenthesis and wrap the note around a warning `o-media` object.

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/ios.html
> +                        </div>
This block seems specific to a client.

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/firefox.html
> +                        	[% i18n("**Please Note**") %]
This note should be wrapped in a *warning* `o-media` object.

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/android.html
> +			<h3 class="number"><span>[% i18n("Step ") %]</span>1</h3>
Place the space outside the function call (`i18n("Step")`). Repeat everywhere.

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/ios.html
> +							[% i18n("(Note: These images show iOS 9 running on an iPad; if you have a different version of iOS, the layout and buttons may be different — but the words should be the same.) Also, you maybe
Remove the parenthesis and wrap the note around a warning `o-media` object.

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/opera.html
> +        		[% i18n('<font color="red"><u>Note:</u></font> This guide is for Opera version 12 and below. Newer versions of Opera will use your computer system\'s certificate or keychain manager instead
Wrap the note around a warning `o-media` object.

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/opera.html
> +			[% i18n("(Note: These images show Opera on Mac OS X. If your computer runs Windows or Linux, the buttons may look different - but the words should be the same.)") %]
Remove the parenthesis and wrap the note around a warning `o-media` object.

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/android.html
> +                        <li class="o-list-inline__item u-padding-horizontal-tiny"><a href="/ssl_inspection/osx">Mac OSX</a></li>
Mac OSX => *macOS*

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/osx.html
> +                       	    [% i18n("<strong>This guide will help you install the SSL filtering certificate for Mac-based browsers which use the operating system's built-in Keychain facility — this i
.. Mac-based browsers which use the operating system's built-in Keychain facility => .. *browsers which use macOS built-in Keychain facility*
Mac OSX => *macOS*

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/osx.html
> +                            [% i18n("(Note: You may not see exactly the same thing if you are using another browser or a different version of OS X; however, the general process and wording should be
Remove the parenthesis and wrap the note around a warning `o-media` object.

2018-10-25 14:31 UTC, cgx commented on html/captive-portal/templates/ssl_inspection/osx.html
> +                        <h3> ***Note*** </h3>
Wrap the note around a warning `o-media` object.

2018-12-17 18:28 UTC, extrafu commented
@cgx Can you please make the changes before Thursday so we merge?

2018-12-18 19:55 UTC, cgx approved these changes

2018-12-18 19:56 UTC, cgx commented
@julsemaan I'll let you merge once you approved the backend changes.

2018-12-18 20:16 UTC, julsemaan commented
I'll dry the controller code a little bit and we'll be good to merge

2018-12-19 12:59 UTC, julsemaan commented
The iOS instructions cannot work, they talk about a mobileconfig profile but the download link points to the same certificate file.

We'll need to have another link to a certificate enrollment profile for iOS and probably provide instructions and documentation on how to do that.

Or rework the backend to host the certificate on the server and then generate a mobileconfig file based on it

Nonetheless, this needs additional work to get iOS working fine according to the instructions

2018-12-19 19:27 UTC, merged