Run some pfstats task only on the Master of the cluster or on the standalone
inverse-inc/packetfence pull request #3716
Opened 2018-10-26 20:07 UTC by fdurand

# Description
Get rid of sql queries made by pfstats on a cluster

# Impacts
Stats

# Issue
fixes #3690

# Delete branch after merge
YES

# NEWS file entries

## Enhancements
* pfstats optimization

## Bug Fixes
* Run some sql queries from pfstats from only one server (#3690)

2018-10-29 11:26 UTC, julsemaan commented on go/stats/main.go
> +func detectVIP(management pfconfigdriver.ManagementNetwork) {
This seems duplicated with the one in pfdhcp, could we centralize this in a package so we don't duplicate code

2018-10-29 15:46 UTC, fdurand commented on go/stats/main.go
> +func detectVIP(management pfconfigdriver.ManagementNetwork) {
It's not exactly the same that we have in pfdhcp.
Btw i can move this function in sharedutils.

2018-10-29 15:57 UTC, satkunas requested changes

2018-10-29 15:57 UTC, satkunas commented on conf/stats.conf.example
> +management = false
Use the same `key=value` spacing used elsewhere.

2018-10-29 15:57 UTC, satkunas commented on go/stats/main.go
> +	for _, adresse := range adresses {
This `for` loop appears to iterate over all `adresses` even after `found=true`. Is a `return` statement needed right after `found=true`?

Would it be faster to define `VIP[management.Int] = false` at the beginning of this function, and only set `VIP[management.Int] = true` and `return` immediately if `IP.Equal(VIPIp[management.Int])` ?

2018-12-17 20:22 UTC, fdurand commented
BUMP

2018-12-18 16:22 UTC, julsemaan commented
@satkunas 

Can you check @fdurand's changes and remove your block if its all fine.

To me, we're all good to merge

2018-12-21 14:24 UTC, satkunas commented
@fdurand @julsemaan all good. Merge when ready.

2018-12-21 14:38 UTC, merged