Updated acct_stop procedure to avoid acct_stop packet if it's duplicate
inverse-inc/packetfence pull request #3753
Opened 2018-11-05 21:09 UTC by fdurand

# Description
Detect if PacketFence receive duplicates accounting stop and avoid insertion in the DB.

# Impacts
RADIUS authorize accounting

# Issue
Duplicate entries in the radacct_log table

# Delete branch after merge
YES

# NEWS file entries

## Enhancements
* Avoid duplicates accounting stop entries

2018-12-18 15:56 UTC, satkunas requested changes

2018-12-18 15:56 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  IN p_acctinputoctets bigint(20),
unsigned?

2018-12-18 15:56 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  IN p_acctoutputoctets bigint(20),
unsigned?

2018-12-18 15:56 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  IN p_tenant_id int
int(11) unsigned

2018-12-18 15:56 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  DECLARE Previous_Input_Octets bigint(20);
unsigned?

2018-12-18 15:56 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  DECLARE Previous_Output_Octets bigint(20);
unsigned?

2018-12-18 15:56 UTC, satkunas commented on db/upgrade-X.X.X-X.Y.Z.sql
> +  DECLARE Previous_Session_Time int(12);
unsigned?

2018-12-18 19:52 UTC, fdurand commented
Done

2018-12-19 13:42 UTC, satkunas approved these changes

2018-12-19 13:42 UTC, merged