feature/domain_filtering_for_email_sources
inverse-inc/packetfence pull request #3807
Opened 2018-11-21 17:45 UTC by jrouzierinverse

Description
===========
Allow to filter email domains that can be used for the email source

Impacts
=======
EmailSource and the portal email source workflow

NEWS file entries
=================

Enhancements
------------
* Email Source can have banned and allowed email domains

2018-11-21 20:56 UTC, extrafu commented on html/pfappserver/lib/pfappserver/Form/Config/Source/Email.pm
> +    label => 'Comma seperated list of Allowed Domains',
Comma-separated

2018-11-21 20:57 UTC, extrafu commented on html/pfappserver/lib/pfappserver/Form/Config/Source/Email.pm
> +    label => 'Comma seperated list of Banned Domains',
Comma-separated

2018-11-21 20:59 UTC, extrafu commented
@nqb Please test it.

2018-11-22 12:30 UTC, nqb commented on html/pfappserver/lib/pfappserver/Form/Config/Source/Email.pm
> +    label => 'Comma seperated list of Allowed Domains',
seperated -> separated

2018-11-22 12:30 UTC, nqb commented on html/pfappserver/lib/pfappserver/Form/Config/Source/Email.pm
> +    label => 'Comma seperated list of Banned Domains',
seperated -> separated

2018-11-22 12:57 UTC, nqb commented
@extrafu: I didn't see any calls to `isEmailAllowed` method except for unit tests, are you sure the PR is ready for tests ?

I try to add one domain to the allowed domains field on default email source, I got following error: https://gist.github.com/nqb/c6479592b3d48107cbae3887e7876a9a

Few remarks:
- Feature has been requested to be use on **sponsor** sources
- We should increase size box of the new fields:
![screenshot from 2018-11-22 13-32-07](https://user-images.githubusercontent.com/10830260/48904353-64c88700-ee5e-11e8-87e5-03955512ee5d.png)

2018-11-22 13:02 UTC, nqb commented
I updated description of the PR to add the new checklist. 

@jrouzierinverse: you should update the way you create PR based on https://github.com/inverse-inc/packetfence/blob/8e1d98af80a101a45a49528c6e465a85d55477da/.github/PULL_REQUEST_TEMPLATE.md#checklist

2018-11-22 13:19 UTC, nqb requested changes
Please add comments for `isEmailAllowed`, `domains_regexes` and `make_regex` methods.

2018-11-22 14:39 UTC, jrouzierinverse commented
Sorry did not push the commit

2018-11-22 14:57 UTC, jrouzierinverse commented
Done

2018-11-22 14:58 UTC, jrouzierinverse commented
Ready for testing.
Will update documentation

2018-11-22 16:52 UTC, nqb commented
If I put domains in fields, it works but when I get back to my source, domain fields looks like this: `ARRAY(0x558e032f40c0)`

2018-11-22 16:59 UTC, nqb commented on lib/pf/Authentication/Source/EmailSource.pm
> +        $logger->warn("Failed to authenticate using EmailSource ($self->{id}) with PID '$username'");
IMO, we should give a more precise reason in log, like you did before.
Is it possible to include content of "EMAIL_UNAUTHORIZED" ?

2018-11-22 17:27 UTC, jrouzierinverse commented on lib/pf/Authentication/Source/EmailSource.pm
> +        $logger->warn("Failed to authenticate using EmailSource ($self->{id}) with PID '$username'");
Of course we can use the include the contents of 'EMAIL_UNAUTHORIZED'
What more precise information to you need?
I included the source id and email address in the log what else do you think we need?

2018-11-23 07:04 UTC, nqb commented on lib/pf/Authentication/Source/EmailSource.pm
> +        $logger->warn("Failed to authenticate using EmailSource ($self->{id}) with PID '$username'");
Just to say that the authentication failed due to "banned" domain

2018-11-23 14:20 UTC, nqb commented
No more `ARRAY(0x...)` in fields.

2018-11-26 08:59 UTC, nqb requested changes

2018-11-26 08:59 UTC, nqb commented on html/pfappserver/lib/pfappserver/Form/Config/Source/Email.pm
> +    },
if banned domains are checked before allowed domains, I propose to reverse order of fields in the form.

2018-11-26 08:59 UTC, nqb commented on lib/pf/Authentication/Source/EmailSource.pm
> +}
Could you describe what check the if and what return the function ?

2018-11-26 08:59 UTC, nqb commented on lib/pf/constants/authentication/messages.pm
> +Readonly our $EMAIL_UNAUTHORIZED => "Cannot register with this email address.";
```suggestion
Readonly our $EMAIL_UNAUTHORIZED => "Cannot register with this email address: unallowed domain.";
```

2018-11-26 08:59 UTC, nqb commented on html/pfappserver/lib/pfappserver/Form/Config/Source/Email.pm
> +    },
If we support regex in domains fields, we should update "help" statements.

2018-11-26 15:22 UTC, jrouzierinverse commented
Done re-review

2018-12-03 12:01 UTC, nqb commented
Thanks a lot for your changes.

My new remarks:
- register using local domain in uppercase work, not for allowed/banned domains. We need to be consistent: it should not work in any cases.
- as said before, feature has been requested to be use on sponsor sources. We need to port it.

2018-12-03 12:09 UTC, nqb commented
I created acceptance tests.

2018-12-03 15:28 UTC, jrouzierinverse commented
Did the issue come up when the allowed/banned domains are uppercase in the config or during the authentication?

2018-12-04 06:48 UTC, nqb commented
I'm able to reproduce the issue with following config:
- allow local domain: checked
- banned domains: empty
- allowed domains: one uppercase domaine (FREE.fr)

My local domain is: centos-devel.example.lan, I'm able to register with nqb@CENTOS-devel.example.lan. No changes if I put my allowed domain in lowercase.

2018-12-10 09:20 UTC, nqb commented
> register using local domain in uppercase work, not for allowed/banned domains. We need to be consistent: it should not work in any cases.

Still presents.

I got a new issue. If I edit the default email and sponsor sources and update only the `Comma-separated list of Allowed Domains` field with one domain, I got this [error](https://gist.github.com/nqb/27a40353c8fe54b97aeb1ed837364dc3) in logs.

If I filled the `Comma-separated list of Banned Domains` field, error disappears.

2018-12-11 16:14 UTC, jrouzierinverse commented
Done

2018-12-13 07:28 UTC, nqb commented
@jrouzierinverse : is this code can be apply as is on a 8.1 installation ?

2018-12-13 07:53 UTC, nqb commented
Issue in webadmin fix, I don't see the fix for register using local domain in uppercase

2018-12-13 16:38 UTC, jrouzierinverse commented
Here is the fix dfcc31c08fc6f92486bf5aec1f8be2c4dd330d40 and test 2e1b457d491e1d8d6ac250e4adccbff2d050af19.

2018-12-17 12:08 UTC, nqb commented
Now, I'm able to register with domain in uppercase or lowercase.

2018-12-17 12:11 UTC, nqb approved these changes

2018-12-17 18:29 UTC, extrafu commented
@nqb If all is fine, please merge and update the NEWS file

2018-12-18 10:17 UTC, merged