Feature/radius test
inverse-inc/packetfence pull request #3930
Opened 2019-01-15 13:59 UTC by fdurand

# Description
Allow to set the username and password that pfstat will use to test the eduroam and radius source

# Impacts
pfstats

# Delete branch after merge
YES

# Checklist
- [n ] Document the feature
- [n ] Add unit tests
- [n ] Add acceptance tests (TestLink)

# NEWS file entries

## Enhancements
* Add a test user and password to test the Eduroam and RADIUS source

2019-01-15 14:23 UTC, julsemaan commented on html/pfappserver/lib/pfappserver/Form/Config/Source/Eduroam.pm
> +             help => 'If you monitor, what is the password to test the RADIUS source' },
The password to use for testing when monitoring the RADIUS source

2019-01-15 14:23 UTC, julsemaan commented on html/pfappserver/lib/pfappserver/Form/Config/Source/RADIUS.pm
> +             help => 'If you monitor, what is the password to test the RADIUS source' },
The password to use for testing when monitoring the RADIUS source

2019-01-15 14:23 UTC, julsemaan commented on html/pfappserver/lib/pfappserver/Form/Config/Source/RADIUS.pm
> +             help => 'If you monitor, what is the username to test the RADIUS source' },
The username to use for testing when monitoring the RADIUS source

2019-01-15 14:23 UTC, julsemaan commented on html/pfappserver/lib/pfappserver/Form/Config/Source/Eduroam.pm
> +             help => 'If you monitor, what is the username to test the RADIUS source' },
The username to use for testing when monitoring the RADIUS source

2019-01-15 14:23 UTC, julsemaan commented on go/stats/main.go
> +			if response.Code == radius.CodeAccessAccept {
Would be useful to record whether it was accepted or not for more in-depth troubleshooting if needed

2019-01-15 14:23 UTC, julsemaan commented on go/stats/main.go
> +			if response.Code == radius.CodeAccessAccept {
Same as my comment above

2019-07-16 15:23 UTC, fdurand commented
Needs to be reworked, instead of sending a Access Request we should only sent a Status Server.

2020-12-21 13:27 UTC, jrouzierinverse requested changes

2020-12-21 13:27 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/Source/Eduroam.pm
> +has_field 'testPassword',
Add testPassword to the fields_to_mask list in the sources.
https://github.com/inverse-inc/packetfence/blob/devel/lib/pf/UnifiedApi/Controller/Config/Sources.pm#L246

2020-12-22 00:29 UTC, fdurand commented
This PR is useless now, we use status-check to test the radius sources.

2020-12-22 00:29 UTC, closed without merging