Feature/api admin roles header
inverse-inc/packetfence pull request #3970
Opened 2019-01-30 16:07 UTC by julsemaan

# Description
Pass down admin roles and admin roles group through headers for consumption by API backends

# Impacts
API frontend

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [N/A] Document the feature
- [YES] Add unit tests
- [N/A] Add acceptance tests (TestLink)

2019-01-30 17:23 UTC, jrouzierinverse requested changes

2019-01-30 17:23 UTC, jrouzierinverse commented on go/api-frontend/aaa/authorization.go
> +	r.Header.Set("X-PacketFence-Admin-Roles", strings.Join(roles, ","))
The admin actions are not needed.
I just need the name of the Admin roles that are in conf/adminroles.conf

2019-01-30 17:23 UTC, jrouzierinverse commented on go/api-frontend/aaa/authentication_backend_test.go
> +	if !tokenInfo.AdminRoles()["SYSTEM_READ"] {
The name AdminRoles is confusing here since in perl there called actions not roles.

2019-01-30 17:24 UTC, julsemaan commented on go/api-frontend/aaa/authorization.go
> +	r.Header.Set("X-PacketFence-Admin-Roles", strings.Join(roles, ","))
I know but might as well add them for future utilization.

2019-01-30 17:38 UTC, jrouzierinverse commented on go/api-frontend/aaa/authorization.go
> +	r.Header.Set("X-PacketFence-Admin-Roles", strings.Join(roles, ","))
Then we will add it when we need them.
If someone has the Admin Role ALL that would send an extra 2286 bytes that is wasteful.
If we need them can always add them back.

```
perl -Ilib -Mpf::constants::admin_roles -e'print(length("X-PacketFence-Admin-Roles:" . join(",", @pf::constants::admin_roles::ADMIN_ACTIONS) . "\r\n" )  ,"\n")'
``

2019-01-30 17:51 UTC, julsemaan commented on go/api-frontend/aaa/authorization.go
> +	r.Header.Set("X-PacketFence-Admin-Roles", strings.Join(roles, ","))
Yeah you're right for the large amount of bytes, didn't think of that, I'll strip it

2019-01-30 18:34 UTC, julsemaan commented
Performed the adjustments

2019-01-30 20:32 UTC, jrouzierinverse commented
```
```

2019-01-30 20:32 UTC, jrouzierinverse commented
``

2019-01-30 20:33 UTC, jrouzierinverse commented
Cannot compile
```
[root@dev-c7 pf]# cd ~/gospace/src/github.com/inverse-inc/packetfence/go
[root@dev-c7 go]# make
make NAME="pfhttpd" _pfhttpd
make[1]: Entering directory `/usr/local/pf/go'
cd caddy/caddy/caddy && \
go build && \
cd - && \
mv caddy/caddy/caddy/caddy pfhttpd
# github.com/inverse-inc/packetfence/go/caddy/api-aaa
../../api-aaa/api-aaa.go:167:36: cannot call non-function info.AdminRoles (type map[string]bool)
make[1]: *** [_pfhttpd] Error 2
make[1]: Leaving directory `/usr/local/pf/go'
make: *** [pfhttpd-sha] Error 2
[root@dev-c7 go]# v ../../api-aaa/api-aaa.go +167
[root@dev-c7 go]# v api-frontend/
aaa/              unifiedapierrors/
[root@dev-c7 go]# v caddy/api-aaa/api-aaa
api-aaa.go       api-aaa_test.go
[root@dev-c7 go]# v caddy/api-aaa/api-aaa.go +167
[root@dev-c7 go]# ag GetTokenInfoFromBearerRequest -l
caddy/api-aaa/api-aaa.go
api-frontend/aaa/authorization.go
[root@dev-c7 go]# v api-frontend/aaa/authorization.go
```

2019-02-01 14:07 UTC, julsemaan commented
adjusted the code

2019-02-01 15:54 UTC, merged