added hot-reload of passthroughs in pfdns
inverse-inc/packetfence pull request #3991
Opened 2019-02-08 14:41 UTC by julsemaan

# Description
added hot-reload of passthroughs in pfdns

# Impacts
pfdns passthroughs

# Issue
fixes #3127 

# Delete branch after merge
YES

# Checklist
- [n/a] Document the feature
- [n/a] Add unit tests
- [n/a] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* Adding/removing passthroughs doesn't require to restart pfdns anymore (#3127)

2019-02-15 20:43 UTC, fdurand requested changes

2019-02-15 20:43 UTC, fdurand commented on go/coredns/plugin/pfdns/pfconfig.go
> +	spew.Dump(pfconfigdriver.Config.Passthroughs.Registration)
needs to be remove

2019-02-19 16:46 UTC, julsemaan commented
Adjusted code

2019-02-19 20:47 UTC, fdurand approved these changes

2019-02-19 20:47 UTC, merged