Proper Validation Checks
inverse-inc/packetfence pull request #4110
Opened 2019-03-24 13:38 UTC by simbazad

# Description
Validation checks on user input across most of the configuration section.

# Issue
fixes #4085

# Delete branch after merge
YES

2019-03-24 13:43 UTC, simbazad commented
There's still a lot of work to be done , especially for input coming from endpoints/etc.. , and the dangerous pf_run routine .

2019-06-20 13:01 UTC, julsemaan commented
This looks like a good PR which we seem to have completely forgotten about

Can you rebase this and we'll get this merged

Thanks!

2019-06-20 16:07 UTC, jrouzierinverse requested changes
Thank you for the pull request.
However there are some issues with the pull request.

2019-06-20 16:07 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/SecurityEvent.pm
> +   type => 'PosInteger',
This can be non numeric in some cases.

2019-06-20 16:07 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/Source/LDAP.pm
> +    type         => 'PosInteger',
We can have sub second timeouts please it change back to a float.

2019-06-20 16:07 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/Source/LDAP.pm
> +    type         => 'PosInteger',
We can have sub second timeouts please it change back to a float.

2019-06-20 16:07 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/Pf.pm
> +                    if ( (exists $doc_section->{minimum_length}) && (my $minimum_length = $doc_section->{minimum_length}) ) {
The min/max check will not be added in the case of other Text fields.

2019-06-20 16:07 UTC, jrouzierinverse commented on lib/Input/Validation.pm
> +our @EXPORT = qw(sanitize validate form_field_validation);
Since the validate function is exported by default.
This will override the validate function in the forms that use Input::Validation.
If that form does not implement it's own validate method.
Validation will be broken if it's parent class defines one.

2019-06-20 16:07 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/Source/LDAP.pm
> +    type         => 'PosInteger',
We can have sub second timeouts please it change back to a float.

2019-06-20 16:07 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/Pf.pm
> +    return ($field->add_error("The domain name cannot end with '.local' as this causes issues with Apple iOS devices")) if ($domain =~ /\.local$/);
We allow domains that have no dots in them.

2019-06-20 16:07 UTC, jrouzierinverse commented on conf/documentation.conf
> +type=path
The Path form field checks if a path exists on the file system.
Please convert this back to text.

2019-06-20 16:07 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/Domain.pm
> +use Input::Validation;
This exports the validate function from Input::Validation.

2019-06-20 16:07 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/Fingerbank/Settings.pm
> +use Input::Validation;
This exports the validate function from Input::Validation.

2019-06-20 16:07 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/Pf.pm
> +use Input::Validation;
This exports the validate function from Input::Validation.

2019-06-20 16:07 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/Scan/Nessus.pm
> +use Input::Validation;
This exports the validate function from Input::Validation.

2019-06-20 16:07 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/Scan/OpenVAS.pm
> +use Input::Validation;
This exports the validate function from Input::Validation.

2019-06-20 16:07 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/Scan/Rapid7.pm
> +use Input::Validation;
This exports the validate function from Input::Validation.

2019-06-20 16:07 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/Scan/WMI.pm
> +use Input::Validation;
This exports the validate function from Input::Validation.

2019-06-20 16:07 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/Source/HTTP.pm
> +use Input::Validation;
This exports the validate function from Input::Validation.

2019-11-01 14:08 UTC, extrafu commented
@jrouzierinverse Review again to see what's useful and please close after.

2019-11-04 16:23 UTC, extrafu commented
@jrouzierinverse Please take a decision right now about using parts and scrapping the rest, closing it or pushing it to later.

2019-11-05 11:04 UTC, jrouzierinverse commented
I am closing this because a lot of those these issue are already solved or have edge case not considered by the PR.

2019-11-05 11:04 UTC, closed without merging