Feature/domain queue join
inverse-inc/packetfence pull request #4155
Opened 2019-03-28 21:43 UTC by julsemaan

# NOT READY
Opening this in case someone needs to pickup on it

Missing:
* Example in Javascript 
 * Need to get status first (without waiting)
 * If its not completed, poll the job, if its completed, then yay nothing to do
* Actually implement the API call for the domain join/unjoin/rejoin that goes through the pfqueue producer client with the status_update option

```
my $client = pf::pfqueue::producer::redis->new();
print $client->submit("general", domain => {operation => "join", domain => "inverse"}, undef, status_update => 1);
```

# Description
Allow to start a pfqueue task asynchronously and poll its status
Use the above for long-running domain operations

# Impacts
pfqueue plumbing
Unified API

# Issue
fixes #3561 

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

2019-03-29 15:39 UTC, julsemaan commented
Example:
https://support.inverse.ca/~jsemaan/domain-join.html

2019-03-31 17:04 UTC, jrouzierinverse requested changes
Redis PUB/SUB is unreliable

The current approach will cause some messages to be lost.
If the subscriber is not listening when the message is published that message will be lost.

The only way to avoid losing message is to use BRPOPLPUSH/RPOPLPUSH.

2019-03-31 17:04 UTC, jrouzierinverse commented on lib/pf/pfqueue/status_updater/redis.pm
> +    $self->connection->expire($self->status_key, $self->status_ttl);
The expire should be done after the hset.
Because if the hash does not exists the expire will fail.

2019-04-01 12:06 UTC, julsemaan commented
We don't really care if a publication gets lost since it doesn't contain anything important as the status key holds all the data.

Receiving a publication on the channel just allows the polling to complete faster. The worst that can happen is that the user will wait 15 seconds because of a missed publication that occurred between his 2 requests. The result of the operation will be the same though.

To me that isn't a big issue but if that's a blocker to the team, I can adjust it but the publisher (pfqueue) shouldn't be blocking and ensuring his publication went through and was received by someone as there is no guarantee someone will be polling the status. Someone could just give up on polling the status of the job or some jobs could be started with intent of polling but the consumer just decides to let it do its job without polling.

2019-04-01 14:25 UTC, julsemaan commented
As verbally discussed, I made polling exit early if the job has already completed

2019-04-01 14:44 UTC, jrouzierinverse requested changes

2019-04-01 14:44 UTC, jrouzierinverse commented on go/caddy/job-status/job-status.go
> +	"github.com/go-redis/redis"
We already have a redis connection pool
"github.com/inverse-inc/packetfence/go/redisclient"

This uses the config of pfqueue to connect to redis.
I know it is too late to rework at least use the config to connect to redis.

2019-04-01 14:44 UTC, jrouzierinverse commented on go/caddy/job-status/job-status.go
> +	sub := h.redis.Subscribe(updatesKey)
defer sub.Close() to avoid a resource leak

2019-04-01 15:10 UTC, julsemaan commented
Performed the requested adjustments

2019-04-02 13:54 UTC, jrouzierinverse commented
rebase

2019-04-02 18:38 UTC, julsemaan commented
Adjustments performed for password handling + rebased

2019-04-02 21:12 UTC, jrouzierinverse commented
rebase then I will merge

2019-04-03 11:38 UTC, julsemaan commented
rebased

2019-04-03 13:10 UTC, merged