fix/allowed_options
inverse-inc/packetfence pull request #4558
Opened 2019-05-21 21:24 UTC by jrouzierinverse

Description
===========
Use the Admin Roles allowed_access_levels

Issue
=====
Fixes #4536

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

2019-05-22 15:50 UTC, fdurand commented
Still missing the access duration.
Also the user need to have the "Nodes - Read" action to be able to see the roles.
Add all the roles appear in the list and not only the one allowed in the admin role.

2019-05-23 16:32 UTC, julsemaan commented
@jrouzierinverse 

Can you fix this ASAP so that it can get into 9.0.1

2019-05-24 12:45 UTC, julsemaan commented
Pushing to 9.0.2 so we can get a full fix for the issue

2019-10-22 07:24 UTC, nqb commented
We will need this PR merged for 9.2.

2019-10-22 20:07 UTC, julsemaan commented
@jrouzierinverse 

Could you work on a full fix based on @fdurand's comments. Its indeed overdue as the current admin lacks some advanced access control due to that missing feature

2019-10-29 14:52 UTC, extrafu commented
@jrouzierinverse 

Make sure we handle roles and access duration validation.

2019-11-04 16:22 UTC, extrafu commented
@julsemaan If all good please merge.

2019-11-04 21:20 UTC, julsemaan commented
Given @fdurand is the assignee and probably knows the problem with more details than me I'll just let him double check the PR to ensure it meets what he expects for the fix

2019-11-05 16:21 UTC, fdurand commented
Still doesn't work, from a user i created with node_manager role, i am able to change the role of a device to any role and same for user and role/access duration.
Also my own user is able to change his own admin role and grant access to ALL.

2019-11-05 16:52 UTC, jrouzierinverse commented
Let me see

2019-11-11 21:20 UTC, fdurand commented
Nodes options looks good.
User options no.
I am not able to set any role/access duration/access level

2019-11-12 16:00 UTC, fdurand commented
After added:
Security event  - READ
Nodes - READ
Configuration Main - READ
System - READ

I am able to set the role of the device (only the allowed roles) but i can set any access duration.

2019-11-19 20:51 UTC, cgx requested changes

2019-11-19 20:51 UTC, cgx commented on html/pfappserver/root/static.alt/src/globals/configuration/pfConfiguration.js
> +  set_role_by_acl_node: {
@satkunas This action doesn't seem to be used anywhere. Forgot to commit your changes to the Node components?

2019-11-19 20:51 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfCSVImport.vue
> +            if (field.types.map(type => fieldTypeComponent[type]).includes(componentTypes[t])) return true
@satkunas Put the `map` outside the *for* loop for better performance.

2019-11-20 19:45 UTC, cgx approved these changes

2019-11-20 20:06 UTC, merged