Pfappserver chosen improvments
inverse-inc/packetfence pull request #4560
Opened 2019-05-22 14:01 UTC by satkunas

# Description
- Improves allowed lookup search by preventing duplicates (`oses`)
- Hides duplicate chosen placeholder on allowed lookups.

# Impacts
None

# Delete branch after merge
YES 

# Checklist
- [n/a] Document the feature
- [n/a] Add unit tests
- [n/a] Add acceptance tests (TestLink)

2019-05-23 18:07 UTC, cgx requested changes

2019-05-23 18:07 UTC, cgx commented on html/pfappserver/root/static.alt/src/globals/configuration/pfConfiguration.js
> +                console.error(`Unhandled meta type: ${meta[key].type}`)
Prefix `console` statement with `// eslint-disable-next-line`.

2019-05-23 18:07 UTC, cgx commented on html/pfappserver/root/static.alt/src/globals/configuration/pfConfiguration.js
> +            console.error(`Unhandled meta: ${property}`)
Prefix `console` statement with `// eslint-disable-next-line`.

2019-05-23 18:16 UTC, satkunas commented
@cgx done

2019-05-24 18:00 UTC, cgx commented
Some visual glitches I noticed.

The placeholder seems misaligned in a single-value instance:

<img width="603" alt="chosen-misaligned-label" src="https://user-images.githubusercontent.com/1088448/58347523-0e97c900-7e2c-11e9-9e85-c0d25f6b9f8f.png">

The border is partially hidden in a multi-value instance:

<img width="1059" alt="chosen-multiselect-border" src="https://user-images.githubusercontent.com/1088448/58347612-4d2d8380-7e2c-11e9-9555-5b8d86274cae.png">

2019-05-27 20:12 UTC, satkunas commented
> Some visual glitches I noticed.

@cgx I am not able to reproduce either of these issues. Could this be browser related?

2019-05-28 02:15 UTC, cgx commented
@satkunas Maybe it's because I'm running [Edge Canary](https://www.microsoftedgeinsider.com/) on macOS .. 🎲

2019-05-28 10:46 UTC, julsemaan commented
@satkunas, I run Netscape on my Palm Pilot and the admin appears in black and white. Can you help ?

Side note: I'm color-blind

2019-05-31 12:41 UTC, cgx approved these changes

2019-05-31 12:41 UTC, merged