Pfappserver event module
inverse-inc/packetfence pull request #4567
Opened 2019-05-23 19:31 UTC by satkunas

# Description
A global singleton store module that binds on window and document events. Reduces the work needed for a template to bind/unbind and track events. Improves performance since bin/unbind is no longer needed throughout.

# Impacts
Replaces the `[escape]` and `[ctrl]` key binds. 

# Delete branch after merge
YES

# Checklist
- [n/a] Document the feature
- [n/a] Add unit tests
- [n/a] Add acceptance tests (TestLink)

## Enhancements
* centralized event bindings

2019-05-24 16:03 UTC, satkunas commented
@cgx please test commit https://github.com/inverse-inc/packetfence/pull/4567/commits/734cf6b541ebe2dcf44f38461a97181532fcb2da to ensure that body click works as expected in security event triggers.

2019-06-05 15:11 UTC, cgx requested changes
Could you also cleanup `NodesImport.vue` and `UsersImport.vue` where we have keydown listeners? Remove the references to `this.noInitBindKeys` which is not defined for those components.

2019-06-05 15:11 UTC, cgx commented on html/pfappserver/root/static.alt/src/store/modules/events.js
> +  altShiftUKey: state => state.focus && state.documentEvent.altKey && state.documentEvent.shiftKey && state.documentEvent.keyCode === state.keyCodes['KeyU'],
Remove trailing comma.

2019-06-05 15:11 UTC, cgx commented on html/pfappserver/root/static.alt/src/store/modules/events.js
> +    commit('RESIZE', null)  // init windowSize
Remove extra space before comment delimiter.

2019-06-05 15:11 UTC, cgx commented on html/pfappserver/root/static.alt/src/store/modules/events.js
> +  focus: true,
Why not initializing `focus` to `false`?

2019-06-05 15:11 UTC, cgx commented on html/pfappserver/root/static.alt/src/store/modules/events.js
> +  escapeKey: state => state.focus && state.documentEvent.keyCode === state.keyCodes['Escape'],
When using constant keys, use the syntax `state.keyCodes.Escape`.

2019-06-05 19:02 UTC, cgx approved these changes

2019-06-05 19:03 UTC, merged