Eduroam documentation
inverse-inc/packetfence pull request #4839
Opened 2019-10-01 19:52 UTC by lzammit

# Description
Eduroam documentation

# Impacts
Documentation  file

# Delete branch after merge
YES

# Checklist
- [X] Document the feature

# NEWS file entries
Eduroam documentation

2019-10-02 00:02 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +2: The access point forward the authentication request to the wireless controller.
forwards

2019-10-02 00:02 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +3: The controller sends the radius authentication to PacketFence on port 11812.
RADIUS authentication request

2019-10-02 00:03 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +5: If it's local REALM, PacketFence does a NTLM request to the AD to verify the identity.
to the Active Directory domain controller

2019-10-02 00:04 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +5b: The AD did not validate the credentials. PacketFence sends a Radius Reject
a RADIUS accept-reject response

2019-10-02 00:04 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +5c: After a successful NTLM authentication, PacketFence returns a Radius Acess Accept to the wireless controller to apply the production VLAN for that mac address.
RADIUS accept-accept response

2019-10-02 00:04 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +5c: After a successful NTLM authentication, PacketFence returns a Radius Acess Accept to the wireless controller to apply the production VLAN for that mac address.
mac -> MAC

2019-10-02 00:05 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +6: If it's a not local REALM, PacketFence proxy the radius request to the eduroam servers
proxies the RADIUS

2019-10-02 00:05 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +8: PacketFence returns a Radius Acess Accept to the wireless controller to apply the production VLAN for that mac address.
RADIUS access-accept response

2019-10-02 00:05 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +8: PacketFence returns a Radius Acess Accept to the wireless controller to apply the production VLAN for that mac address.
mac -> MAC

2019-10-02 00:06 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +Go to the PacketFence administration web interface and go to *Configuration -> Policies and Access Control -> Authentication Sources*.
Open the PacketFence administration...

2019-10-02 00:06 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +The information to setup that source could be found on the eduroam platform.
to setup -> to configure

2019-10-02 00:07 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +Create the Connection Profile named 'Local and external eduroam authentication' Check "Automatically register devices" then create a SSID filter 'eduroam'. Make sure to add the Active Directory sourc
Create a connection profile named

2019-10-02 00:07 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +Inbound authentication (TLRS to PF)
PF -> PacketFence

2019-10-02 00:08 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +1: Eduroam sends the radius authentication to a public IP address (NAT/PAT) bound to PacketFence on the management IP address (Management VIP for a cluster) on port 1812.
RADIUS authentication request

2019-10-02 00:09 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +3a: User identity successfuly authentication on the AD.
Successful user identify authentication on the AD

2019-10-02 00:10 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +4: PacketFence replies to the Eduroam servers either a RADIUS Access Accept for a sucessful authentication or a RADIUS Access Reject for an unsuccessful authentication. PacketFence sets the REALM to
eduroam.... RADIUS access-accept .... RADIUS access-reject... for all successful authentications.

2019-10-02 00:10 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +First, you need to refer to the previous step 'Configure the Eduroam source'.
eduroam

2019-10-02 00:10 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +Once the source is configured, you will need to create a new Connection profile.
connection

2019-10-02 00:10 UTC, extrafu commented on docs/PacketFence_Installation_Guide.asciidoc
> +Create the Connection Profile for outbound authentication
connection profile for outbound authentications

2019-10-02 05:39 UTC, nqb commented
@lzammit, please follow AsciiDoc conventions https://packetfence.org/doc/PacketFence_Developers_Guide.html#_documentation_conventions

2019-10-02 12:04 UTC, lzammit commented
@nqb if you are referencing to the list, it does not work for me because of the 2 levels, thanks.

2019-10-02 12:10 UTC, nqb commented
Hello @lzammit,

AsciiDoc supports several level of lists, take a look at my previous link there is some examples.

2019-10-02 12:17 UTC, nqb requested changes
For path to menus, you can use following syntax: `_Configuration -> Policies and Access Control_` as mentioned in conventions too.

2019-10-02 12:17 UTC, nqb commented on docs/PacketFence_Installation_Guide.asciidoc
> +^^^^^^^^^^^^^^^^^^^^
You can use following syntax: `===`, see https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#section-titles

2019-10-02 12:17 UTC, nqb commented on docs/PacketFence_Installation_Guide.asciidoc
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^
You can use following syntax: `===`, see https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#section-titles

2019-10-02 12:17 UTC, nqb commented on docs/PacketFence_Installation_Guide.asciidoc
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
You can use following syntax: `===`, see https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#section-titles

2019-10-02 12:17 UTC, nqb commented on docs/PacketFence_Installation_Guide.asciidoc
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
You can use following syntax: `===`, see https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#section-titles

2019-10-02 12:17 UTC, nqb commented on docs/PacketFence_Installation_Guide.asciidoc
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
You can use following syntax: `===`, see https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#section-titles

2019-10-02 17:53 UTC, extrafu reviewed
You pervert.

2019-10-17 19:54 UTC, fdurand commented on docs/PacketFence_Installation_Guide.asciidoc
> +8: PacketFence returns a Radius Acess Accept to the wireless controller to apply the production VLAN for that MAC address.
Access Accept

2019-10-17 19:54 UTC, fdurand commented on docs/PacketFence_Installation_Guide.asciidoc
> +5c: After a successful NTLM authentication, PacketFence returns a Radius Acess Accept to the wireless controller to apply the production VLAN for that MAC address.
Access Accept

2019-10-22 05:59 UTC, nqb commented
@lzammit, list items need to be adjust.

2019-10-23 12:22 UTC, lzammit commented
Done!

2019-10-24 11:40 UTC, nqb commented on docs/PacketFence_Installation_Guide.asciidoc
> +* 1: The device connects on the eduroam SSID.
If you want to use ordered lists, you should use followin syntax:
```
. First item
. Second item
. Third item
```

2019-10-24 11:40 UTC, nqb commented on docs/PacketFence_Installation_Guide.asciidoc
> +Local *Exclusive Sources* and click on `New excluse source` then `Eduroam`.
I don't understand this sentence.

There is a typo too : exclus**i**ve in place of excluse

2019-10-24 11:40 UTC, nqb commented on docs/PacketFence_Installation_Guide.asciidoc
> +1: Eduroam sends the RADIUS authentication to a public IP address (NAT/PAT) bound to PacketFence on the management IP address (Management VIP for a cluster) on port 1812.
If you want to use ordered lists, you should use followin syntax:
```
. First item
. Second item
. Third item
```

2019-11-12 19:33 UTC, merged

2019-11-12 19:35 UTC, julsemaan commented
But the main question is: Are the numbered lists following our standards?

2019-11-12 19:37 UTC, extrafu commented
@julsemaan I gave up on that, @lzammit can't even read our own guidelines.