Juniper EX2300 CoA Port Bounce
inverse-inc/packetfence pull request #4887
Opened 2019-11-02 09:43 UTC by lyubomirtraykov

# Description
Perform CoA Port-Bounce on Juniper EX2300 Switch 

# Impacts
(REQUIRED)
Port Bounce method

# Delete branch after merge
YES

# Checklist
- [n/a ] Document the feature
- [ yes] Add unit tests
- [ n/a] Add acceptance tests (TestLink)

# NEWS file entries
(REQUIRED, but may be optional...)
## Enhancements
* Enhance Juniper EX2300

2019-11-02 09:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/inverse-inc/packetfence?pullRequest=4887) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/inverse-inc/packetfence?pullRequest=4887) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/inverse-inc/packetfence?pullRequest=4887) it.</sub>

2019-11-04 13:27 UTC, julsemaan requested changes
Just a minor logging detail to fix and then its ready to merge for 9.2

2019-11-04 13:27 UTC, julsemaan commented on lib/pf/Switch/Juniper/EX2300.pm
> +    $logger->info("boucing $mac using RADIUS CoA-Request method");
boucing -> bouncing

2019-11-04 14:12 UTC, lyubomirtraykov commented
Using _radiusBounceMac is better because we don't need to get the mac from the  ifIndex.

2019-11-04 14:38 UTC, julsemaan commented
From what I can tell _radiusBounce isn't being called anywhere so you need to use setAdminStatus like in the previous version of your PR or else it won't do anything

2019-11-05 12:40 UTC, julsemaan commented on lib/pf/Switch/Juniper/EX2300.pm
> +    $logger->info("boucing $mac using RADIUS CoA-Request method");
You still have boucing instead of bouncing

2019-11-06 15:18 UTC, merged