Added a new trigger on node maintenance task
inverse-inc/packetfence pull request #4948
Opened 2019-11-20 15:25 UTC by fdurand

# Description
Add a security event trigger on node maintenance task

# Impacts
pfmon

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries

## Enhancements
* New security event in node maintenance task

2019-12-19 14:30 UTC, nqb requested changes

2019-12-19 14:30 UTC, nqb commented on lib/pf/node.pm
> +        $apiclient->call('trigger_violation', %violation_data);
`trigger_violation` and `%violation_data` need to be renamed to `security_event`.

2020-04-01 13:25 UTC, julsemaan commented
@nqb, take another look and merge

2020-04-02 07:13 UTC, nqb commented on lib/pf/node.pm
> +        $apiclient->call('security_event', %security_event);
```suggestion
        $apiclient->notify('trigger_security_event', %security_event);
```

2020-04-02 07:14 UTC, nqb commented on lib/pf/node.pm
> +        $apiclient->call('security_event', %security_event);
Make following change and I will merge.

2020-04-02 11:49 UTC, fdurand commented
BUMP

2020-04-02 12:00 UTC, merged