Admin - Switch Import
inverse-inc/packetfence pull request #5034
Opened 2020-01-08 22:23 UTC by satkunas

# Description
Implement CSV import for switches.

# Impacts
n/a

# Issue
fixes #4825

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [n/a] Document the feature
- [n/a] Add unit tests
- [n/a] Add acceptance tests (TestLink)

# NEWS file entries
(REQUIRED, but may be optional...)
## New Features
* Switch CSV Import

## Bug Fixes
* web admin: import switches from CSV is missing (#4825)

2020-01-08 22:24 UTC, satkunas commented
@jrouzierinverse switch/bulkImport endpoint needed resembling the one in Nodes and Users.

There's currently a shim in place here: https://github.com/inverse-inc/packetfence/pull/5034/files#diff-fb264530f0ccc4232739a032f2e08cc7R99

2020-02-25 15:20 UTC, julsemaan commented
Ensure that we can import id, description and group

Also needs to be rebased and then @jrouzierinverse can review + merge

2020-03-05 18:55 UTC, satkunas commented
@julsemaan @jrouzierinverse rebased. Ready for review.

2020-05-04 09:40 UTC, nqb commented
@julsemaan  and @jrouzierinverse, could you review this PR ? Thanks.

2020-05-04 10:32 UTC, jrouzierinverse commented
This should be reworked to use the bulk_import interface when #4212 is merged.

2020-05-07 19:42 UTC, cgx commented on html/pfappserver/root/static.alt/src/views/Configuration/_store/switches.js
> +      return items
This is redundant. `return bulkImport(_items)` is enough.

2020-05-26 08:43 UTC, nqb commented
Would be nice to have in 10.1, changing milestone.

2020-05-29 17:55 UTC, satkunas commented
> This should be reworked to use the bulk_import interface when #4212 is merged.

I will update once it's merged.

2020-05-29 20:17 UTC, satkunas commented
@jrouzierinverse @cgx updated, ready to be re-reviewed.

2020-06-01 15:53 UTC, cgx commented on html/pfappserver/root/static.alt/src/views/Configuration/_components/SwitchesImport.vue
> +    importPromise (payload, dryRun) {
`dryRun` is not used.

2020-06-01 15:55 UTC, cgx commented on html/pfappserver/root/static.alt/src/views/Configuration/_components/SwitchesImport.vue
> +      return new Promise((resolve, reject) => {
You don't have to wrap your call inside another promise. Just do

```
importPromise (payload) {
  return this.$store.dispatch('$_switches/bulkImport', payload)
}
```

2020-06-01 16:01 UTC, cgx commented on html/pfappserver/root/static.alt/src/views/Configuration/_components/SwitchesImport.vue
> +    'pf-csv-import': pfCSVImport,
No need to specify the name since it's already defined in the component itself.

2020-06-01 16:05 UTC, cgx commented on html/pfappserver/root/static.alt/src/views/Configuration/_components/SwitchesImport.vue
> +  margin-right: 0.5rem!important;
This will affect all `b-nav` instances, so make sure it's required and move it to `src/styles/_nav.scss`.

2020-06-01 16:12 UTC, cgx requested changes
@satkunas Some minor changes to do on the frontend.

2020-06-01 17:03 UTC, satkunas commented
@cgx changes pushed

2020-06-01 17:58 UTC, cgx approved these changes

2020-06-01 17:59 UTC, merged