Filter Engines GUI
inverse-inc/packetfence pull request #5143
Opened 2020-02-14 15:30 UTC by satkunas

# Description
Complete rework/refactor of Graphical User Interface (Admin) for Filter Engines 

# Impacts
Changes the Filter Engine workflow.

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## New Features
* TDB

## Enhancements
* TBD

2020-03-06 16:03 UTC, julsemaan commented
Initial comments on this:

- [ ] Should be able to add a description to the filters
- [ ] Actions should have stub values for arguments like the custom syslog parser engine. Ideally, they would have a builder but that could be for the next iteration
- [ ] Fields and values don't automatically populate for the filter, we have to type them manually

Pretty sure some of the above was already thought of by @satkunas and @jrouzierinverse in their own checklist but I wanted to at least get them here so that it can be tracked.

I'll update this comment with more feedback/items today if needed

2020-03-06 16:42 UTC, julsemaan commented
I'm adding this separately as its pretty major but it looks like none of the VLAN filter rules are loaded in the engine so its impossible to test the actual rules this produces

Log of the request:
```
Mar  6 11:40:07 pf-julien packetfence_httpd.aaa: httpd.aaa(22136) DEBUG: [mac:02:00:00:00:00:01] No engine found for AutoRegister (pf::access_filter::test)
```

My configuration:
```
[myass]
scopes=NodeInfoForAutoReg,RegisteredRole,AutoRegister
actions=modify_node: mac = $mac, notes = UNA MACHINA
action.0=modify_node: mac = $mac, notes = UNA MACHINA
status=enabled
role=default
condition=((starts_with(node_info.machine_account, "jse")&&connection_type == "Wireless-802.11-EAP")||node_info.role == "machines")
```

2020-03-11 17:07 UTC, satkunas commented
@julsemaan drag/drop refactored

2020-03-11 23:51 UTC, jrouzierinverse commented
> Initial comments on this:
> 
> * [x]  Should be able to add a description to the filters
> * [ ]  Actions should have stub values for arguments like the custom syslog parser engine. Ideally, they would have a builder but that could be for the next iteration
I will provide this in the OPTIONS
> * [ ]  Fields and values don't automatically populate for the filter, we have to type them manually
I will provide this in the OPTIONS.

However, this will be something we cannot automatically generate we must update this dictionary manually.

> * [ ]  I'm unable to select text in the input boxes that are part of the conditions
> * [ ]  My conditions are getting simplified where if I created a condition `OR (AND condition1, condition2)`, it simplifies it to `AND condition1, condition2`. From what I recall we said we wouldn't try to "optimize" the input of the user to prevent them from thinking the system is broken because what they save isn't the same as what they see after the save

That is not an optimization I cannot represent that as condition string.
OR (AND condition1, condition2)  = (condition1 && condition2)
AND (condition1) = condition1
OR (condition1) = condition1

> * [x]  Would be nice to move sub-conditions anywhere within the main condition. For example I have a condition node_info.machine_account starts_with host/ and I want to move it into a nested OR condition I just added afterwards. It works if that nested OR already contains a condition, not if its empty

> * [x]  Having difficulty dragging and dropping sub-conditions where we need to drag it into the sub-condition and then highlight the new position of what we're dragging so that it goes at the right place
> 
> Pretty sure some of the above was already thought of by @satkunas and @jrouzierinverse in their own checklist but I wanted to at least get them here so that it can be tracked.
> 
> I'll update this comment with more feedback/items today if needed

2020-03-12 10:03 UTC, jrouzierinverse commented
The stubs are for the action parameters are now available in the OPTIONS

2020-03-13 18:26 UTC, satkunas commented
Adding 2 basic conditions results in missing end brackets in string-ified condition

![Screenshot_20200313_142514](https://user-images.githubusercontent.com/3904468/76649239-a0490200-6536-11ea-80cb-3d9bec66825e.png)

`dhcp_filters.conf`
```
[DHCP Filter]
scopes=
status=enabled
description=Test
condition=contains(foo, "bar" && contains(bar, "foo"
```

2020-03-13 18:37 UTC, julsemaan commented
Stuff that in my opinion will be necessary:

- [ ]  Fields and values don't automatically populate for the filter, we have to type them manually
- [ ] Getting a warning for when the condition that is saved in the backend isn't the same as the condition that was created by the user; issue:  

> My conditions are getting simplified where if I created a condition OR (AND condition1, condition2), it simplifies it to AND condition1, condition2. From what I recall we said we wouldn't try to "optimize" the input of the user to prevent them from thinking the system is broken because what they save isn't the same as what they see after the save

2020-03-13 19:47 UTC, satkunas commented
An error occurs when either enabling or disabling an item in the dhcp filters collection. This does not occur with the vlan filters.

Method:
`PATCH /api/v1/config/filter_engines/dhcp_filter/DHCP%20Filter`

Payload:
```json
{
id: "DHCP Filter"
quiet: true
status: "enabled"
}
```

Response:
```json
{"errors":[{"field":"condition.op","message":"'var' is not a valid value"}],"message":"Unable to validate","status":422}
```

2020-03-18 12:55 UTC, julsemaan commented
Comments from new tests

- [ ] The RADIUS filter merge_answer should be a toggle between `yes` and `no`
- [ ] When typing in the attribute fields of my condition, the focus keeps being stolen and I can't type anymore in the field that was selected
- [ ] I'm still unable to select text in the fields of a condition (which was supposed to have been fixed)

- [ ] Trying to negate a condition using NOT ALL creates a bad condition:
GUI:
![image](https://user-images.githubusercontent.com/3857942/76962548-cdf6c800-68f5-11ea-8660-915447159198.png)
Configuration:
```
[test1]
status=enabled
answer.0=3Com-Product-ID = hello
description=test1
scopes=
condition=not_and(, "")
```

- [ ] The defaults of the DNS filters have not been converted

- [ ] We're missing an upgrade script to convert existing configuration from the old format to the new format

Reported previously and still active:

- [ ]  Fields and values don't automatically populate for the filter, we have to type them manually
- [ ] Getting a warning for when the condition that is saved in the backend isn't the same as the condition that was created by the user; issue:  

> My conditions are getting simplified where if I created a condition OR (AND condition1, condition2), it simplifies it to AND condition1, condition2. From what I recall we said we wouldn't try to "optimize" the input of the user to prevent them from thinking the system is broken because what they save isn't the same as what they see after the save

- [ ] The backend is still not doing anything so we can't test these actually do work

2020-03-18 14:09 UTC, satkunas commented
>  When typing in the attribute fields of my condition, the focus keeps being stolen and I can't type anymore in the field that was selected

This is fixed, but one side effect my be some unexpected behavior after drag-drop. Keep an eye out.

2020-03-18 14:23 UTC, satkunas commented
> I'm still unable to select text in the fields of a condition (which was supposed to have been fixed)

Unable to fix: 
https://bugzilla.mozilla.org/show_bug.cgi?id=800050

2020-03-18 14:29 UTC, jrouzierinverse commented
Fixed the NOT_AND serialization

2020-03-18 15:58 UTC, julsemaan commented
> Fixed the NOT_AND serialization

Doesn't work for me, I'm getting a different result but still not something that makes sense:
```
[test1]
status=enabled 
answer.0=3Com-Product-ID = hello
description=test1
scopes=
condition=!() 
```

2020-03-18 16:03 UTC, julsemaan commented
>  The RADIUS filter merge_answer should be a toggle between yes and no

When I save a new RADIUS filter without touching the merge_answer toggle, it doesn't save the field to `merge_answer=no` and simply omits it from the request payload. IMO, it should explicitly set it to `merge_answer=no`

This is the request payload:
```
{"answers":null,"condition":{"field":null,"op":"and","value":null,"values":[]},"description":"test3","id":"test3","merge_answer":null,"radius_status":null,"scopes":null,"status":"enabled"}
```

2020-03-18 16:03 UTC, julsemaan commented
I have unchecked the elements that are still buggy from the list above to help tracking the progress, just re-check them once its fixed

2020-03-19 15:30 UTC, satkunas commented
> > The RADIUS filter merge_answer should be a toggle between yes and no
> 
> When I save a new RADIUS filter without touching the merge_answer toggle, it doesn't save the field to `merge_answer=no` and simply omits it from the request payload. IMO, it should explicitly set it to `merge_answer=no`
> 
> This is the request payload:
> 
> ```
> {"answers":null,"condition":{"field":null,"op":"and","value":null,"values":[]},"description":"test3","id":"test3","merge_answer":null,"radius_status":null,"scopes":null,"status":"enabled"}
> ```

@jrouzierinverse Please set the meta default for `merge_answer` to 'no', it is currently `null`.
```
/usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/filter_engines/radius_filters| jq '.meta.status.default'
"enabled"
```
```
/usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/filter_engines/radius_filters| jq '.meta.merge_answers.default'
null
```

2020-03-20 15:47 UTC, julsemaan commented
>  Trying to negate a condition using NOT ALL creates a bad condition:

and 

> When I save a new RADIUS filter without touching the merge_answer toggle, it doesn't save the field to merge_answer=no and simply omits it from the request payload. IMO, it should explicitly set it to merge_answer=no

are fixed, I've updated the list above

2020-03-23 15:51 UTC, jrouzierinverse commented
Actions for the VlanFilters are not required.

2020-03-23 16:13 UTC, jrouzierinverse commented
Make Scopes required for all filters.

2020-03-23 21:16 UTC, extrafu commented
TODO @jrouzierinverse 

[ ] Fields and values don't automatically populate for the filter, we have to type them manually (backend part)

TODO @satkunas 
[ ] issue of actions being required when they are
[ ] scopes are now required (at least one needs to be defined)
[ ] Fields and values don't automatically populate for the filter, we have to type them manually

2020-03-24 12:15 UTC, julsemaan commented
>  My conditions are getting simplified where if I created a condition OR (AND condition1, condition2), it simplifies it to AND condition1, condition2. From what I recall we said we wouldn't try to "optimize" the input of the user to prevent them from thinking the system is broken because what they save isn't the same as what they see after the save

@jrouzierinverse, this is still happening

What I am saving:
![image](https://user-images.githubusercontent.com/3857942/77424249-2cfd8680-6da7-11ea-923c-444dbdbed4b2.png)

What is displayed after I create it, then refresh the page:
![image](https://user-images.githubusercontent.com/3857942/77424313-46063780-6da7-11ea-8ffe-8f743ee5760c.png)

The user should be warned in this case that what he saved isn't what is saved in the configuration.

@jrouzierinverse, if its @satkunas that needs to handle this, please let us know

2020-03-24 12:16 UTC, satkunas commented
@extrafu actions are only required when "Run actions" is enabled.

> issue of actions being required when they are not

2020-03-24 12:39 UTC, satkunas commented
> Actions for the VlanFilters are not required.

done

> Make Scopes required for all filters.

done

2020-03-24 14:24 UTC, jrouzierinverse commented
> > My conditions are getting simplified where if I created a condition OR (AND condition1, condition2), it simplifies it to AND condition1, condition2. From what I recall we said we wouldn't try to "optimize" the input of the user to prevent them from thinking the system is broken because what they save isn't the same as what they see after the save
> 
> @jrouzierinverse, this is still happening
> 
> What I am saving:
> ![image](https://user-images.githubusercontent.com/3857942/77424249-2cfd8680-6da7-11ea-923c-444dbdbed4b2.png)
> 
> What is displayed after I create it, then refresh the page:
> ![image](https://user-images.githubusercontent.com/3857942/77424313-46063780-6da7-11ea-8ffe-8f743ee5760c.png)
> 
> The user should be warned in this case that what he saved isn't what is saved in the configuration.
> 
> @jrouzierinverse, if its @satkunas that needs to handle this, please let us know

This should be fixed for all cases not just the simple ones.

2020-03-24 16:02 UTC, julsemaan requested changes

2020-03-24 16:02 UTC, julsemaan commented on html/pfappserver/lib/pfappserver/Form/Field/DHCPAnswer.pm
> +    OptionSubnetMask                                 => 1,
It would greatly help to have the option ID in the label to recognize them better

2020-03-24 16:02 UTC, julsemaan commented on lib/pf/UnifiedApi/Controller/Config/FilterEngines/DHCPFilters.pm
> +sub is_sortable {
This code is being repeated in a lot of controllers, a role would be better (or a util function function you reuse)

2020-03-24 16:07 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Field/DHCPAnswer.pm
> +    OptionSubnetMask                                 => 1,
It already is. Look at the options_type method below

2020-03-24 19:46 UTC, julsemaan commented
Republishing TODO with new bugs

TODO @jrouzierinverse 

- [ ] Fields and values don't automatically populate for the filter, we have to type them manually (backend part)
- [x] Warning for the simplification of a condition (check if it should be in the frontend)
- [x]  The backend is still not doing anything so we can't test these actually do work
- [ ] The defaults of the DNS filters have not been converted
- [ ] We're missing an upgrade script to convert existing configuration from the old format to the new format
- [ ] Broken RADIUS filters backend engine

TODO @satkunas 
- [ ] issue of actions being required when they are not
- [x] scopes are now required (at least one needs to be defined)
- [ ] Fields and values don't automatically populate for the filter, we have to type them manually

BUGS:
- [ ] DNS filters scopes are wrong

2020-03-25 15:33 UTC, merged