Master/Slave radius proxy and degraded workflow
inverse-inc/packetfence pull request #5616
Opened 2020-06-19 19:08 UTC by fdurand

# Description
Proxy radius request when the server is in slave mode.
It include a degraded radius configuration in order to reply even if the main radius server is down.

When the main server is up, the slave radius server proxy to the main one and store the reply in the radreply table.

If it 802.1x the nthash key is shared all accross the servers member and in degraded situation radius use this hash and reply with the latest attributes coming from previous authentication (radreply table).

If it's mac-auth we reply with the previous attributes.

# Impacts
Master Slave configuration.

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## New Features
* Master/Slave radius proxy and degraded workflow

2020-08-10 19:31 UTC, jrouzierinverse commented
Can you rebase?
Also, there is a circular dependency in ```pf::cluster``` causing the perl tests to break.

2020-09-09 11:44 UTC, extrafu commented
@fdurand Please rebase so we can merge it

2020-09-15 17:11 UTC, extrafu commented
@fdurand Please rebase.

2020-09-15 17:11 UTC, extrafu commented
@jrouzierinverse Please review.

2020-09-15 19:12 UTC, jrouzierinverse requested changes

2020-09-15 19:12 UTC, jrouzierinverse commented on db/pf-schema-X.Y.Z.sql
> +);
Go the following error.
"ERROR 1075 (42000) at line 695: Incorrect table definition; there can be only one auto column and it must be defined as a key"

2020-09-15 19:12 UTC, jrouzierinverse commented on lib/pf/cluster.pm
> +
This is function getDBMaster is duplicated.

2020-09-15 19:12 UTC, jrouzierinverse commented on lib/pf/services/manager/radiusd_child.pm
> +    }
This file fails coding-style.t

2020-09-18 18:13 UTC, fdurand commented
Tested and fixed. Ready for another review.

2020-09-22 11:33 UTC, extrafu commented
@jrouzierinverse Review again and merge if all is fine.

2020-09-22 16:09 UTC, merged