feature/switch-template-cli-access
inverse-inc/packetfence pull request #5708
Opened 2020-07-19 22:54 UTC by jrouzierinverse

Description
===========
Add support for cli Access for Switch::Template

NEWS file entries
=======================
Enhancements
-------------
* Add support for cli Access for Switch::Template

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

2020-07-20 00:09 UTC, extrafu commented on html/pfappserver/root/static.alt/src/views/Configuration/_config/switchTemplate.js
> +          label: i18n.t('Cli Authorize Read Scope'),
Cli -> CLI

2020-07-20 00:09 UTC, extrafu commented on html/pfappserver/root/static.alt/src/views/Configuration/_config/switchTemplate.js
> +          label: i18n.t('Cli Authorize Write Scope'),
Cli -> CLI

2020-07-22 15:41 UTC, jrouzierinverse commented
bump

2020-09-14 07:54 UTC, nqb requested changes
It failed on my side with following error:

```
Sep 14 07:42:49 pfcen7dev packetfence_httpd.aaa: httpd.aaa(8717) ERROR: [mac:[undef]] Can't use string ("") as an ARRAY ref while "strict refs" in use at /usr/local/pf/lib/pf/radius/rest.pm line 33.
 (pf::WebAPI::REST::handler)
```
I got same error if I tested without a switch template (using Generic module)

2020-09-15 17:17 UTC, lzammit commented
Works!

2020-09-16 08:00 UTC, nqb commented
Need a rebase.

2020-09-16 12:13 UTC, extrafu commented
Ready for merging? If so, let's do it.

2020-09-16 12:21 UTC, nqb commented
Doing a latest test and I will merge.

2020-09-16 12:47 UTC, merged