feature/node-delete
inverse-inc/packetfence pull request #5724
Opened 2020-07-27 14:15 UTC by jrouzierinverse

Description
===========
Cleanup node before deletion

NEWS file entries
=======================
Enhancements
-------------
* Allow to delete a node from web admin with a locationlog opened (#5492)

Issue
=====
fixes #5492

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

2020-09-16 11:40 UTC, julsemaan requested changes

2020-09-16 11:40 UTC, julsemaan commented on html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesSearch.vue
> +              <span class="ml-4">{{ $t('Delete') }}</span>
I'm really not sure about allowing the ability to bulk delete.

This has the potential to cause a sh*tload of problems.

I'm fine with leaving the API call there and the admin plumbing but I'd remove the option for now

2020-09-17 14:45 UTC, extrafu commented
@satkunas Please remove the bulk option from the GUI. @cgx have a quick look at the JS. @julsemaan merge after please

2020-09-17 20:57 UTC, cgx commented on html/pfappserver/root/static.alt/src/views/Nodes/_store/index.js
> +      commit('NODE_BULK_SUCCESS', response)
We need a new mutation (`NODE_BULK_DELETED`), which does the same thing as `NODE_DESTROYED` and `NODE_NOT_EXISTS` but for the list of deleted nodes.

2020-09-18 14:36 UTC, satkunas commented on html/pfappserver/root/static.alt/src/views/Nodes/_store/index.js
> +      commit('NODE_BULK_SUCCESS', response)
My last commit hid the bulk delete, so there's no longer any need for this method in the store module.

2020-09-18 14:43 UTC, cgx commented
@julsemaan I think we're ready to merge.

2020-09-18 15:35 UTC, merged