feature/default-switch-packetfence-standard
inverse-inc/packetfence pull request #5742
Opened 2020-08-10 18:33 UTC by jrouzierinverse

Description
===========
Set the default switch type to Packetfence::Standard

NEWS file entries
=======================

Enhancements
-------------
* Set the default switch type to Packetfence::Standard

Issue
=====
fixes #5490

Delete branch after merge
=========================
NO

UPGRADE file entries
=========================

Set the switch type to Generic if it was not previously defined.

/usr/local/pf/addons/upgrade/to-10.2-default-switch-packetfence-standard.pl

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

2020-08-11 05:48 UTC, nqb requested changes
There is an ambiguity for `addons/upgrade/to-10.2-default-switch-packetfence-standard.pl` script.

Name of script doesn't match its description: "Rename Generic switch type to Packetfence::SNMP" and its actions: script is trying to set Generic value for switches.

2020-08-11 20:06 UTC, jrouzierinverse commented
Fixed the verbage

2020-09-09 14:31 UTC, nqb commented on addons/upgrade/to-10.2-default-switch-packetfence-standard.pl
> +=cut
If purpose of this PR is to "Set the default switch type to Packetfence::Standard", title and description needs to be adjust.

2020-09-14 09:12 UTC, nqb commented on addons/upgrade/to-10.2-default-switch-packetfence-standard.pl
> +=cut
Also description of PR (Upgrade section) need to be edited.

2020-09-14 09:42 UTC, nqb reviewed
Should we not remove Generic switch module too ?

2020-09-14 09:49 UTC, nqb requested changes
If we want to replace `Generic` switch module by `PacketFence::Standard` switch module, we should first merge #5708, rebase and add `cliAuthorizeRead` and `cliAuthorizeWrite` scopes to `PacketFence::Standard` switch module based on what we do in Generic switch module.

I can take care of this change.

2020-09-15 17:28 UTC, jrouzierinverse commented
Let's remove the Generic switch in 11.0.

2020-09-15 17:31 UTC, jrouzierinverse commented
There is no need to add cliAuthorizeRead and cliAuthorizeWrite scopes to PacketFence::Standard.
As it has the same behavior of the Generic module if none are defined.

2020-09-16 07:54 UTC, nqb commented on addons/upgrade/to-10.2-default-switch-packetfence-standard.pl
> +=cut
Purpose of this script is to set Generic type to switch which don't have any type.

2020-09-16 07:54 UTC, merged