Integer based switch_ip searches in locationlog
inverse-inc/packetfence pull request #5820
Opened 2020-09-22 19:22 UTC by satkunas

# Description
Adds a virtual column to the locationlog table allowing integer based searches on nodes using a switch CIDR (10.0.0.0/9 = range 10.0.0.1 - 10.127.255.254).

The switch dropdown in the Nodes section of the webadmin will utilize `greater_than_equal` and `less_than_equal` operators during a ranged node search for CIDR defined switches. Non-CIDR defined switches will continue to work as-is with a single `equals` operator.

# Issue
Fizxes #

# Delete branch after merge
YES

# Checklist
- [n/a] Document the feature
- [n/a] Add unit tests
- [n/a] Add acceptance tests (TestLink)

## Enhancements
* Range based node searches from switch CIDR.

## Bug Fixes
* Searching by 'Source Switch Identifier' for a switch range doesn't work (#5792)

2020-09-22 19:22 UTC, satkunas commented
@jrouzierinverse it's all yours.

2020-09-23 15:28 UTC, satkunas commented
@julsemaan ready for review

2020-09-23 15:50 UTC, jrouzierinverse requested changes

2020-09-23 15:50 UTC, jrouzierinverse commented on html/pfappserver/root/static.alt/src/views/Nodes/index.vue
> +                  query = { query: JSON.stringify({ op: 'and', values: [{ op: 'or', values: [{ field: 'locationlog.switch_ip', op: 'equals', value: switchGroupMember.id }] }] }) }
This will not allow search mac based switches

2020-09-24 11:35 UTC, julsemaan commented
We need to get this into 10.2 since it will not be possible to backport it to the maintenance

2020-09-24 17:40 UTC, julsemaan commented
I'm getting the following error while viewing a node:
```
Sep 24 13:39:00 test-fresh packetfence: pfperl-api(55429) ERROR: Database query failed with non retryable error: The used SELECT statements have a different number of columns (errno: 1222) [SELECT `tenant_id`, `mac`, `switch`, `port`, `vlan`, `role`, `connection_type`, `connection_sub_type`, `dot1x_username`, `ssid`, `start_time`, `end_time`, `switch_ip`, `switch_ip_int`, `switch_mac`, `stripped_user_name`, `realm`, `session_id`, `ifDesc`, `voip` FROM `locationlog` WHERE ( ( `locationlog`.`mac` = ? AND `locationlog`.`tenant_id` = ? ) ) UNION ALL SELECT `tenant_id`, `mac`, `switch`, `port`, `vlan`, `role`, `connection_type`, `connection_sub_type`, `dot1x_username`, `ssid`, `start_time`, `end_time`, `switch_ip`, `switch_mac`, `stripped_user_name`, `realm`, `session_id`, `ifDesc`, `voip` FROM `locationlog_history` WHERE ( ( `locationlog_history`.`mac` = ? AND `locationlog_history`.`tenant_id` = ? ) ) LIMIT ? OFFSET ?]{94:db:c9:38:85:5b, 1, 94:db:c9:38:85:5b, 1, 1001, 0} (pf::dal::db_execute)
```

Guessing because switch_ip_int is not in locationlog_history

2020-09-24 18:14 UTC, jrouzierinverse commented
> I'm getting the following error while viewing a node:
> 
> ```
> Sep 24 13:39:00 test-fresh packetfence: pfperl-api(55429) ERROR: Database query failed with non retryable error: The used SELECT statements have a different number of columns (errno: 1222) [SELECT `tenant_id`, `mac`, `switch`, `port`, `vlan`, `role`, `connection_type`, `connection_sub_type`, `dot1x_username`, `ssid`, `start_time`, `end_time`, `switch_ip`, `switch_ip_int`, `switch_mac`, `stripped_user_name`, `realm`, `session_id`, `ifDesc`, `voip` FROM `locationlog` WHERE ( ( `locationlog`.`mac` = ? AND `locationlog`.`tenant_id` = ? ) ) UNION ALL SELECT `tenant_id`, `mac`, `switch`, `port`, `vlan`, `role`, `connection_type`, `connection_sub_type`, `dot1x_username`, `ssid`, `start_time`, `end_time`, `switch_ip`, `switch_mac`, `stripped_user_name`, `realm`, `session_id`, `ifDesc`, `voip` FROM `locationlog_history` WHERE ( ( `locationlog_history`.`mac` = ? AND `locationlog_history`.`tenant_id` = ? ) ) LIMIT ? OFFSET ?]{94:db:c9:38:85:5b, 1, 94:db:c9:38:85:5b, 1, 1001, 0} (pf::dal::db_execute)
> ```
> 
> Guessing because switch_ip_int is not in locationlog_history

Commit 26163f9e7f993c7a42b91372318f34dd4b1d998f fixes this.

2020-09-24 18:15 UTC, merged