Fix/5861
inverse-inc/packetfence pull request #5906
Opened 2020-10-08 20:26 UTC by fdurand

# Description
Download the correct certificate based on the profile id and the cn
Revoke the correct certificate based on the serial number and the cn 

# Issue
fixes #5861

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries

## Bug Fixes
* Fix issue when pulling the wrong certificate only based on the cn  (#5861)
* Issue with Zammitbug in dinde context (#43)

2020-10-14 19:57 UTC, julsemaan commented on lib/pf/pki_provider/packetfence_pki.pm
> +    my ($status, $count) = pf::dal::ikey_value_storage->remove_items(%options);
s/ikey/key/

2020-10-14 19:59 UTC, fdurand commented on lib/pf/pki_provider/packetfence_pki.pm
> +    my ($status, $count) = pf::dal::ikey_value_storage->remove_items(%options);
i should deposit the brand

2020-10-15 11:20 UTC, julsemaan commented on go/caddy/pfpki/models.go
> +				return Information, errors.New("A database error occured. See log for details.")
use a constant for `errors.New("A database error occured. See log for details.")` since its the same error over and over

2020-10-15 11:20 UTC, julsemaan commented on lib/pf/pki_provider/packetfence_pki.pm
> +        if ($key_value) {
Would it be relevant to log an error or warning when we don't find the value?

It shouldn't happen if a cert issued by this code gets revoked but will happen for certs issued by the previous code from my understanding

2020-12-21 16:56 UTC, jrouzierinverse requested changes

2020-12-21 16:56 UTC, jrouzierinverse commented on lib/pf/pki_provider/packetfence_pki.pm
> +    $obj->merge(\%data);
Remove this line as does nothing.

2021-01-26 19:43 UTC, fdurand commented
Bump

2021-12-13 20:05 UTC, fdurand commented
New PR for that: #6768

2021-12-13 20:05 UTC, closed without merging