add cancelation link in email for stripe billing
inverse-inc/packetfence pull request #5928
Opened 2020-10-19 16:07 UTC by julsemaan

# Description
Adds a cancelation link for Stripe subscriptions

# Impacts
Stripe billing engine (subscriptions)

# Delete branch after merge
YES

# NEWS file entries
(REQUIRED, but may be optional...)
## New Features
* Added a link to cancel a Stripe subscription in the confirmation email sent during the registration

2020-12-21 15:19 UTC, jrouzierinverse requested changes

2020-12-21 15:19 UTC, jrouzierinverse commented on lib/pf/Authentication/Source/StripeSource.pm
> +    my ($self, $info, $query_args) = @_;
rename $info to $subscription_id so it is clear what that variable is for.

2020-12-21 15:19 UTC, jrouzierinverse commented on html/captive-portal/lib/captiveportal/PacketFence/Controller/Status.pm
> +    my ($self, $c, $source_id, $info) = @_;
rename $info to $subscription_id so it is clear what that variable is for.

2021-01-22 19:25 UTC, julsemaan commented
Comments have been addressed

@jrouzierinverse, ready to merge if its fine for you

2021-01-23 14:27 UTC, merged