feature/config-bulk-import-async
inverse-inc/packetfence pull request #5941
Opened 2020-10-28 15:48 UTC by jrouzierinverse

Description
===========
Allow the bulk import of config items to be async.

Impacts
=======
Bulk config import

NEWS file entries
=======================
Enhancements
-------------
* Allow the bulk import of config items to be async.

Issue
=====
Related #5920

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

2020-10-28 17:46 UTC, jrouzierinverse commented
@cgx @satkunas 
This can be used by using setting the async flags.
```json
{ "async" : true, "items" : [ {  "id" : "value_1" , "value_2" : "2" } ] }
```
Results
```json
{ "task_id" : "54321" }
```

To get the results use the task poll API

GET /api/v1/pfqueue/task/54321/status/poll

2021-01-24 15:38 UTC, jrouzierinverse commented
Can this be merged and an issue create to implement this logic in the frontend.

2021-08-04 16:01 UTC, satkunas commented
@jrouzierinverse frontend pushed, ready to merge

2021-09-29 17:12 UTC, julsemaan commented
@satkunas, does this need to be revisited with the admin rework?

If so, this needs to be postponed

2021-09-29 19:13 UTC, satkunas commented
@julsemaan I resolved a small merge conflict. I don't see anything else standing in the way from being merged.

2021-10-05 13:42 UTC, extrafu commented
@satkunas Make sure it's still relevant.

2021-10-05 13:58 UTC, satkunas commented
UI code is OK to merge

2021-10-05 14:03 UTC, julsemaan requested changes

2021-10-05 14:03 UTC, julsemaan commented on lib/pf/UnifiedApi/Controller/Config.pm
> +    my $results = $self->do_bulk_import($data);
An else statement would make things clearer that this is the synchronous import that will only be called if async is false

2021-10-07 11:36 UTC, merged