Fix/5954 5952
inverse-inc/packetfence pull request #5955
Opened 2020-11-03 08:23 UTC by nqb

# Description
- SSIDs are not hidden by default when creating a provisioner (#5952) 
- with_aup is correctly displayed on GUI (#5954)

# Impacts
Provisioning
Portal Module

# Issue
fixes #5952 
fixes #5954 

# Delete branch after merge
YES

# NEWS file entries
## Bug Fixes
* SSIDs are not hidden by default when creating a provisioner (#5952) 
* with_aup is correctly displayed on GUI (#5954)

2020-11-03 08:23 UTC, nqb commented
`with_aup` fix works but not `broadcast` fix.

2020-11-03 10:52 UTC, nqb commented
Tested after build on a pipeline and both settings works as expected.

2020-11-05 13:19 UTC, nqb commented
Bump

2020-11-10 13:39 UTC, satkunas approved these changes
Javascript looks good!

2020-11-10 13:53 UTC, nqb commented
@jrouzierinverse, is it ok for you ?

2020-11-10 15:42 UTC, jrouzierinverse requested changes
unchecked_value is not valid parameter.

2020-11-10 15:42 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/PortalModule/Authentication.pm
> +   unchecked_value => 0,
Rename unchecked_value -> input_without_param 
https://metacpan.org/pod/HTML::FormHandler::Field::Checkbox

2020-11-10 15:42 UTC, jrouzierinverse commented on html/pfappserver/lib/pfappserver/Form/Config/Provisioning/mobileconfig.pm
> +   unchecked_value => 0,
Rename unchecked_value -> input_without_param

https://metacpan.org/pod/HTML::FormHandler::Field::Checkbox

2020-11-23 11:48 UTC, nqb commented
Thanks @jrouzierinverse, it should be good now.

2020-12-08 06:48 UTC, merged