Gui Performance - Vue3 Composition API
inverse-inc/packetfence pull request #6035
Opened 2020-12-11 16:22 UTC by satkunas

# Description
Implements vue-composition API.
Refactor Confguration View's Forms

# Impacts
npm packages
vue runtime

# Delete branch after merge
YES 

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## New Features
* GUI configuration form refactor

## Enhancements
* ...

## Bug Fixes
* ...

2020-12-14 13:17 UTC, nqb commented
I just run a pipeline to see if build passed on CI: https://gitlab.com/inverse-inc/packetfence/-/pipelines/229502861

2020-12-23 22:14 UTC, cgx requested changes

2020-12-23 22:14 UTC, cgx commented on html/pfappserver/root/static.alt/README.md
> +* [mime-type](https://github.com/jshttp/mime-types) -- mime/content-type
Add a reference to `yup`.

2020-12-23 22:14 UTC, cgx commented on html/pfappserver/root/static.alt/package.json
> +    "vue-cli-plugin-i18n": "^0.6.1",
Is downgrading `vue-cli-plugin-i18n` necessary?

2020-12-23 22:14 UTC, cgx commented on html/pfappserver/root/static.alt/package.json
> +    "webpack-bundle-analyzer": "^4.2.0"
`webpack-bundle-analyzer` is already a dependency of `@vue/cli-service`. You can remote it.

2020-12-23 22:14 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/new/BaseContainerLoading.vue
> +    default: true
Are those two lines necessary?

2020-12-23 22:14 UTC, cgx commented on html/pfappserver/root/static.alt/src/composables/useFormButtonBar.js
> +  })*/
Unsure about the reset button? If it makes sense to always have it, remove this code.

2020-12-23 22:14 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfSearchBoolean.vue
> +      <b-form-select class="mr-1" v-localModel.lazy="localModel.values[0].values[0].value" :options="values(localModel.values[0].values[0])" v-else-if="isFieldType(selectValueType, localModel.values[
`v-localModel`? Regexp glitch?

2020-12-23 22:14 UTC, cgx commented on html/pfappserver/root/static.alt/src/components/pfSearchBoolean.vue
> +              <b-form-select class="mr-1" v-localModel.lazy="rule.value" :options="values(rule)" v-else-if="isFieldType(selectValueType, rule)"></b-form-select>
`v-localModel`? Regexp glitch?

2020-12-23 22:14 UTC, cgx commented on html/pfappserver/root/static.alt/src/composables/useFormProvide.js
> +  */
Will this commented code be eventually uncommented?

2021-01-05 13:23 UTC, satkunas commented on html/pfappserver/root/static.alt/package.json
> +    "webpack-bundle-analyzer": "^4.2.0"
Existing dependency is not enough to use https://github.com/inverse-inc/packetfence/blob/2ed21aca981c35c0a36f78e43128be0dda289700/html/pfappserver/
root/static.alt/vue.config.js#L40

Direct dep is needed.

2021-01-07 16:46 UTC, merged