feature/tenant-aware-pfdhcplistener
inverse-inc/packetfence pull request #6060
Opened 2020-12-28 17:07 UTC by jrouzierinverse

Description
===========
Make the pfdhcplistener tenant aware

Impacts
=======
pfdhcplistener

NEWS file entries
=======================
Enhancements
-------------
* The pfdhcplistener is tenant aware.

Issue
=====
fixes #5991

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

UPGRADE file entries
=========
To add the tenant_id to all network configurations run 
perl /usr/local/pf/addons/upgrade/to-11.0-network-conf.pl

2020-12-28 17:10 UTC, extrafu commented on lib/pf/ConfigStore/L2Network.pm
> +#use pf::constants::config;
Remove?

2020-12-28 17:11 UTC, extrafu commented on t/unittest/dhcp/processor_v4.t
> +#This test will running last
Rephrase

2021-01-06 13:33 UTC, jrouzierinverse commented
done

2021-01-06 14:06 UTC, nqb commented
I'm self-assigning in order to test.

2021-01-26 14:23 UTC, nqb requested changes

2021-01-26 14:23 UTC, nqb commented on addons/upgrade/to-11.0-network-conf.pl
> +
Wrong description

2021-01-27 11:46 UTC, jrouzierinverse commented
Updated and rebased

2021-03-16 10:56 UTC, nqb commented
@satkunas,

When I tried to create an unmanaged network using "New Routed Network" button, I don't have "Unmanaged" choice in dropdown list of "Type" field. I checked return of API (OPTIONS /api/v1/config/routed_networks) and it contains:

```
0: {text: "Isolation", value: "vlan-isolation"}
1: {text: "Registration", value: "vlan-registration"}
2: {text: "DNS Enforcement", value: "dns-enforcement"}
3: {text: "Inline Layer 3", value: "inlinel3"}
4: {text: "Unmanaged", value: "other"}
```

2021-03-22 08:04 UTC, nqb commented
Closing this PR in favour of #6204

2021-03-22 08:04 UTC, closed without merging