Update to Stripe v3
inverse-inc/packetfence pull request #6121
Opened 2021-01-29 17:56 UTC by julsemaan

# Description
Stripe now required to use the latest version of Stripe checkout (elements) for auto compliance, this updates the integration to use Stripe elements (also known as Stripe checkout v3)

# Impacts
Stripe integration

# Delete branch after merge
YES

# NEWS file entries
## Enhancements
* Updated Stripe integration to use Stripe Elements

2021-01-29 17:57 UTC, julsemaan commented
There is 1 last detail to figure out, I had to go back to creating one customer entry per subscription (instead of reusing the customer entry) due to how declines are now handled.

Reached out to Stripe regarding that, we'll see if I have a way to put it back to using the same customer object, otherwise we'll merge as-is.

2021-03-23 12:13 UTC, julsemaan commented
@jrouzierinverse, please review this for inclusion in 10.3

2021-03-23 14:39 UTC, jrouzierinverse requested changes

2021-03-23 14:39 UTC, jrouzierinverse commented on lib/pf/Authentication/Source/StripeSource.pm
> +    my $subscriptions = $self->_get_json($self->curl, "v1/subscriptions?customer=".$data->{id});
```$data->{id}``` needs to url encoded

2021-03-23 15:32 UTC, julsemaan commented on lib/pf/Authentication/Source/StripeSource.pm
> +    my $subscriptions = $self->_get_json($self->curl, "v1/subscriptions?customer=".$data->{id});
Done

2021-03-23 16:41 UTC, merged