feature/remove-inline-accounting
inverse-inc/packetfence pull request #6171
Opened 2021-03-15 14:35 UTC by jrouzierinverse

Description
===========
Remove inline_accounting table.

NEWS file entries
=======================
Enhancements
-------------
* Remove unused table inline_accounting

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

2021-03-26 10:32 UTC, extrafu commented
@jrouzierinverse rebase  and @nqb / @julsemaan review and merge if fine

2021-03-26 10:57 UTC, nqb requested changes
### Missing files

There is some references to `inline.accounting` inside `pf.conf.defaults` and `documentation.conf`

### Drop of DB table

I see you dropped `inline_accounting` table.
Tell me if I'm wrong but it means that we lost "bandwidth history" for nodes.
I'm not able to see if we lost an old history.

2021-03-26 11:07 UTC, nqb requested changes

2021-03-26 11:07 UTC, nqb commented on db/upgrade-X.X.X-X.Y.Z.sql
> +DROP TABLE `inline_accounting`;
```suggestion
DROP TABLE IF EXISTS `inline_accounting`;
```

2021-03-26 11:24 UTC, julsemaan commented
Other than @nqb's comments, it looks fine to me

2021-03-29 19:44 UTC, extrafu commented
@jrouzierinverse Finish the work on that PR before tackling bugs.

2021-03-30 05:19 UTC, nqb commented
@jrouzierinverse: there is still some references to `inline.accounting` inside `pf.conf.defaults` and `documentation.conf`

2021-03-30 05:54 UTC, nqb commented
@jrouzierinverse, I did the removal for old config settings. Let me know if it's ok.

I just need an answer on "Drop of DB table" topic I mentioned and we should be ready to merge.

2021-04-01 08:35 UTC, nqb commented
Bump @jrouzierinverse

2021-04-02 06:41 UTC, nqb commented
Task `inline_accounting_maintenance` run each minute and mark inactive sessions based on:
- `$accounting_session_timeout` (default value: 300 seconds)
- one day history

Then task update `bandwidth_balance` column value  in `node` table.

There is also some logical related to management of security event.

I didn't see any jobs that cleanup `inline_accounting` table so it means all data will be lost. It should impact only users that extract data from this table for external usage. I will merge this PR as-is and add a note in Upgrade guide.

2021-04-02 06:41 UTC, merged