SCEP Support
inverse-inc/packetfence pull request #6213
Opened 2021-03-23 13:05 UTC by fdurand

# Description
Added support for SCEP.
Added dns/ip in certificate
Added template in certificate profile

# Impacts
pfpki

# Issue
fixes #6022
fixes #6021
fixes #5897
fixes #5896

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## New Features
* pfpki scep support

## Enhancements
* DNS/IP attributes in certificate (pfpki)
* Additional template attributes in certificate profile

## Bug Fixes
* fixes #6022
* fixes #6021
* fixes #5897
* fixes #5896

2021-03-23 15:30 UTC, nqb requested changes
### Coding style

I see a change in naming of functions (i.e. `generatePassword` becomes `GeneratePassword`). 
Is it something we will generate ?

2021-03-23 15:30 UTC, nqb commented on db/upgrade-X.X.X-X.Y.Z.sql
> +\! echo "altering pki_cert"
```suggestion
\! echo "altering pki_certs"
```

2021-03-23 15:30 UTC, nqb commented on go/caddy/pfpki/certutils/certutils.go
> +// load an encrypted private key from disk
Wrong comment

2021-03-23 15:30 UTC, nqb commented on go/caddy/pfpki/pfpki.go
> +	api.Handle("/pki/scep/{id}/", handlers.ManageSCEP(PFPki)).Methods("GET", "POST")
It looks like content is present twice.

2021-03-23 15:30 UTC, nqb commented on go/caddy/pfpki/types/types.go
> +	// Error struct
```suggestion
	// Errors struct
```

2021-03-23 15:30 UTC, nqb commented on html/pfappserver/root/src/views/Configuration/pki/profiles/_components/TheForm.vue
> +          :text="$i18n.t('Optional. This is the url of the OCSP server that will be added in the certificate.If empty then the ca one will be used')"
```suggestion
          :text="$i18n.t('Optional. This is the url of the OCSP server that will be added in the certificate. If empty then the ca one will be used')"
```

2021-03-23 16:00 UTC, fdurand commented
> ### Coding style
> I see a change in naming of functions (i.e. `generatePassword` becomes `GeneratePassword`).
> Is it something we will generate ?

It's because the function needs to be exported, it's why some of them has been changed.

2021-03-24 13:58 UTC, nqb requested changes

2021-03-24 13:58 UTC, nqb commented on html/pfappserver/root/src/views/Configuration/pki/profiles/_components/TheForm.vue
> +          :column-label="$i18n.t('OCSP Url')"
```suggestion
          :column-label="$i18n.t('OCSP URL')"
```

2021-03-24 13:58 UTC, nqb commented on html/pfappserver/root/src/views/Configuration/pki/profiles/_components/TheForm.vue
> +          :text="$i18n.t('Optional. This is the url of the OCSP server that will be added in the certificate. If empty then the ca one will be used')"
```suggestion
          :text="$i18n.t('Optional. This is the URL of the OCSP server that will be added in the certificate. If empty then the ca one will be used')"
```

2021-03-24 14:24 UTC, nqb requested changes
### Inheritance of fields from template

Certs contains fields inherited from template but this inheritance doesn't appear in GUI.
It looks like we don't receive these informations from API when clicking on certificate.

2021-03-24 14:32 UTC, fdurand commented
> ### Inheritance of fields from template
> Certs contains fields inherited from template but this inheritance doesn't appear in GUI.
> It looks like we don't receive these informations from API when clicking on certificate.

It's in the certificate but not in the DB, let me fix that.

2021-03-25 11:11 UTC, nqb requested changes
### scep_allow_renewal

I'm confused with this field.
Based on name, I will expect a boolean value to enable/disable this feature but in GUI, field description is: 
> Number of days before SCEP authorize renewal

2021-03-25 12:28 UTC, fdurand commented
> ### scep_allow_renewal
> I'm confused with this field.
> Based on name, I will expect a boolean value to enable/disable this feature but in GUI, field description is:
> 
> > Number of days before SCEP authorize renewal

In fact it represent the period before the certificate expire to allow the renewal.

2021-03-25 12:53 UTC, nqb commented
> In fact it represent the period before the certificate expire to allow the renewal.

What do you think about a rename to `scep_days_before_renewal` with following description: "Number of days before SCEP authorize renewal" ?

2021-03-25 13:11 UTC, fdurand commented
> > In fact it represent the period before the certificate expire to allow the renewal.
> 
> What do you think about a rename to `scep_days_before_renewal` with following description: "Number of days before SCEP authorize renewal" ?

yep let me change that.

2021-03-26 15:32 UTC, nqb commented
As discussed with @fdurand, I got some issues to get certificate using `sscep`. @fdurand is looking at that.

2021-03-26 16:02 UTC, fdurand commented
> As discussed with @fdurand, I got some issues to get certificate using `sscep`. @fdurand is looking at that.

Just did a test with fresh package:

```
[root@facketfence pf]# sscep getca  -u http://192.168.2.1/scep/intune -c ./ca-prefix -i Inverse -v -d
sscep: starting sscep, version 0.6.1
sscep: new transaction
sscep: transaction id: SSCEP transactionId
sscep: hostname: 192.168.2.1
sscep: directory: scep/intune
sscep: port: 80
sscep: SCEP_OPERATION_GETCA
sscep: requesting CA certificate
sscep: scep msg: GET /scep/intune?operation=GetCACert&message=Inverse HTTP/1.0

sscep: server returned status code 200
sscep: MIME header: application/x-x509-ca-cert
sscep: valid response from server
sscep: MD5 fingerprint: 66:F4:7D:53:31:15:14:7C:E7:B2:7C:8A:C8:6F:7C:B8
sscep: CA certificate written as ./ca-prefix
```

So it looks to work.
As we talked, it looks that it depend of devices , i did it with sscep, iphone, android and all 2 worked.

The only difference is that you are running debian and me centos.
I will try on debian.

2021-03-29 19:04 UTC, fdurand commented
> > As discussed with @fdurand, I got some issues to get certificate using `sscep`. @fdurand is looking at that.
> 
> Just did a test with fresh package:
> 
> ```
> [root@facketfence pf]# sscep getca  -u http://192.168.2.1/scep/intune -c ./ca-prefix -i Inverse -v -d
> sscep: starting sscep, version 0.6.1
> sscep: new transaction
> sscep: transaction id: SSCEP transactionId
> sscep: hostname: 192.168.2.1
> sscep: directory: scep/intune
> sscep: port: 80
> sscep: SCEP_OPERATION_GETCA
> sscep: requesting CA certificate
> sscep: scep msg: GET /scep/intune?operation=GetCACert&message=Inverse HTTP/1.0
> 
> sscep: server returned status code 200
> sscep: MIME header: application/x-x509-ca-cert
> sscep: valid response from server
> sscep: MD5 fingerprint: 66:F4:7D:53:31:15:14:7C:E7:B2:7C:8A:C8:6F:7C:B8
> sscep: CA certificate written as ./ca-prefix
> ```
> 
> So it looks to work.
> As we talked, it looks that it depend of devices , i did it with sscep, iphone, android and all 2 worked.
> 
> The only difference is that you are running debian and me centos.
> I will try on debian.

I am able to replicate on Debian.

2021-03-29 19:10 UTC, fdurand commented
> > > As discussed with @fdurand, I got some issues to get certificate using `sscep`. @fdurand is looking at that.
> > 
> > 
> > Just did a test with fresh package:
> > ```
> > [root@facketfence pf]# sscep getca  -u http://192.168.2.1/scep/intune -c ./ca-prefix -i Inverse -v -d
> > sscep: starting sscep, version 0.6.1
> > sscep: new transaction
> > sscep: transaction id: SSCEP transactionId
> > sscep: hostname: 192.168.2.1
> > sscep: directory: scep/intune
> > sscep: port: 80
> > sscep: SCEP_OPERATION_GETCA
> > sscep: requesting CA certificate
> > sscep: scep msg: GET /scep/intune?operation=GetCACert&message=Inverse HTTP/1.0
> > 
> > sscep: server returned status code 200
> > sscep: MIME header: application/x-x509-ca-cert
> > sscep: valid response from server
> > sscep: MD5 fingerprint: 66:F4:7D:53:31:15:14:7C:E7:B2:7C:8A:C8:6F:7C:B8
> > sscep: CA certificate written as ./ca-prefix
> > ```
> > 
> > 
> > So it looks to work.
> > As we talked, it looks that it depend of devices , i did it with sscep, iphone, android and all 2 worked.
> > The only difference is that you are running debian and me centos.
> > I will try on debian.
> 
> I am able to replicate on Debian.

Tried with the latest code of sscep ( https://github.com/certnanny/sscep ) and it works like a charm.
Let me try to package it and include as a dependencie in this PR.

2021-03-30 11:53 UTC, nqb commented
Using new `sscep` package on Debian, I'm able to get a certificate based on a CSR generated locally on my PacketFence server running Debian. My CSR contains a SCEP challenge password which was defined in my PKI profile.

Resulting certificate contains key usage and extended key usage defined in my PKI profile but OCSP URL is missing.

2021-03-31 14:00 UTC, nqb commented
> Resulting certificate contains key usage and extended key usage defined in my PKI profile but OCSP URL is missing.

As discussed with @fdurand, OCSP URL should be defined in CSR.
It seems that EKU and KU are taken from PKI profile but it looks like they could be defined in CSR too.
SCEP is only used to sign.

2021-04-01 20:30 UTC, merged