Permit to send the deauth request on the previous equipment.
inverse-inc/packetfence pull request #6215
Opened 2021-03-23 17:11 UTC by fdurand

# Description
Send the deauth request to the previous switch the device was connected.
In the case you have 2 equipment, one AP and a dhcp that trigger a radius request and you want the deauth request to be sent only on the dhcp equipment. 

# Impacts
Deauth

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries

## Enhancements
* Deauth request can be made on the previous equipment the device was connected.

2021-09-29 17:13 UTC, julsemaan commented
IMO this can get in for 11.1 but we need the form+admin to be rebased and adjusted

2021-10-05 13:40 UTC, extrafu commented
@fdurand Please rebase and @satkunas review the UI code.

2021-10-05 13:53 UTC, fdurand commented
rebase done

2021-10-05 13:58 UTC, satkunas commented
UI code is OK to merge

2021-10-05 14:05 UTC, julsemaan requested changes

2021-10-05 14:05 UTC, julsemaan commented on html/pfappserver/lib/pfappserver/Form/Config/Switch.pm
> +   label => 'Deauth On previous switch',
Remove the label and help from here

2021-10-05 14:05 UTC, julsemaan commented on html/pfappserver/root/src/views/Configuration/switchGroups/_components/TheForm.vue
> +          :text="$i18n.t('This option parameter will allow you to do the deauthentication/CoA on the previous switch the device connected.')"
```suggestion
          :text="$i18n.t('This option parameter will allow you to do the deauthentication/CoA on the previous switch where the device was connected.')"
```

2021-10-05 14:05 UTC, julsemaan commented on html/pfappserver/root/src/views/Configuration/switches/_components/TheForm.vue
> +          :text="$i18n.t('This option parameter will allow you to do the deauthentication/CoA on the previous switch the device connected.')"
```suggestion
          :text="$i18n.t('This option parameter will allow you to do the deauthentication/CoA on the previous switch whre the device was connected.')"
```

2021-10-06 12:31 UTC, fdurand commented
BUMP

2021-10-06 13:47 UTC, merged