feature/netflow-module-disable-enable
inverse-inc/packetfence pull request #6336
Opened 2021-04-30 01:45 UTC by jrouzierinverse

Description
===========
Allow the netflow kernel module to be disabled

Impacts
=======
pfacct netflow

Enhancements
-------------
* Allow the netflow kernel module to be disabled

Issue
=====
fixes #6214

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

2021-06-30 14:10 UTC, nqb commented
@satkunas, could you take a quick look on this PR to be sure everything is OK on GUI part ?

2021-06-30 14:40 UTC, satkunas commented
@nqb it looks good

2021-07-01 07:00 UTC, nqb requested changes
Webadmin part works as expected.

However, when I set `netflow_kernel_module=disabled` and restart `pfacct`, I see following lines in logs:

```
Jul 01 08:32:17 packetfence systemd[1]: Starting PacketFence GO Accounting Server Daemon...
Jul 01 08:32:19 packetfence packetfence[1469]: pfcmd.pl(1469) INFO: netflow is disabled or the netflow kernel module is disabled (pf::cmd::pf::confignetflow::_run)
Jul 01 08:32:19 packetfence pfacct[1581]: t=2021-07-01T08:32:19+0000 lvl=info msg="File descriptor limit is: 4096" pid=1581
Jul 01 08:32:19 packetfence pfacct[1581]: t=2021-07-01T08:32:19+0000 lvl=info msg="Starting listening to netflow at '127.0.0.1:2056'" pid=1581
Jul 01 08:32:19 packetfence systemd[1]: Started PacketFence GO Accounting Server Daemon.
```

=> Kernel module is still loaded and `pfacct` is still listening on udp/2056. I try to restart a second time and to reboot without any effect.

2021-07-15 13:35 UTC, nqb commented
@jrouzierinverse, could you provide a feedback on this PR ?

2021-07-15 13:42 UTC, jrouzierinverse commented
The expected results is the kernel module not loaded but pfacct is still listening to netflow traffic.
Was the kernel module still loaded after the reboot.

2021-07-15 13:45 UTC, nqb commented
>Was the kernel module still loaded after the reboot.

Yes, I described in my previous comment. Even after a reboot, kernel module is still loaded.

2021-09-29 17:15 UTC, julsemaan commented
@nqb and @jrouzierinverse, what prevents this from being merged?

2021-09-29 17:39 UTC, jrouzierinverse commented
@nqb identified an issue with this where the module was still loaded.
I did not verify that issue yet.

2022-07-25 19:11 UTC, fdurand commented
Isn´t it because even if $Config{advanced}{netflow_kernel_module} is disabled and netflow_enabled is enabled , we add the iptables rule "-I FORWARD -j NETFLOW" that load the kernel module ?

2022-07-26 16:28 UTC, fdurand commented
@jrouzierinverse , @extrafu  Just a concern, if iptables is using it and you want to disable it then you have to regenerate the iptables rules before using the command pfcmd confignetflow.
If you want to use it then you need to use the command pfcmd confignetflow then regenerate the iptables rules.

So there is no easy way to add it in the iptables systemd script, this have to be done manually.

2022-07-27 17:51 UTC, extrafu commented
@fdurand Could we clearly document this somewhere or throw a warning when we toy-around  "pfcmd service iptables" ?

2026-02-04 17:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/inverse-inc/packetfence?pullRequest=6336) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/inverse-inc/packetfence?pullRequest=6336) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: jrouzierinverse<br/>:x: fdurand<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/inverse-inc/packetfence?pullRequest=6336) it.</sub>

2026-03-26 17:17 UTC, closed without merging