Macro documentation in filter engine
inverse-inc/packetfence pull request #6392
Opened 2021-06-09 18:56 UTC by fdurand

# Description
Extra documentation to use the macro in the filter engine

# Impacts
More documentation

# Delete branch after merge
YES

# NEWS file entries

## Enhancements
* Macro documentation for filter engine

2021-06-30 13:28 UTC, nqb requested changes
- You don't need to add extra "===" after a title, only before

2021-06-30 13:28 UTC, nqb commented on docs/installation/advanced_access_configuration.asciidoc
> +This macro will return an substring
```suggestion
This macro will return a substring
```

2021-06-30 13:28 UTC, nqb commented on docs/installation/advanced_access_configuration.asciidoc
> +This macro will return the EUI48 format of a mac address
```suggestion
This macro will return the EUI48 format of a MAC address
```

2021-06-30 13:28 UTC, nqb commented on docs/installation/advanced_access_configuration.asciidoc
> +will assign to PacketFence-UserName the EUI48 mac address
```suggestion
will assign to PacketFence-UserName the EUI48 MAC address
```

2021-06-30 13:28 UTC, nqb commented on docs/installation/advanced_access_configuration.asciidoc
> +will assign a number between 10620 and 12600 to Session-Timeout
```suggestion
will assign a random number between 10620 and 12600 to Session-Timeout
```

2021-06-30 13:28 UTC, nqb commented on docs/installation/advanced_access_configuration.asciidoc
> +will log the value of the radius request attribute User-Name and logged
```suggestion
will log the value of the RADIUS request attribute User-Name and logged
```

2021-06-30 13:28 UTC, nqb commented on docs/installation/advanced_access_configuration.asciidoc
> +This macro will apply a regex on the attribute value to be able able to build anither value
```suggestion
This macro will apply a regular expression on the attribute value to be able able to build another value
```

2021-06-30 14:17 UTC, nqb requested changes

2021-06-30 14:17 UTC, nqb commented on docs/installation/advanced_access_configuration.asciidoc
> + TLS-Client-Cert-Common-Name = "zammit@packetfence.org" -> TLS-Stripped-UserName = zammit
```suggestion
 TLS-Client-Cert-Common-Name = "zammit@packetfence.org" -> TLS-Stripped-UserName = "zammit"
```

2021-07-05 15:00 UTC, fdurand commented
BUMP

2021-07-06 05:34 UTC, nqb approved these changes

2021-07-06 05:34 UTC, merged