fix/6326
inverse-inc/packetfence pull request #6465
Opened 2021-08-02 13:56 UTC by jrouzierinverse

# Description

Normalize connection_sub_type to use the numeric value.

# Impacts
Radius filters

# Issue
fixes #6326

# Delete branch after merge
NO

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries

## Bug Fixes
* Normalize connection_sub_type to use the numeric value (#6326)

2021-08-03 10:20 UTC, nqb requested changes
Few remarks but fix work as expected.

I got following content in my `radius_filters.conf`:

```
[test_bugfix]
description=test_bugfix
status=enabled
condition=connection_type == "Wireless-802.11-EAP" && connection_sub_type == "EAP-TLS"
merge_answer=no
answer.0=request:Reply-Message = test_bugfix
```

and I can see that my RADIUS request is matched by this filter without changing `connection_sub_type`.

2021-08-03 10:20 UTC, nqb commented on lib/pf/factory/condition.pm
> +sub normalize_eap_type {
This function doesn't seem to be used.

2021-08-03 10:20 UTC, nqb commented on lib/pf/config/builder/filter_engine.pm
> +sub rewriteConditions {
Is this function really necessary ?

In my understanding, this function returns what it received.

2021-08-06 05:49 UTC, nqb commented
No more changes to come @jrouzierinverse (see my second comment) ?

2021-08-06 19:07 UTC, jrouzierinverse commented on lib/pf/factory/condition.pm
> +sub normalize_eap_type {
This is for a future feature #6485

2021-08-10 09:10 UTC, merged