fix/4987
inverse-inc/packetfence pull request #6527
Opened 2021-08-19 17:21 UTC by jrouzierinverse

- Only trigger the node discover security event in the context of radius and pfdhcplistener.
- Refactor node discover triggering to it's own function
- Add test for triggering node discovered

# Description
(REQUIRED)
Describe what the new code is used for.
ie: Allow PacketFence to trigger the coffee machine on wireless EAP 802.1X connection to brew a fresh espresso.

# Impacts
(REQUIRED)
Describe what to reviewer should look at. Will also help for testing purposes.
ie: - RADIUS authorize workflow

# Code / PR Dependencies
(OPTIONAL. REMOVE IF NOT NEEDED)
List the PRs or other factors on which this PR depends

# NEW Package(s) required
(OPTIONAL. REMOVE IF NOT NEEDED)
Which new package(s) (all supported distributions) are required for this PR to work.

# Issue
(OPTIONAL. REMOVE IF NOT NEEDED)
The following syntax 'fixes #ISSUE_NUMBER' will automatically closes a Github issue on pull-request merge time.
Modify the ISSUE_NUMBER in order to reflect the Github issue that need to be closed
fixes #ISSUE_NUMBER

# Delete branch after merge
(REQUIRED)
YES | NO

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
(REQUIRED, but may be optional...)
## New Features
* Feature 1
* Feature 2

## Enhancements
* Enhancement 1
* Enhancement 2

## Bug Fixes
If an issue exists on Github, please refer to it (name) along with it's number...
* Issue with Zammitbug in sandwich context (#42)
* Issue with Zammitbug in dinde context (#43)

# UPGRADE file entries
(OPTIONAL, but may be required...)

2022-03-31 06:10 UTC, nqb commented
@jrouzierinverse, after a rebase, can I consider this PR ready for test ?

I will certainly need it soon for a customer deployment. 

Thanks.

2022-03-31 10:37 UTC, jrouzierinverse commented
Yes

2022-03-31 10:44 UTC, jrouzierinverse commented
Done

2022-04-01 06:05 UTC, nqb requested changes
Except my note on accounting, it works as expected on RADIUS and DHCP.

No security event is triggered when creating node through web admin.

2022-04-01 06:05 UTC, nqb commented on lib/pf/radius.pm
> +    local $pf::dal::node::TRIGGER_NODE_DISCOVERED = 1;
I don't think it's necessary here because sending an accounting request for a node which doesn't exist will not create the node in PacketFence DB.

2022-04-25 07:18 UTC, nqb commented
@jrouzierinverse, could you look at my comment ? Thanks.

2022-04-25 14:05 UTC, jrouzierinverse commented on lib/pf/radius.pm
> +    local $pf::dal::node::TRIGGER_NODE_DISCOVERED = 1;
You are right I removed it

2022-04-26 05:23 UTC, merged