Feature/admin cert san
inverse-inc/packetfence pull request #6714
Opened 2021-11-23 13:42 UTC by julsemaan

# Description
Add support for SAN in the certificates section

# Impacts
Certificates display and new CSRs that will be issued via the admin interface

# NEW Package(s) required
A new version of packetfence-perl must be built with Crypt-OpenSSL-X509-1.910.tar.gz

# Issue
fixes #6689 

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [N/A] Document the feature
- [X] Add unit tests
- [N/A] Add acceptance tests (TestLink)

# NEWS file entries
(REQUIRED, but may be optional...)
## New Features
* Feature 1
* Feature 2

## Enhancements
* Certificate signing requests created via the admin interface now include a Subject Alternative Name (SAN)
* The Subject Alternative Names of a certificate are now displayed in the admin interface

2021-11-23 13:43 UTC, julsemaan commented
I just need a bit of frontend magic from @satkunas to display the SAN cleanly instead of displaying as an array

Currently displays as:
![image](https://user-images.githubusercontent.com/3857942/143035090-9a255d85-5acf-4d30-98cf-0dcf07103f28.png)

But there is certainly a cleaner way to display these

2021-12-15 14:12 UTC, nqb reviewed
@julsemaan, do you remember why we need to upgrade Crypt::OpenSSL::X509 Perl module ?

I don't see any specific notes in [Changelog](https://github.com/dsully/perl-crypt-openssl-x509/blob/master/Changes).

2021-12-15 14:14 UTC, nqb requested changes
Looks like display is not correct in Certification Authority Certificates field (only):

![image](https://user-images.githubusercontent.com/10830260/146202232-212b25b6-4e86-448d-9299-104555540793.png)


@satkunas, could you take a look ?

2021-12-15 14:18 UTC, nqb reviewed
In the code, I can see that we copied Common Name into SAN (`DNS`).

I think it's a good idea as a default behavior. Later, we could let users define their own extended attributes.

2021-12-15 15:34 UTC, julsemaan commented
> @julsemaan, do you remember why we need to upgrade Crypt::OpenSSL::X509 Perl module ?
> 
> I don't see any specific notes in [Changelog](https://github.com/dsully/perl-crypt-openssl-x509/blob/master/Changes).

Because to_string isn't implemented in the current version for extensions

2022-01-31 07:01 UTC, nqb commented
@satkunas, I will need a fix on https://github.com/inverse-inc/packetfence/pull/6714#pullrequestreview-832872045 if we want to have this PR merged before feature freeze.

2022-01-31 15:17 UTC, nqb commented
Works as expected, I will update `packetfence-perl` to include new dependency.

2022-01-31 15:17 UTC, merged

2022-02-08 07:38 UTC, nqb commented
Crypt::OpenSSL::X509 should be part of `packetfence-perl` 1.2.0