explicitely support APs defined by CIDR/IP for Unifi web-auth
inverse-inc/packetfence pull request #6717
Opened 2021-11-24 19:23 UTC by julsemaan

# Description
explicitely support APs defined by CIDR/IP for Unifi web-auth

# Impacts
Ubiquiti Unifi module

# Issue
fixes #6686 

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [N/A] Document the feature
- [N/A] Add unit tests
- [N/A] Add acceptance tests (TestLink)

# NEWS file entries
## Bug Fixes
* Fix regression in the Unifi module for deauthentication of webauth clients when the APs are defined using an IP or CIDR in the configuration (#6686)
*

2021-11-24 19:24 UTC, julsemaan commented
I've marked this as a +1 since it doesn't alter the behavior that was released in 11.1, it just adds another behavior that is opinionated on APs defined using IP or CIDR

2021-11-29 07:22 UTC, nqb requested changes
Thanks for your detailled comments.

IMHO, it's a problem to have different behavior depending on how AP are declared into PacketFence configuration. 

If I correctly understand your code, in a case where AP are declared by IP addresses in PacketFence configuration and MAC address of device is not found on a Unifi site, we don't deauthenticate. However, in such scenario for AP declared by MAC addresses, we deauthenticate on all sites.

2021-11-29 07:22 UTC, nqb commented on lib/pf/Switch/Ubiquiti/Unifi.pm
>      $logger->info("Switched status on the Unifi controller using command $command");
This sentence could be wrong if your device has not been found and your access points are defined by AP in PacketFence config.

2021-11-29 12:34 UTC, julsemaan commented
> Thanks for your detailled comments.
> 
> IMHO, it's a problem to have different behavior depending on how AP are declared into PacketFence configuration.
> 
> If I correctly understand your code, in a case where AP are declared by IP addresses in PacketFence configuration and MAC address of device is not found on a Unifi site, we don't deauthenticate. However, in such scenario for AP declared by MAC addresses, we deauthenticate on all sites.

That is correct, we could make it so we send it to all sites if we don't find the device but from what I could see this wouldn't be necessary on the recent Unifi versions since we're sure to find it if its authorized or connected. This means when granting access we'll find it (since the user is connected and on the portal), and when we're revoking access, the entry should be found in a site since its currently authorized.

My understanding is that the block to deauth on all sites would be targetted at old Unifi versions but its hard to tell at the moment. We could always add the block to deauth on all sites for IP/CIDR APs, it won't cost more than me taking the time to do a copy/paste.

2021-11-29 13:09 UTC, nqb commented
> My understanding is that the block to deauth on all sites would be targetted at old Unifi versions but its hard to tell at the moment. We could always add the block to deauth on all sites for IP/CIDR APs, it won't cost more than me taking the time to do a copy/paste.

I agree.

2021-12-24 10:31 UTC, nqb commented
@julsemaan, let me know if you plan to adjust this PR.

2021-12-30 19:19 UTC, julsemaan commented
PR adjusted

2022-01-19 08:52 UTC, nqb commented on lib/pf/Switch/Ubiquiti/Unifi.pm
>      $logger->info("Switched status on the Unifi controller using command $command");
This is still a problem for me.

2022-01-19 08:57 UTC, nqb commented on lib/pf/Switch/Ubiquiti/Unifi.pm
>      $logger->info("Switched status on the Unifi controller using command $command");
I misunderstand logic. In fact, this sentence will never appear in logs if AP are defined by IP addresses.

2022-01-19 08:58 UTC, merged