Fixes #6147
inverse-inc/packetfence pull request #6761
Opened 2021-12-09 15:39 UTC by fdurand

# Description
Exclude CA cert from isSelfSigned

# Impacts
Secure redirect

# Issue
fixes #6147

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries

## Bug Fixes
* HTTPS redirection broken if Root CA is a self-signed (#6147)

2021-12-09 16:03 UTC, julsemaan commented on lib/pfconfig/namespaces/config/Pf.pm
> +/
Not sure this slash belongs in here

2021-12-09 18:23 UTC, jrouzierinverse requested changes

2021-12-09 18:23 UTC, jrouzierinverse commented on lib/pfconfig/namespaces/config/Pf.pm
> +                $ca = $TRUE if ( ( $oid eq '2.5.29.19' ) && ( $ext->to_string() ~= /CA:TRUE/i ) );
change ```~=``` to ```=~```

2021-12-13 14:38 UTC, jrouzierinverse requested changes

2021-12-13 14:38 UTC, jrouzierinverse commented on lib/pfconfig/namespaces/config/Pf.pm
> +                $ca = $TRUE if ( ( $oid eq '2.5.29.19' ) && ( $ext->to_string() =~ /CA:TRUE/i ) );
No need to loop just look up the ext by the oid.
```perl
my $ext = $$exts{'2.5.29.19'};
$ca = $TRUE if defined $ext && $ext->to_string() =~ /CA:TRUE/i;
```

2022-01-13 19:52 UTC, fdurand commented
BUMP

2022-01-31 13:32 UTC, extrafu commented
@jrouzierinverse If all good, merge to get it out of our way for the v11.2 release.

2022-02-01 12:34 UTC, extrafu commented
Bump again, until noon or moving out of 11.2

2022-02-01 12:37 UTC, merged