Fix/6766
inverse-inc/packetfence pull request #6773
Opened 2021-12-14 15:47 UTC by fdurand

# Description
Added a way to defined the tls min and max version in the tls profil

# Impacts
Eap configuration

# Issue
fixes #6766

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries

## Bug Fixes
* TLS 1.0 is disabled in FreeRADIUS configuration starting from PacketFence v11 (#6766)

2021-12-15 09:33 UTC, nqb commented on conf/radiusd/tls.conf.defaults
> +tls_min_version = 1.0
I suggest to stay with TLS 1.2 as `tls_min_version` like you proposed on #5808. Users who want to keep TLS 1.0 need to changed it here.

2021-12-15 09:33 UTC, nqb commented on conf/radiusd/tls.conf.defaults
> +tls_min_version = 1.0
I suggest to stay with TLS 1.2 as `tls_min_version` like you proposed on #5808. Users who want to keep TLS 1.0 need to changed it here.

2021-12-15 09:50 UTC, nqb commented on html/pfappserver/lib/pfappserver/Form/Config/Radiusd/TLSProfile.pm
> +    return map { { value => $_, label => $_ } } qw(1.0 1.1 1.2 1.3);
- Is it possible to have values defined in another place ? Below, I saw that we take values from ConfigStore.
- I read some things about TLS 1.3, are we sure it makes sense to enable it ?

2021-12-15 09:51 UTC, nqb requested changes
IMHO, we should also add notes in upgrade guide:
* TLS 1.0 and TLS 1.1 are disabled by default
* How to change default behavior 

I can take care of that.

2021-12-15 14:41 UTC, fdurand commented on html/pfappserver/lib/pfappserver/Form/Config/Radiusd/TLSProfile.pm
> +    return map { { value => $_, label => $_ } } qw(1.0 1.1 1.2 1.3);
I use constant to define the version now.
It´s a supported option in freeradius so it´s why i added it. (1.3)

2021-12-15 15:55 UTC, nqb commented
I need to write upgrade note.

2021-12-24 10:07 UTC, merged

2021-12-24 10:30 UTC, nqb commented
I will backport to maintenance in January.