Hide download and email if the certificate has been signed by scep request
inverse-inc/packetfence pull request #6778
Opened 2021-12-15 19:25 UTC by fdurand

# Description
Hide download and email if the certificate has been signed by scep request

# Impacts
PKI

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries

## Enhancements
* Hide download and email for a certificate that has been signed by a scep request

2021-12-19 07:31 UTC, nqb requested changes

2021-12-19 07:31 UTC, nqb commented on go/caddy/pfpki/models/models.go
> +	if err := c.DB.Create(&Cert{Cn: cn, Ca: ca, CaName: ca.Cn, ProfileName: profiledb[0].Name, SerialNumber: crt.SerialNumber.String(), Mail: attributeMap["emailAddress"], StreetAddress: attributeMap["s
Can we find another name for this variable :-) ?

2021-12-30 08:14 UTC, nqb requested changes
1. Do we really want to prevent download of SCEP certificates from web admin ?

IMHO, we should allow admin users to download SCEP certificates from web admin because web admin doesn't display all informations of certificates (OCSP URL, key usage, etc.) and if you need these informations, you will have to look into DB.

Certificates generated through SCEP are stored in DB without private keys so it's not a problem. Perhaps we can have a "Copy Certificate" button like we have for CA certificates.

2. Download button is still available when you click on a SCEP certificate

2022-01-13 20:47 UTC, fdurand commented
Just added a way to download the public key.
Also you need to recompile the pki in order to have the Download button removed from the admin gui.

2022-01-14 10:50 UTC, nqb requested changes
- Existing SCEP certs will have a wrong value of `scep` field in DB. We need to update existing SCEP certs if we are able to distinguish them but I'm not sure it's possible.

2022-01-17 13:03 UTC, nqb commented
> * Existing SCEP certs will have a wrong value of `scep` field in DB. We need to update existing SCEP certs if we are able to distinguish them but I'm not sure it's possible.

I don't see an automated way to identify SCEP certificate in DB before.

2022-01-18 09:03 UTC, nqb commented
Just did new tests:
1. Download button is still available for SCEP certificates when you click on a SCEP certificate (not on the listing, only "Copy certificate")
1. SCEP filter doesn't work:
![image](https://user-images.githubusercontent.com/10830260/149904693-34d73664-3ce2-4031-be49-9dbda6e938d5.png)

=> I expect to be able to select SCEP

@satkunas, could you take a look ?

2022-01-19 14:21 UTC, satkunas commented
> Just did new tests:
> 
> 1. Download button is still available for SCEP certificates when you click on a SCEP certificate (not on the listing, only "Copy certificate")
> 2. SCEP filter doesn't work:
>    ![image](https://user-images.githubusercontent.com/10830260/149904693-34d73664-3ce2-4031-be49-9dbda6e938d5.png)
> 
> => I expect to be able to select SCEP
> 
> @satkunas, could you take a look ?

@nqb the `scep` column has been pinned to ensure that the scep column is returned with each item in order to show/hide the download/email buttons. If this column is not showing up you'll need to clear your `pkiCerts::defaultSearch` preference.

2022-01-19 21:04 UTC, nqb requested changes

2022-01-19 21:04 UTC, nqb commented on db/upgrade-X.X-X.Y.sql
> +UPDATE TABLE pki_certs
```suggestion
UPDATE pki_certs
```

2022-01-19 21:24 UTC, nqb commented
Work as expected after I remove my preferences and clean my web browser cache.

2022-01-19 21:24 UTC, merged