Test suite Feature/venom cli login tests
inverse-inc/packetfence pull request #6783
Opened 2021-12-17 05:35 UTC by JeGoi

# Description
Cover test for cli radius test

# Impacts
Venom tests

# Delete branch after merge
YES

2021-12-18 08:03 UTC, nqb requested changes
Some general notes:
1. We are not testing CLI login for Read and Write access, only Write access
1. We are not testing CLI login against a real switch but using `radclient` on a default switch already created
1. There is no connection profile created to match on `CLI-Access`  
1. We don't validate that a user in local DB can authenticate on the switch. Could be easy to do using a connection profile with an admin account and a local source
1. Could you remove useless JSON payload when it's not necessary ?

2021-12-18 08:03 UTC, nqb commented on t/venom/lib/delete_file.yml
> +      - result.exitcode ShouldEqual 0
You can remove this assertion because it's implicit. If you want to keep it, according to https://github.com/ovh/venom/tree/master/executors/exec, `exitcode` is not a value usable.

2021-12-18 08:03 UTC, nqb commented on t/venom/lib/delete_source.yml
> +    url: '{{.pfserver_webadmin_url}}/api/v1/node/{{.input.id}}'
API URL is wrong

2021-12-18 08:03 UTC, nqb commented on t/venom/lib/delete_switch.yml
> +  # delete source
```suggestion
  # delete switch
```

2021-12-18 08:03 UTC, nqb commented on t/venom/lib/delete_switch.yml
> +  # check source deleted
```suggestion
  # check switch deleted
```

2021-12-18 08:03 UTC, nqb commented on t/venom/lib/restart_radius_services.yml
> +executor: restart_radius_services
IMHO, we should create a `restart_pf_service` executor with one arg equals to name of a `pf` service

2021-12-18 08:03 UTC, nqb commented on t/venom/lib/restart_radius_services.yml
> +      "Authorization": "{{.result.token}}"
If I'm not wrong, it will only work when #6775 is merged.

2021-12-18 08:03 UTC, nqb commented on t/venom/lib/systemctl_service.yml
> +      - result.systemout ShouldContainSubstring ""
I think you can remove this assertion (default assertion is enough)

2021-12-18 08:03 UTC, nqb commented on t/venom/scenarios/cli_login/playbooks/configure.yml
> +  name: configure Golang environment for unit tests
Title is wrong.

2021-12-18 08:03 UTC, nqb commented on t/venom/scenarios/cli_login/playbooks/configure.yml
> +#      tags: go
Can be removed.

2021-12-18 08:03 UTC, nqb commented on t/venom/scenarios/cli_login/playbooks/configure.yml
> +  - name: Authorization in radb
```suggestion
  - name: Authorization in raddb
```

2021-12-18 08:03 UTC, nqb commented on t/venom/test_suites/cli-login-radius/00_create_admin_roles.yml
> +name: Create and test Radius machine source
Titles of files, test suite and test case don't match action: create **one** admin role for WRITE access on switch

2021-12-18 08:03 UTC, nqb commented on t/venom/test_suites/cli-login-radius/05_create_radius_machine_source.yml
> +name: Create and test Radius machine source
I'm not sure to understand the title here:
- There is no "test" of the source
- I don't understand why you speak about "machine"

2021-12-18 08:03 UTC, nqb commented on t/venom/test_suites/cli-login-radius/10_create_switch.yml
> +name: Create and test Radius machine source
Titles of test suite and test case don't match action.

2021-12-18 08:03 UTC, nqb commented on t/venom/test_suites/cli-login-radius/10_create_switch.yml
> +    url: '{{.pfserver_webadmin_url}}/api/v1/config/switch/192.168.0.1'
IP should be in `vars/all.yml`

2021-12-18 08:03 UTC, nqb commented on t/venom/lib/systemctl_service.yml
> +  unit_commands: {}
`unit_command` ?

I don't think we can pass several unit command at the same time.

2021-12-18 08:03 UTC, nqb commented on t/venom/test_suites/cli-login-radius/20_start_services.yml
> +    service: packetfence-pfcron
`pfcron` should have been already started at end of configurator. Why it's necessary to start it ?

2021-12-18 08:03 UTC, nqb commented on t/venom/test_suites/cli-login-radius/20_start_services.yml
> +    unit_commands: start
I think you want to restart services because they have been already started at end of configurator.

2021-12-18 08:03 UTC, nqb commented on t/venom/test_suites/cli-login-radius/teardown/00_clean_pf_config.yml
> +    url: '{{.pfserver_webadmin_url}}/api/v1/config/switch/192.168.0.1'
IP need to be in variable

2021-12-18 08:03 UTC, nqb commented on t/venom/test_suites/cli-login-radius/10_create_switch.yml
> +name: Create and test Radius machine source
In fact, also you don't create a switch, you only modify an existing switch.

2021-12-18 08:03 UTC, nqb commented on t/venom/test_suites/cli-login-radius/teardown/05_stop_service.yml
> +    service: ""
Really necessary ?

2021-12-18 08:03 UTC, nqb commented on t/venom/test_suites/cli-login-radius/teardown/90_teardown.yml
> +name: Teardown
I don't think that file is necessary here because there is no changes to default REALMS and no domain created.

2021-12-19 06:19 UTC, nqb reviewed
At the moment, `cli_login` test suite doesn't require other VM than `pf` VM so it could be part of `unit_tests` scenario to speed tests.

However, at some point, we may want to test CLI login with an AD source so in that case, we will have to boot `ad` VM and certainly create a dedicated scenario.

2021-12-19 07:17 UTC, nqb reviewed
Another suggestion (for a next iteration): create a dedicated role to configure local RADIUS server on PacketFence to simplify reutilization

2021-12-20 15:45 UTC, JeGoi commented on t/venom/lib/restart_radius_services.yml
> +      "Authorization": "{{.result.token}}"
Correct!

2021-12-20 15:52 UTC, JeGoi commented on t/venom/lib/delete_file.yml
> +      - result.exitcode ShouldEqual 0
Ok. Changed to result.code

2021-12-20 15:55 UTC, JeGoi commented on t/venom/lib/delete_source.yml
> +    url: '{{.pfserver_webadmin_url}}/api/v1/node/{{.input.id}}'
Fixed

2021-12-20 15:58 UTC, JeGoi commented on t/venom/lib/restart_radius_services.yml
> +executor: restart_radius_services
Well, in fact I did it in the venom-v1.0.0 branch.
Need to be fixed when merged.

2021-12-20 15:59 UTC, JeGoi commented on t/venom/lib/systemctl_service.yml
> +  unit_commands: {}
Correct. Done

2021-12-20 16:01 UTC, JeGoi commented on t/venom/lib/systemctl_service.yml
> +      - result.systemout ShouldContainSubstring ""
Hum, I add this one because I was not sure...  I will comment it until it is working

2021-12-20 16:03 UTC, JeGoi commented on t/venom/scenarios/cli_login/playbooks/configure.yml
> +#      tags: go
Done

2021-12-20 16:03 UTC, JeGoi commented on t/venom/scenarios/cli_login/playbooks/configure.yml
> +  name: configure Golang environment for unit tests
Thks Done

2021-12-20 16:04 UTC, JeGoi commented on t/venom/scenarios/cli_login/playbooks/configure.yml
> +  - name: Authorization in radb
Done

2021-12-20 16:49 UTC, JeGoi commented on t/venom/test_suites/cli-login-radius/10_create_switch.yml
> +    url: '{{.pfserver_webadmin_url}}/api/v1/config/switch/192.168.0.1'
Hum, it is the default switch on PF.
But you are right, it should be moved as variable.

2021-12-20 16:51 UTC, JeGoi commented on t/venom/test_suites/cli-login-radius/00_create_admin_roles.yml
> +name: Create and test Radius machine source
Fixed

2021-12-20 16:53 UTC, JeGoi commented on t/venom/test_suites/cli-login-radius/05_create_radius_machine_source.yml
> +name: Create and test Radius machine source
Thanks Fixed

2021-12-20 16:57 UTC, JeGoi commented on t/venom/test_suites/cli-login-radius/10_create_switch.yml
> +name: Create and test Radius machine source
Fixed

2021-12-20 17:00 UTC, JeGoi commented on t/venom/test_suites/cli-login-radius/20_start_services.yml
> +    service: packetfence-pfcron
Yes it should. I don't remember why I restart it there.
It will removed.
Thanks

2021-12-20 17:00 UTC, JeGoi commented on t/venom/test_suites/cli-login-radius/20_start_services.yml
> +    unit_commands: start
Same as before.

2021-12-20 17:02 UTC, JeGoi commented on t/venom/test_suites/cli-login-radius/teardown/00_clean_pf_config.yml
> +    url: '{{.pfserver_webadmin_url}}/api/v1/config/switch/192.168.0.1'
Done

2021-12-20 17:05 UTC, JeGoi commented on t/venom/test_suites/cli-login-radius/teardown/90_teardown.yml
> +name: Teardown
Done

2021-12-20 17:23 UTC, JeGoi commented on t/venom/lib/delete_switch.yml
> +  # check source deleted
Fixed

2021-12-23 12:29 UTC, JeGoi commented on t/venom/test_suites/cli-login-radius/teardown/05_stop_service.yml
> +    service: ""
Prefer to do it since clean and removed services/files before.

2021-12-23 14:03 UTC, nqb commented
Pipeline to test: https://gitlab.com/inverse-inc/packetfence/-/pipelines/435898927

2021-12-23 20:44 UTC, JeGoi commented
Hum, it fails but not on the configurator, not the test itself

2021-12-24 10:10 UTC, nqb commented
I tested locally two scenarios and they work as expected.

2021-12-24 10:10 UTC, merged