Venom: Firewall SSO
inverse-inc/packetfence pull request #6822
Opened 2022-01-12 19:29 UTC by satkunas

# Description
Implement Firewall SSO Venom test suite

# Impacts
Extends `dot1x_eap_peap` scenario

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
(REQUIRED, but may be optional...)
## New Features
* Feature 1
* Feature 2

2022-01-12 19:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/inverse-inc/packetfence?pullRequest=6822) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/inverse-inc/packetfence?pullRequest=6822) before we can accept your contribution.<br/><hr/>**dsatkunas** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/inverse-inc/packetfence?pullRequest=6822) it.</sub>

2022-01-13 08:19 UTC, nqb requested changes

2022-01-13 08:19 UTC, nqb commented on t/venom/scenarios/dot1x_eap_peap/playbooks/configure.yml
> +        name: yq
```suggestion
        name: yq
        state: present
```

2022-01-13 08:19 UTC, nqb commented on t/venom/test_suites/wired_dot1x_eap_peap_firewall_sso_https/03_create_http_smocker.yml
> +          from: result.systemout
can be removed

2022-01-27 13:25 UTC, nqb commented
@satkunas and @julsemaan identified a limitation to run firewall SSO tests sequentially inside `wired_dot1x_eap_peap` scenario.

All tests use one node ( `node01`) and expect `node01` to have new IP address on production VLAN (192.168.121.0/24) between each tests in order to trigger correctly SSO workflow.

Currently, `node01` continues to use same IP address between each tests even after:
- forcing a DHCP release on `node01` 
- forcing a ifdown/ifup on `switch01`

I think this behavior is caused by `libvirt` DHCP server which assigned IP address for one hour by default and just reassign this IP address each time. This lease time is also a problem when a device go on production VLAN and we want to move it to another VLAN: node doesn't try to get a new IP address because lease is still valid.

A possible solution could be to create a another production network (similar to 192.168.121.0/24) with a DHCP server provided by a Vagrant VM (like `linux02`). Another solution could be to use a different node for each test.

2022-01-27 13:31 UTC, nqb commented
@julsemaan and @satkunas, I forgot to ask the basics: why do we need a new IP address on node01 ? Is it because we have an existing ip4log entry ? Would it work as-is if we clean ip4log during teardown ?

2022-01-27 13:37 UTC, julsemaan commented
> @julsemaan and @satkunas, I forgot to ask the basics: why do we need a new IP address on node01 ? Is it because we have an existing ip4log entry ? Would it work as-is if we clean ip4log during teardown ?

We need to have the device request a new IP address so that the pfdhcplistener sees it and triggers the firewall SSO in the second test.

We tried using the RADIUS accounting data switch01 sends but unfortunately it doesn't contain the Framed-IP-Address so we can't do SSO using that leaving only DHCP as the trigger

2022-02-06 07:50 UTC, nqb requested changes
- [X] During teardown of two test suites, I suggest to restart pfsso **after** disable_sso_on_advanced

2022-02-06 07:50 UTC, nqb commented on t/venom/test_suites/wired_dot1x_eap_peap_firewall_sso_https/teardown/03_kill_http_smocker.yml
> +      sudo kill -9 `cat {{.smocker_dir}}/haproxy.pid`
```suggestion
      kill -9 `cat {{.smocker_dir}}/haproxy.pid`
```

2022-02-06 07:50 UTC, nqb commented on t/venom/test_suites/wired_dot1x_eap_peap_firewall_sso_https/teardown/03_kill_http_smocker.yml
> +      sudo pkill smocker
```suggestion
      pkill smocker
```

2022-02-06 07:50 UTC, nqb commented on t/venom/test_suites/wired_dot1x_eap_peap_firewall_sso_https/teardown/03_kill_http_smocker.yml
> +          from: result.systemout
Can be removed. This variable will not be usable after end of test.

2022-02-06 07:50 UTC, nqb commented on t/venom/test_suites/wired_dot1x_eap_peap_firewall_sso_radius/03_create_radius_mock.yml
> +      npm install pm2 -g
Is it still necessary after Ansible provisioning (see configure.yml) ?

2022-02-09 18:38 UTC, satkunas commented on t/venom/test_suites/wired_dot1x_eap_peap_firewall_sso_radius/03_create_radius_mock.yml
> +      npm install pm2 -g
Yes, the ansible provisioning did not properly install pm2 as a global package

2022-02-15 15:24 UTC, nqb commented on t/venom/test_suites/wired_dot1x_eap_peap_firewall_sso_radius/03_create_radius_mock.yml
> +      npm install pm2 -g
I'm removing `pm2` installation in `configure.yml` to avoid confusion

2022-02-17 07:05 UTC, merged