Add the ip6tables service
inverse-inc/packetfence pull request #6836
Opened 2022-01-19 20:56 UTC by julsemaan

# Description
Adds the ip6tables service

# Impacts
New service

# Issue
fixes #6351 

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [N/A] Document the feature
- [N/A] Add unit tests
- [TODO] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* The ip6tables rules are now managed by PacketFence

2022-01-19 20:57 UTC, julsemaan commented
Tested the packaging on Debian + RHEL and its fine

We'll have an acceptance test in the integration tests with a little magic from @nqb

2022-01-19 21:09 UTC, nqb requested changes
Packaging looks good. 

Regarding binary location for Debian, I think we just need to apply a patch on `pf.conf` like we do for FreeRADIUS: https://github.com/inverse-inc/packetfence/blob/84892e085adc6b342790f805bc61fc9361f7a149/debian/patches/debianize.patch#L42-L49

to have a working ip6tables on Debian without any visible override on `pf.conf`

2022-01-20 12:19 UTC, extrafu commented on conf/documentation.conf
> +not running the RPMed version.
"RPMed version" - how about the Debian packages? Should we simply say "if you are not running the official packaged version" ?

2022-01-20 12:19 UTC, extrafu commented on conf/pf.conf.defaults
> +# location of the ip6tables binary. only necessary to change if you are not running the rpmed version.
Same as above

2022-01-20 12:54 UTC, julsemaan commented
> Packaging looks good.
> 
> Regarding binary location for Debian, I think we just need to apply a patch on `pf.conf` like we do for FreeRADIUS:
> 
> https://github.com/inverse-inc/packetfence/blob/84892e085adc6b342790f805bc61fc9361f7a149/debian/patches/debianize.patch#L42-L49
> 
> to have a working ip6tables on Debian without any visible override on `pf.conf`

Based on my findings, the binary is located at the same place on RHEL 8 and Debian 11

2022-01-25 16:57 UTC, fdurand requested changes
It miss the debianize.patch change.
Do we need to log in ip6tables ?

2022-01-25 16:57 UTC, fdurand commented on lib/pf/ip6tables.pm
> +    my ($class) = @_;
self instead of class

2022-01-25 16:57 UTC, fdurand commented on lib/pf/ip6tables.pm
> +    my ($class, $save_file) = @_;
self instead of class

2022-01-25 16:57 UTC, fdurand commented on lib/pf/ip6tables.pm
> +    my ($class, $restore_file) = @_;
self instead of class

2022-01-25 16:57 UTC, fdurand commented on lib/pf/services/manager/ip6tables.pm
> +    return 1;
Use constant

2022-01-25 16:57 UTC, fdurand commented on lib/pf/services/manager/ip6tables.pm
> +    return 1;
Use constant

2022-01-25 16:57 UTC, fdurand commented on lib/pf/services/manager/ip6tables.pm
> +    return 1;
Use constant

2022-01-25 16:57 UTC, fdurand commented on lib/pf/services/manager/ip6tables.pm
> +    return 1;
Use constant

2022-01-25 16:57 UTC, fdurand commented on lib/pf/services/manager/ip6tables.pm
> +    return ($pid && $rules_applied) ? 1 : 0;
Use constant

2022-01-25 16:57 UTC, fdurand commented on lib/pf/services/manager/ip6tables.pm
> +    return $? == 0;
Use constant

2022-01-25 17:01 UTC, julsemaan commented on lib/pf/ip6tables.pm
> +    my ($class) = @_;
AFAIK, we use `$class` when we don't have to call `new` on the module (its the case here)

@jrouzierinverse can correct me if I'm wrong

2022-01-25 17:02 UTC, julsemaan commented
> It miss the debianize.patch change. 
AFAIK there is nothing necessary there because the paths are the same on Debian and RHEL (I tested a package on both)
That is unless something else than the binary paths has to be debianized

> Do we need to log in ip6tables ?
You mean ip6tables.pm? Or the actual ip6tables chain?

2022-01-25 17:07 UTC, fdurand commented
> > It miss the debianize.patch change.
> 
> AFAIK there is nothing necessary there because the paths are the same on Debian and RHEL (I tested a package on both) That is unless something else than the binary paths has to be debianized

It´s for the systemd script, the perl path is not the same.
> 
> > Do we need to log in ip6tables ?
> 
> You mean ip6tables.pm? Or the actual ip6tables chain?

I mean that:
-j LOG --log-prefix "STATE_INVALID_DROP: "

2022-01-25 18:23 UTC, julsemaan commented
I've moved the venom tests into [fix/6351](https://github.com/inverse-inc/packetfence/tree/fix/6351-test)

2022-01-25 18:26 UTC, julsemaan commented
> > > It miss the debianize.patch change.
> > 
> > 
> > AFAIK there is nothing necessary there because the paths are the same on Debian and RHEL (I tested a package on both) That is unless something else than the binary paths has to be debianized
> 
> It´s for the systemd script, the perl path is not the same.

According to my Debian 11 machine, `/bin/perl` points to the Perl binary:
```
root@test-pf:~# /bin/perl --version

This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-gnu-thread-multi
(with 46 registered patches, see perl -V for more detail)

Copyright 1987-2021, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

With that in mind, is it really worth changing debianize.patch for patching something that isn't required

> > > Do we need to log in ip6tables ?
> > 
> > 
> > You mean ip6tables.pm? Or the actual ip6tables chain?
> 
> I mean that: -j LOG --log-prefix "STATE_INVALID_DROP: "

I'll remove this

2022-01-25 18:31 UTC, fdurand commented
If the perl path is ok on debian 11 then we are good so.

2022-01-25 18:37 UTC, julsemaan commented
Everything should be adjusted except the `$self` vs `$class` which is due to calling the functions on the class and not on a blessed instance. 

Happy to change it if we state we must use `$self` even in this case

Some examples of `$class`:
- lib/pf/api.pm
- lib/pf/Connection/Profile.pm
- lib/pf/Portal/Session.pm

2022-01-25 18:45 UTC, merged