add unit tests for addons/functions/
inverse-inc/packetfence pull request #6846
Opened 2022-01-25 19:24 UTC by julsemaan

# Description
Add unit tests for addons/functions/

# Impacts
Venom unit tests

# Delete branch after merge
YES

2022-01-25 19:31 UTC, julsemaan commented
See this pipeline: https://gitlab.com/inverse-inc/packetfence/-/pipelines/456189959

2022-02-07 15:25 UTC, nqb requested changes
- [X] You need to adjust packaging for `packetfence-test` on Debian like you did for EL
- [X] I think `vars.tests.ci-el8` could be rename `vars.tests.ci` because I don't think why it would be different at some point for Debian

I will review *.tests later

2022-02-07 15:25 UTC, nqb commented on t/addons-functions/README.md
> +./run-all.tests
```suggestion
make test
```

2022-02-07 15:25 UTC, nqb commented on t/venom/test_suites/unit_tests/addons_functions_tests.yml
> +    script: "sed -i 's#%%TEST_INTERFACE_NETWORK%%#{{ .pfserver_mgmt_net }}#g' /usr/local/pf/t/addons-functions/vars.tests"
Could you remove space inside curly brackets ?

2022-02-07 15:25 UTC, nqb commented on t/venom/test_suites/unit_tests/addons_functions_tests.yml
> +    script: "sed -i 's#%%TEST_INTERFACE_NETWORK%%#{{ .pfserver_mgmt_net }}#g' /usr/local/pf/t/addons-functions/vars.tests"
If you rebase on devel, you can use `pfserver_test_dir` variable to replace `/usr/local/pf/t`

2022-02-07 15:31 UTC, nqb reviewed
If I understand correctly the code;

`failed_test "get_os_ip_address provides the right IP address"` means that ` test_get_os_ip_address` **doesn't** provide the right IP address no ?

2022-02-07 15:38 UTC, julsemaan commented
> If I understand correctly the code;
> 
> `failed_test "get_os_ip_address provides the right IP address"` means that ` test_get_os_ip_address` **doesn't** provide the right IP address no ?

Correct so it fails the assertion `get_os_ip_address provides the right IP address`

The text describes what **should** happen and if it doesn't the output will be:
`FAILED: get_os_ip_address provides the right IP address`

2022-02-07 15:40 UTC, julsemaan commented
> * You need to adjust packaging for `packetfence-test` on Debian like you did for EL

I'm not sure what/where to adjust that since unit tests only seem to be running on EL8 from what I saw

> * I think `vars.tests.ci-el8` could be rename `vars.tests.ci` because I don't think why it would be different at some point for Debian
> 

Agreed, I'll adjust that

2022-02-07 19:45 UTC, nqb commented
> I'm not sure what/where to adjust that since unit tests only seem to be running on EL8 from what I saw

You're right regarding unit tests running on EL8 but we packaged `packetfence-test` for Debian too. I will adjust packaging for Debian.

2022-02-07 20:34 UTC, merged