fix/6830
inverse-inc/packetfence pull request #6850
Opened 2022-01-27 13:26 UTC by jrouzierinverse

# Description
Improve the performance of the bandwidth accounting cleanup process

# Impacts
Bandwidh accounting.

# Issue
fixes #6380

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries

## Enhancements
* Improved the performance of the bandwidth accounting cleanup process

2022-02-09 13:25 UTC, fdurand commented on db/upgrade-X.X-X.Y.sql
> + ADD INDEX bandwidth_accounting_tenant_id_mac_last_updated (tenant_id, mac, last_updated),
ADD INDEX IF NOT EXISTS

2022-02-09 14:02 UTC, jrouzierinverse commented on db/upgrade-X.X-X.Y.sql
> + ADD INDEX bandwidth_accounting_tenant_id_mac_last_updated (tenant_id, mac, last_updated),
This is fixed in devel let me rebase

2022-02-09 15:14 UTC, fdurand requested changes

2022-02-09 15:14 UTC, fdurand commented on db/upgrade-X.X-X.Y.sql
> +DELIMITER /
Add comment like \! echo "blablabla"

2022-02-09 15:14 UTC, fdurand commented on db/upgrade-X.X-X.Y.sql
> +DELIMITER /
Add comment like \! echo "blablabla"

2022-02-09 15:14 UTC, fdurand commented on db/upgrade-X.X-X.Y.sql
> +DELIMITER /
Add comment like \! echo "blablabla"

2022-02-09 15:14 UTC, fdurand commented on db/upgrade-X.X-X.Y.sql
> +DELIMITER /
Add comment like \! echo "blablabla"

2022-02-11 16:34 UTC, fdurand requested changes
Remove the procedure and fix the missing admin gui parameters and we will be good to merge.

2022-02-11 16:34 UTC, fdurand commented on conf/pfcron.conf.defaults
> +session_batch=100
needs to be visible from the admin gui

2022-02-11 16:34 UTC, fdurand commented on conf/pfcron.conf.defaults
> +session_timeout=5s
needs to be visible from the admin gui

2022-02-11 16:34 UTC, fdurand commented on conf/pfcron.conf.defaults
> +session_window=24h
needs to be visible from the admin gui

2022-02-11 17:12 UTC, merged