Feature: UI Cluster Services
inverse-inc/packetfence pull request #6855
Opened 2022-01-27 18:26 UTC by satkunas

# Description
Implement service handling on any/all members of a cluster. Implement a single store module to unify service, system_service and systemd API calls. Deprecates 2 existing store modules for service (local only) and cluster_service.

# Impacts
* Configurator service handling
* Status service handling
* Status > Clusert Services handling.

# Issue
...

# Delete branch after merge
YES 

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* Unified service store module allowing control of both local - and cluster members - services.

## Bug Fixes
...

2022-01-27 18:38 UTC, julsemaan commented
I can't wait to use this on my cluserts

2022-01-31 13:48 UTC, extrafu commented
@cgx Make sure to review this quickly

2022-02-01 13:33 UTC, satkunas commented
@jrouzierinverse using the `X-PacketFence-Server` header to proxy a request through haproxy to another member of the cluster works, but the login token does not appear to be shared among the members, so this fails with a `401 "Invalid token. Login again using /api/v1/login"`

2022-02-04 15:26 UTC, satkunas commented
Fixes also needed with #6867

2022-02-07 19:45 UTC, satkunas commented
@jrouzierinverse 

`{async: true}` support is needed in `/api/v1/configurator/system_service/`

2022-06-07 14:31 UTC, satkunas commented
@cgx conflicts fixed and merged.

2022-07-05 19:23 UTC, cgx commented
It would be nice to adopt either `$t()` or `$i18n.t()` but not both.

2022-07-05 19:26 UTC, cgx requested changes

2022-07-05 19:26 UTC, cgx commented on html/pfappserver/root/src/store/modules/cluster.js
> +*/
Can we remove this commented block?

2022-07-05 19:26 UTC, cgx commented on html/pfappserver/root/src/components/new/BaseButtonService.vue
> +    $store.dispatch('notification/info', { url: server, message: i18n.t('Service <code>{service}</code> killed.', { service: service.value }) })
I recommend replacing *kill* by *stop* everywhere.

2022-07-05 19:26 UTC, cgx commented on html/pfappserver/root/src/views/Status/services/_components/BaseService.vue
> +    <template v-slot:overlay v-if="service.status && !['loading'].includes(service.status)">
Simplify with `service.status && service.status !== 'loading'`

2022-07-05 19:26 UTC, cgx commented on html/pfappserver/root/src/views/Status/services/_components/BaseService.vue
> +          <b-row class="row-nowrap">
`row-nowrap` doesn't seem to be valid class. Please remove it everywhere.

2022-07-05 19:26 UTC, cgx commented on html/pfappserver/root/src/views/Status/services/_components/BaseService.vue
> +          <b-row class="row-nowrap">
Add `cols="2"` to force both columns to appear on the same row.

2022-07-05 19:26 UTC, cgx commented on html/pfappserver/root/src/views/Status/services/_components/BaseButtonBulkActions.vue
> +    event.stopPropagation()
Useless since you used the `stop` event modifier.

2022-07-12 14:03 UTC, satkunas commented
> It would be nice to adopt either `$t()` or `$i18n.t()` but not both.

I will change all to the latter since it's more explicit.

2022-07-12 17:16 UTC, satkunas commented on html/pfappserver/root/src/views/Status/services/_components/BaseService.vue
> +          <b-row class="row-nowrap">
This was inherited from a class defined in Portal Modules. I moved the class def to the root /styles.

2022-08-16 18:00 UTC, merged