feature/utf8-db
inverse-inc/packetfence pull request #6937
Opened 2022-03-17 18:34 UTC by jrouzierinverse

# Description
UTF8 support in the database.

# Impacts
The database encoding.

# Issue
fixes #4514
fixes #2519
fixes #4049

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## New Features
* Full UTF8 support

## Bug Fixes
* Display of UTF8 strings (#4514)
* Accented characters support for users fields (#2519)
* Use Unicode characters like Chinese/Arabic not are not correctly shown in web admin (#4049)

2022-03-17 19:15 UTC, extrafu commented
I think we should run the performance/stress tests we run prior a release on this PR before merging. See if it has any performance impacts for key aspects of PacketFence.

2022-06-21 11:53 UTC, extrafu commented
@julsemaan I think we should look into this one and merge it sooner than later.

2022-06-21 12:15 UTC, julsemaan commented
Agreed, IMO we need to:
- Rebase against the latest devel
- Get confirmation from @jrouzierinverse that he is getting consistent encoding across the captive portal + admin
- Get confirmation from @jrouzierinverse that he did test the resolution of the 3 issues he mentioned in this PR

2022-07-19 14:49 UTC, satkunas requested changes

2022-07-19 14:49 UTC, satkunas commented on db/upgrade-X.X-X.Y.sql
> +<<<<<<< HEAD
fix merge

2022-07-19 14:49 UTC, satkunas commented on db/upgrade-X.X-X.Y.sql
> +<<<<<<< HEAD
fix merge

2022-07-25 13:51 UTC, extrafu commented
@satkunas All good on this one?

2022-07-25 14:27 UTC, satkunas commented
> @satkunas All good on this one?

I'm good

2022-07-25 14:28 UTC, extrafu commented
@satkunas In this case please merge it

2022-07-25 14:38 UTC, merged