[Containers] pfpki: add as a container
inverse-inc/packetfence pull request #7020
Opened 2022-06-07 19:12 UTC by JeGoi

# Description
Add pfpki in container

# Impacts
pfpki is now in a container

# Delete branch after merge
YES

# Checklist
- [./ ] Tests done

2022-06-07 19:18 UTC, julsemaan requested changes

2022-06-07 19:18 UTC, julsemaan commented on containers/pfpki/Dockerfile
> +ENTRYPOINT /bin/bash -c "export $(cat /usr/local/pf/var/conf/pfpki.env | xargs) && /usr/local/pf/sbin/pfhttpd -conf /usr/local/pf/conf/caddy-services/pfpki.conf -log-name=pfpki"
You do not need to load /usr/local/pf/var/conf/pfpki.env in the env, it will be done implicitely (api-frontend is an example of that)

FYI, where it's done:
https://github.com/inverse-inc/packetfence/blob/devel/containers/systemd-service#L17-L19

2022-06-07 19:23 UTC, JeGoi commented on containers/pfpki/Dockerfile
> +ENTRYPOINT /bin/bash -c "export $(cat /usr/local/pf/var/conf/pfpki.env | xargs) && /usr/local/pf/sbin/pfhttpd -conf /usr/local/pf/conf/caddy-services/pfpki.conf -log-name=pfpki"
Fixed

2022-06-08 11:51 UTC, julsemaan commented
Launched a pipeline, if it succeeds I'll merge

https://gitlab.com/inverse-inc/packetfence/-/pipelines/558556203

2022-06-08 15:18 UTC, JeGoi commented
Unless I missed something, it looks good.

2022-06-08 16:54 UTC, merged