Security Visualizations (VizSec)
inverse-inc/packetfence pull request #7038
Opened 2022-06-21 16:28 UTC by satkunas

# Description
* Add Assets Visualization
* Add Threats Visualization
* Add Network Communication Visualization

# Code / PR Dependencies
 * new release of the Fingerbank Perl lib: https://github.com/fingerbank/perl-client/commit/f82b02eca3ad725efe0c5ee1e26d7e4630df64d0

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [n/a] Add unit tests
- [n/a] Add acceptance tests (TestLink)

# NEWS file entries
## New Features
* Added Assets, Communication and Threats visualizations

2022-07-19 16:06 UTC, cgx requested changes

2022-07-19 16:06 UTC, cgx commented on db/upgrade-X.X-X.Y.sql
> +   DROP PRIMARY KEY,
Spaces commit snafu.

2022-07-19 16:06 UTC, cgx commented on db/upgrade-X.X-X.Y.sql
> +   DROP PRIMARY KEY,
Spaces commit snafu.

2022-07-19 16:06 UTC, cgx commented on html/pfappserver/root/src/views/Status/network_communication/_components/TheSearch.vue
> +          :class="(selectedDeviceClasses.indexOf(deviceClass.id) > -1) ? 'text-success' : 'text-muted'"
Why colouring the text here and the border in `network_threats`? I think it would be nice to choose only one representation. Personally I prefer when the border is coloured.

2022-07-19 16:06 UTC, cgx commented on html/pfappserver/root/src/views/Status/network_communication/_composables/useCommunication.js
> +  */
Can this commented block be removed?

2022-07-19 16:06 UTC, cgx commented on html/pfappserver/root/src/views/Status/network_communication/_components/BaseDataHosts.vue
> +          const color = 'rgb(40, 167, 69)' // success
Would be better to define constants when you apply static rgb colours.

2022-07-19 16:06 UTC, cgx commented on html/pfappserver/root/src/views/Status/network_communication/_components/TheSearch.vue
> +  </base-search>
I find it confusing to navigate through the pagination on the left column while the data is located in the right column. It would be better to have it accessible from the right column, at a more visible location (maybe at the top?).

2022-07-19 16:06 UTC, cgx commented on html/pfappserver/root/src/views/Status/network_communication/_components/TheView.vue
> +      border-top: 1px solid rgb(222, 226, 230);
Use a CSS variable.

2022-07-19 16:06 UTC, cgx commented on html/pfappserver/root/src/views/Status/network_communication/_components/BaseDataFlow.vue
> +    //$store.dispatch('$_fingerbank_communication/toggleDevice', device)
Can this line be removed?

2022-07-21 19:35 UTC, cgx approved these changes

2022-07-22 12:01 UTC, extrafu commented
@cgx If approved, please merge it

2022-07-22 12:47 UTC, merged