Updated Intune integration to work with Microsoft Graph
inverse-inc/packetfence pull request #7115
Opened 2022-08-17 06:31 UTC by trs80

# Description
Updates the Intune cloud integration to work with MS Graph API as well as Azure AD API

# Impacts
Makes Intune SCEP support work for new installs since Azure AD API is deprecated and going away soonish

# Issue
fixes #6933

# Delete branch after merge
NO

# Checklist
(REQUIRED) - [yes, no or n/a]
- [yes] Document the feature
- [no] Add unit tests
- [no] Add acceptance tests (TestLink)

# NEWS file entries
## Bug Fixes
If an issue exists on Github, please refer to it (name) along with it's number...
* Updates Intune integration to new Microsoft Graph API (#6933)

2022-08-17 06:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/inverse-inc/packetfence?pullRequest=7115) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/inverse-inc/packetfence?pullRequest=7115) before we can accept your contribution.<br/><hr/>**James Andrewartha** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/inverse-inc/packetfence?pullRequest=7115) it.</sub>

2022-08-23 22:22 UTC, fdurand commented
For the screenshot can we add both or at least say if Azure AD API is deprecated then do that ?

2022-08-23 22:22 UTC, fdurand requested changes

2022-08-23 22:22 UTC, fdurand commented on go/caddy/pfpki/cloud/intune.go
> +	var aadGraphFailed bool
it should be msGraphFailed instead since the first request is for msGraphResourceUrl

2022-08-23 22:22 UTC, fdurand commented on go/caddy/pfpki/cloud/intune.go
> +		aadGraphFailed = true
msGraphFailed

2022-08-23 22:22 UTC, fdurand commented on go/caddy/pfpki/cloud/intune.go
> +	if aadGraphFailed {
msGraphFailed

2022-08-23 22:22 UTC, fdurand commented on go/caddy/pfpki/cloud/intune.go
> +					if a == "providerName" && !aadGraphFailed || a == "serviceName" && aadGraphFailed {
msGraphFailed

2022-08-24 04:21 UTC, trs80 commented
For the screenshot, Azure AD Graph is so deprecated you can't even add it via the web UI any more, and will stop working after the end of 2022. So I've added a note saying that and to add the new permissions instead.

I've changed the variable name, the Azure AD Graph codepath does need testing by someone else who already has it set up.

2022-09-15 06:18 UTC, trs80 commented
Fixed conflict with upstream (adding spew.Dump(err.Error()) basically)

2022-09-16 16:54 UTC, fdurand commented
@trs80 i did another branch for that since adal will be deprecated in favor of azidentity https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/MIGRATION.md#autorestadal-5 .
I also completly deprecated Azure AD API and if you want to use intune with new version of PacketFence then you will need to adjust the permissions.

https://github.com/inverse-inc/packetfence/compare/fix/intune

Btw i don´t want to rob your work so if you want you can take the code i did and apply it on your PR.

2022-09-21 00:56 UTC, trs80 commented
I'm not fussed about credit, I just want a working version merged. I can update the docs on top of your PR if you want.

2022-10-31 16:58 UTC, fdurand commented
Other branch has been merged in devel.
Thanks a lot for your work.

2022-10-31 16:58 UTC, closed without merging