Feature/venom pf security event Suricata
inverse-inc/packetfence pull request #7255
Opened 2022-10-06 16:26 UTC by JeGoi

# Description
Add suricata security event based on inline l2 test suite.

# Impacts
Suricata test can be removed from manual testing

# Delete branch after merge
YES

2022-10-06 16:28 UTC, extrafu commented
Very nice! 👍

2022-10-07 09:29 UTC, nqb requested changes
General remarks:
- security_events_suricata test suite should be integrated into inline scenarios. Otherwise, we are adding another scenario which take around 25 minutes to run
- I don't see a reason to rename existing scenario "security_events" to "security_events_autoreg". If we want to add other "security events" test suites inside this scenario, it will be a problem.
- There are several changes in Venom executors which are not used by security_events_suricata test suite but by other test suites. Could you move these changes into a dedicated PR ? In that way, we will be able to check if they have impacts on other test suites.
- In TESTSUITE.md, some steps are mentioned but they are missing in fact because the logic is different.
- The device is registered in (20_local..) but in fact, we don't rely on that later. So it's not really necessary to do it.

2022-10-07 09:29 UTC, nqb commented on t/venom/test_suites/security_event_suricata/25_prepare_security_event_suricata.yml
> +#    triggers: '[{"dhcp_fingerprint": "{{.security_event_suricata.node.dhcp_fingerprint_id}}"}]'
Can be removed I guess

2022-10-07 09:29 UTC, nqb commented on t/venom/test_suites/security_event_suricata/25_prepare_security_event_suricata.yml
> +            "suricata_event": "ET POLICY ",
Not sure if space after `POLICY` is expected

2022-10-07 09:29 UTC, nqb commented on t/venom/test_suites/security_event_suricata/27_create_suricata_event.yml
> +- name: get_node01_dhcp_on_reg
The name of the test case is a bit confusing because there is no "registration" network because you are using an inline L2 network.

2022-10-07 09:29 UTC, nqb commented on t/venom/test_suites/security_event_suricata/teardown/40_delete_security_event.yml
> +name: SecurityEventAutoreg
Wrong title

2022-10-07 09:29 UTC, nqb commented on t/venom/test_suites/security_event_suricata/teardown/50_delete_file.yml
> +name: SecurityEventAutoreg
Wrong title

2022-10-07 09:29 UTC, nqb commented on t/venom/vars/all.yml
> +security_event_suricata.node.dhcp_fingerprint_id: 276
I don't think these variables are used

2022-10-07 09:29 UTC, nqb commented on t/venom/lib/pf_api_syslog_parser_action.yml
> +  pf_api_realm_action_: "{{.result.pf_api_action_}}"
I think there is a mistake here (`realm`)

2022-10-07 09:29 UTC, nqb commented on t/venom/test_suites/security_event_suricata/TESTSUITE.md
> +# Inline L2
Wrong title

2022-10-07 11:09 UTC, JeGoi commented on t/venom/test_suites/security_event_suricata/25_prepare_security_event_suricata.yml
> +#    triggers: '[{"dhcp_fingerprint": "{{.security_event_suricata.node.dhcp_fingerprint_id}}"}]'
Still the issue with venom 1.0.1 version... I should have remove it.

2022-10-07 11:42 UTC, JeGoi commented
@nqb :
1) security_events_suricata test suite should be integrated into inline scenarios. Otherwise, we are adding another scenario which take around 25 minutes to run
Why not... It is just that it will be hidden inside this scenario which is not talking about security events...

2) I don't see a reason to rename existing scenario "security_events" to "security_events_autoreg". If we want to add other "security events" test suites inside this scenario, it will be a problem.
Ok but how to manage it with point 1. Another solution is to name scenarios with vms deployed inside...

3) There are several changes in Venom executors which are not used by security_events_suricata test suite but by other test suites. Could you move these changes into a dedicated PR ? In that way, we will be able to check if they have impacts on other test suites.
Yes and no, at the beginning, we used security_events_autoreg as a reference them, libs have been created/modified. Because we tried to add more tests (web access), it has been rebased on inline/l2 which is easier to manage nodes, add a dhcp server, etc.
As you can see there, https://gitlab.com/inverse-inc/packetfence/-/jobs/3137913477 it is running even with these modifications. So, before revert them, why not just run the others? On current pipeline test, issues are mostly not related to venom.

4) In TESTSUITE.md, some steps are mentioned but they are missing in fact because the logic is different.
I will double check. All steps are mostly the same except the suricata settings and how the flag is risen.

5) The device is registered in (20_local..) but in fact, we don't rely on that later. So it's not really necessary to do it.
I think here you are wrong, it needs to be register to check the access to internet. It is the equivalent of: ./t/venom/test_suites/inline/l2/20_local_user_authentication.yml

2022-10-07 12:28 UTC, JeGoi commented on t/venom/test_suites/security_event_suricata/25_prepare_security_event_suricata.yml
> +#    triggers: '[{"dhcp_fingerprint": "{{.security_event_suricata.node.dhcp_fingerprint_id}}"}]'
Fixed

2022-10-07 12:32 UTC, JeGoi commented on t/venom/test_suites/security_event_suricata/25_prepare_security_event_suricata.yml
> +            "suricata_event": "ET POLICY ",
It is coming from the request. No clue if it is, but it is a copy paste. So...

2022-10-07 12:38 UTC, JeGoi commented on t/venom/test_suites/security_event_suricata/27_create_suricata_event.yml
> +- name: get_node01_dhcp_on_reg
Correct. Renamed.

2022-10-07 12:41 UTC, JeGoi commented on t/venom/test_suites/security_event_suricata/teardown/50_delete_file.yml
> +name: SecurityEventAutoreg
Fixed

2022-10-07 12:43 UTC, JeGoi commented on t/venom/vars/all.yml
> +security_event_suricata.node.dhcp_fingerprint_id: 276
Your are right connected to the first iteration of this test_suite

2022-10-07 12:44 UTC, JeGoi commented on t/venom/lib/pf_api_syslog_parser_action.yml
> +  pf_api_realm_action_: "{{.result.pf_api_action_}}"
Fixed

2022-10-07 12:47 UTC, JeGoi commented on t/venom/test_suites/security_event_suricata/TESTSUITE.md
> +# Inline L2
Fixed with other improvements.

2022-10-10 13:32 UTC, nqb commented on t/venom/test_suites/security_event_suricata/25_prepare_security_event_suricata.yml
> +name: Create autoreg security event
Wrong title

2022-10-10 13:42 UTC, nqb commented
### 1 and 2

`security_events_suricata`  is an inline test, `security_event_autoreg` can be seen as a RADIUS test. So perhaps you can rename things accordingly.

### 3

I think we can keep changes in this PR if we are sure there is no regression on other test suites.

If I'm not wrong, changes in these PR have impact on other test suites (not only on `security_events_autoreg`).
But again, it's really more easy to review small PR with limited changes on specific things.

### 4

These two steps are still mentioned but they are not executed:
```
1. Change the role of the device to guest
1. Test if the device is in the role ID 2 ipset set
```

### 5

Yes you are right.

2022-10-10 14:46 UTC, JeGoi commented
# 1&2
Ok I have already revert it and add security_event_suricata in inline scenario.

# 3
Looks fine to me https://gitlab.com/inverse-inc/packetfence/-/pipelines/661194453
Errors are in the inline l2 and inline/suricata. My guess is that inline/suricata is using the same data as the inline/l2 and i may cause trouble.

# 4
Oh, you are right! Will be  fixed.

2022-10-11 12:35 UTC, nqb commented
Running a pipeline with all tests: https://gitlab.com/inverse-inc/packetfence/-/pipelines/663779856

2022-10-14 19:34 UTC, JeGoi commented on t/venom/test_suites/security_event_suricata/30_tests.yml
> +    script: echo '{{.get_security_event_id.all_events}}' | jq '.[] | if (.security_event_id == 88888889 and .status == "open") then .id else false end ' | grep -v "false"
```suggestion
    script: echo '{{.get_security_event_id.all_events}}' | jq '.[] | if (.security_event_id == {{.security_event_suricata.event.id}} and .status == "open") then .id else false end ' | grep -v "false"
```

2022-10-19 06:23 UTC, merged

2024-06-02 21:01 UTC, mellalahmed commented
Can you help me integrate security events in PacketFence?