Google ldap doc updates
inverse-inc/packetfence pull request #7268
Opened 2022-10-12 18:23 UTC by garci66

# Description
Documentation updates for Google Workspace LDAP source. Makes it a bit clearer what needs to be provisioned / provides some example values

# Impacts
Documentation

# Delete branch after merge
YES 

# Checklist
(REQUIRED) - [yes, no or n/a]
- [yes] Document the feature

# NEWS file entries
(REQUIRED, but may be optional...)
## New Features

## Enhancements

2022-10-13 11:38 UTC, julsemaan requested changes
Some minor details to fix and then I'm happy to merge

Thanks for your contribution!

2022-10-13 11:38 UTC, julsemaan commented on docs/installation/google_workspace_ldap.asciidoc
> +  .. You will also need to configure several values for the Authentication Source:
```suggestion
  .. You will also need to these properties for the Authentication Source:
```

2022-10-13 11:38 UTC, julsemaan commented on docs/installation/google_workspace_ldap.asciidoc
> +  .. For Authentication and Administration rules, you can match against google group membership (if you have configured google to allow group membership access - this is done when creating the ldap c
```suggestion
  .. For Authentication and Administration rules, you can match against google group membership (if you have configured google to allow group membership access - this is done when creating the LDAP client on the Google workspace configuration page on Google's side, not on PacketFence). In that case, you will want to use the condition `memberOf`, a match of `equals` and the value of `cn=mygroupname,ou=Groups,dc=example,dc=com` if your group is called "mygroupname`. Keep in mind that nested group membership does not work via ldap for google workspace.
```

2022-10-14 13:42 UTC, garci66 commented
You're welcome. Seeing the number of questions in the mailing list about google, I thought this could help.

2022-10-14 14:11 UTC, merged