[Venom] Security test random mac: first commit
inverse-inc/packetfence pull request #7292
Opened 2022-10-19 20:34 UTC by JeGoi

# Description
Add test with random mac address security event with inline l2

# Impacts
Do the test in venom. Can be removed from testlink

# Delete branch after merge
YES

## New Features
* test security random mac address with inline l2

2022-10-19 20:36 UTC, JeGoi commented
https://gitlab.com/inverse-inc/packetfence/-/pipelines/671540811

2022-11-02 17:46 UTC, JeGoi commented
New pipeline looks fine: https://gitlab.com/inverse-inc/packetfence/-/pipelines/683505770

2022-11-16 10:19 UTC, nqb requested changes

2022-11-16 10:19 UTC, nqb commented on t/venom/test_suites/security_event_random_mac/05_setup_packetfence.yml
> +    service: packetfence-iptables
All services below will need to be restarted through API to be consistent with changes made on #7367

2022-11-16 10:19 UTC, nqb commented on t/venom/test_suites/security_event_random_mac/30_tests.yml
> +- name: test_if_the_device_is_back_in_the_register_ipset
```suggestion
- name: test_if_the_device_is_back_in_the_unregister_ipset
```

2022-11-16 10:19 UTC, nqb commented on t/venom/test_suites/security_event_random_mac/teardown/05_deconfigure_packetfence.yml
> +- name: desable_security_event
```suggestion
- name: disable_security_event
```

2022-11-16 10:19 UTC, nqb commented on t/venom/test_suites/security_event_random_mac/teardown/05_deconfigure_packetfence.yml
> +- name: restart_iptables
All services below will need to be restarted through API to be consistent with changes made on https://github.com/inverse-inc/packetfence/pull/7367

2022-11-25 05:48 UTC, nqb commented on t/venom/test_suites/common/restart_pfdns_service.yml
>  name: Restart pfdns service
We have two files which do same thing:
- restart_pfdns.yml
- restart_pfdns_service.yml

2022-11-25 05:56 UTC, nqb commented on t/venom/test_suites/common/restart_pfdns_service.yml
>  name: Restart pfdns service
I removed restart_pfdns.yml to be consistent with current naming convention.

2022-11-25 05:56 UTC, merged