SAML/MFA/etc support for the admin interface login
inverse-inc/packetfence pull request #7302
Opened 2022-10-25 11:36 UTC by julsemaan

# Missing
- [] Admin interface section for the admin_login section of pf.conf
- [] Admin interface configuration of the new RootSession portal module

# Description
Allow usage of the captive portal for authenticating admin users. This allows usage of SAML, MFA and other more advanced mechanisms on the portal to be used on the admin interface

# Impacts
Admin interface login
Portal modules

# Issue
TODO; there are some to link here

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [X] Document the feature
- [N/A] Add unit tests
- [] Add acceptance tests (TestLink)

# NEWS file entries
## New Features
* Added support for authenticating admin users via the captive portal (allows SAML/MFA/etc to be used)

2022-10-25 13:12 UTC, RHDHV-simon-sutcliffe commented
Will this pull request also cover portals used for device registration by end users etc?

2022-10-25 14:14 UTC, julsemaan commented
> Will this pull request also cover portals used for device registration by end users etc? As requested in #6790

Not yet, we put our focus on the admin interface login but this exact same mechanism will be implemented in the self-service portal for users in an upcoming release

2022-10-27 18:09 UTC, julsemaan commented
I believe we have all we need in this PR, @jrouzierinverse, you can start your review

2022-10-28 18:18 UTC, jrouzierinverse requested changes

2022-10-28 18:18 UTC, jrouzierinverse commented on conf/documentation.conf
Please add a description to the entries, or a test will fail.

2022-10-28 18:31 UTC, julsemaan commented on conf/documentation.conf
The real question for me is. Is that test still relevant knowing nothing consumes the description in that file anymore?

2022-10-28 18:56 UTC, jrouzierinverse commented on conf/documentation.conf
We can get rid of the test also.

2022-11-01 13:51 UTC, merged