Feature/configurator async
inverse-inc/packetfence pull request #7367
Opened 2022-11-14 19:03 UTC by JeGoi

# Description
Add async restart for multiple service

# Impacts
Make venom configurator stable for 12.x
Restart other services with async

# Delete branch after merge
YES

# Checklist
- [ ] Add multiple tests
- [ ] Add pipelines tests

2022-11-15 16:19 UTC, nqb commented on t/venom/lib/pf_api_service_start_async.yml
> +  i_delay: 20
The retry/delay is different here, is it on purpose?

2022-11-15 16:19 UTC, nqb commented on t/venom/lib/pf_api_service_start_async.yml
> +  action: "restart"
this action 'restart' doesn't match name of executor 'start"

2022-11-15 16:19 UTC, nqb commented on t/venom/test_suites/common/restart_haproxy_admin.yml
> +name: Restart haproxy-portal service
"admin" has been replaced by "portal". I don't think it's wanted.

2022-11-15 16:19 UTC, nqb commented on t/venom/test_suites/common/restart_haproxy_admin.yml
> +  - type: pf_api_service_start_async
I expect to see `pf_api_system_service_restart_async` if we are doing a restart

2022-11-15 16:19 UTC, nqb commented on t/venom/test_suites/common/restart_haproxy_portal.yml
> +  - type: pf_api_service_start_async
I expect to see `pf_api_system_service_restart_async` if we are doing a restart

2022-11-15 16:19 UTC, nqb commented on t/venom/test_suites/configurator/50_run_configurator_step4.yml
> +  - type: pf_api_service_start_async
I expect to see `pf_api_system_service_restart_async` if we are doing a restart

2022-11-15 16:19 UTC, nqb commented on t/venom/test_suites/common/restart_haproxy_admin.yml
> +    service: 'haproxy-portal'
haproxy-admin

2022-11-15 16:19 UTC, nqb commented on t/venom/test_suites/configurator_inline_l2/50_run_configurator_step4.yml
> +  - type: pf_api_service_start_async
same remark as for previous configurator test suite

2022-11-15 16:19 UTC, nqb commented on t/venom/test_suites/wired_dot1x_eap_tls_pki/41_restart_haproxy-admin_service.yml
> +    service: 'haproxy-portal'
same remark as for previous configurator test suite

2022-11-15 16:19 UTC, nqb commented on t/venom/test_suites/wired_dot1x_eap_tls_pki/42_restart_haproxy-portal_service.yml
> +  - type: pf_api_service_start_async
same remark as for previous configurator test suite

2022-11-15 16:43 UTC, JeGoi commented on t/venom/lib/pf_api_service_start_async.yml
> +  i_delay: 20
What do you mean? The name? if yes, it is to make a difference between to the executor.

2022-11-15 17:00 UTC, nqb commented on t/venom/lib/pf_api_service_start_async.yml
> +  i_delay: 20
The retry/delay value is different from all other executor you create in this PR.

2022-11-15 17:33 UTC, JeGoi commented on t/venom/lib/pf_api_service_start_async.yml
> +  i_delay: 20
I do not remember. Let's make it as the other one. Thanks

2022-11-16 13:46 UTC, nqb requested changes

2022-11-16 13:46 UTC, nqb commented on t/venom/test_suites/common/restart_haproxy_admin.yml
> +name: Restart haproxy-portal service
```suggestion
name: Restart haproxy-admin service
```

2022-11-16 13:46 UTC, nqb commented on t/venom/test_suites/common/restart_haproxy_admin.yml
> +- name: restart_haproxy_portal_service
```suggestion
- name: restart_haproxy_admin_service
```

2022-11-17 12:59 UTC, nqb approved these changes

2022-11-18 07:50 UTC, merged