Feature/go dal
inverse-inc/packetfence pull request #7595
Opened 2023-03-16 13:13 UTC by stgmsa

# Description
implement data access layer using go for table `admin_api_audit_log`

# Impacts
* basic CRUDs accessing `admin_api_audit_log`
* URL queries for List API
* JSON payload query for Search API 
* edge cases and error handlings

# NEW Package(s) required
* validator v10

# Delete branch after merge
YES

# Checklist
- [yes] Document the feature
- [yes] Add unit tests
- [no] Add acceptance tests (TestLink)

# NEWS file entries
## New Features
* Data access layer implemented using go

2023-03-16 13:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/inverse-inc/packetfence?pullRequest=7595) <br/>All committers have signed the CLA.

2023-03-16 16:09 UTC, jrouzierinverse requested changes

2023-03-16 16:09 UTC, jrouzierinverse commented on go/caddy/admin-api-audit-log/models/models.go
> +	CreatedAt time.Time `json:"created_at,omitempty"`
Change to a pointer to avoid it being displayed when not in fields.
```
CreatedAt *time.Time `json:"created_at,omitempty"`
```

2023-03-16 16:09 UTC, jrouzierinverse commented on go/caddy/api/dal_admin_api_audit_log_test.go
> +	fmt.Println(err)
Handle error here

2023-03-16 16:09 UTC, jrouzierinverse commented on go/caddy/api/dal_admin_api_audit_log_test.go
> +		fmt.Printf("Data: %s\n", string(data))
Replace with 
```go
t.Logf("Data: %s\n", string(data))
```

2023-03-28 19:46 UTC, jrouzierinverse requested changes

2023-03-28 19:46 UTC, jrouzierinverse commented on go/caddy/admin-api-audit-log/models/models.go
Rename this file and make a different file for each model.
go/caddy/admin-api-audit-log/models/models.go => go/dal/models

2023-03-30 19:05 UTC, stgmsa commented on go/caddy/admin-api-audit-log/models/models.go
moved to go/caddy/dal/models

2023-04-12 13:23 UTC, jrouzierinverse commented
Remove the DELETE and PATCH methods for the following tables.

admin_api_audit_log
auth_log
dns_audit_log
radacct_log
radius_audit_log

2023-04-12 16:12 UTC, stgmsa commented
> 

removed & ready for re-review.

2023-04-12 17:26 UTC, merged