Update iso rebuild to be EFI bootable
inverse-inc/packetfence pull request #7598
Opened 2023-03-17 14:53 UTC by trs80

# Description
This updates the ISO rebuild process to include the bits for EFI booting

# Impacts
Test booting from UEFI on physical, VMware and/or Hyper-V Gen 2 VM

# Issue
fixes #7113

# Delete branch after merge
YES

# Checklist
- [n/a] Document the feature
- [n/a] Add unit tests
- [n/a] Add acceptance tests (TestLink)

# NEWS file entries

## Enhancements
* ISO supports UEFI booting

2023-03-20 05:26 UTC, nqb commented
Hello @trs80,

Are we sure this change is compatible with non-UEFI boots ?

2023-03-22 07:25 UTC, trs80 commented
I'm back in the office, and tested it with both BIOS and UEFI booting using GNOME Boxes (which uses KVM), they are both fine. I can test it in VMware if you'd like. It just adds extra information so that UEFI works again, the original Debian ISO you extract from uses the same commands and is bootable by both - you can see the full commandline in `.disk/mkisofs` in the ISO image, see https://wiki.debian.org/RepackBootableISO for more information.

2023-06-23 12:07 UTC, nqb requested changes

2023-06-23 12:07 UTC, nqb commented on ci/debian-installer/create-debian-installer.sh
> +xorriso -as mkisofs -r -J -joliet-long -b isolinux/isolinux.bin -c isolinux/boot.cat -boot-load-size 4 -boot-info-table -no-emul-boot -o $ISO_OUT -eltorito-alt-boot -e boot/grub/efi.img -no-emul-boot
Looks like `-no-emul-boot` is called twice.

2023-06-26 11:01 UTC, nqb commented on ci/debian-installer/create-debian-installer.sh
> +xorriso -as mkisofs -r -J -joliet-long -b isolinux/isolinux.bin -c isolinux/boot.cat -boot-load-size 4 -boot-info-table -no-emul-boot -o $ISO_OUT -eltorito-alt-boot -e boot/grub/efi.img -no-emul-boot
I removed extra `-no-emul-boot` and I'm testing changes on my own branch.

2023-06-26 18:47 UTC, closed without merging

2023-06-26 18:57 UTC, nqb commented
Closed in favor of #7724