Draft push acls with ansible
inverse-inc/packetfence pull request #7644
Opened 2023-05-02 13:05 UTC by fdurand

# Description
(REQUIRED)
Describe what the new code is used for.
ie: Allow PacketFence to trigger the coffee machine on wireless EAP 802.1X connection to brew a fresh espresso.

# Impacts
(REQUIRED)
Describe what to reviewer should look at. Will also help for testing purposes.
ie: - RADIUS authorize workflow

# Code / PR Dependencies
(OPTIONAL. REMOVE IF NOT NEEDED)
List the PRs or other factors on which this PR depends

# NEW Package(s) required
(OPTIONAL. REMOVE IF NOT NEEDED)
Which new package(s) (all supported distributions) are required for this PR to work.

# Issue
(OPTIONAL. REMOVE IF NOT NEEDED)
The following syntax 'fixes #ISSUE_NUMBER' will automatically closes a Github issue on pull-request merge time.
Modify the ISSUE_NUMBER in order to reflect the Github issue that need to be closed
fixes #ISSUE_NUMBER

# Delete branch after merge
(REQUIRED)
YES | NO

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
(REQUIRED, but may be optional...)
## New Features
* Feature 1
* Feature 2

## Enhancements
* Enhancement 1
* Enhancement 2

## Bug Fixes
If an issue exists on Github, please refer to it (name) along with it's number...
* Issue with Zammitbug in sandwich context (#42)
* Issue with Zammitbug in dinde context (#43)

# UPGRADE file entries
(OPTIONAL, but may be required...)

2023-06-29 15:37 UTC, satkunas commented
Error being generated from Roles (`GET /api/v1/config/roles`) when viewing the switch page:

```
Jun 29 08:36:13 172 pfperl-api-docker-wrapper[226135]: pfperl-api(17) ERROR: [mac:[undef]] Can't call method "new" on an undefined value at /usr/local/pf/lib/pf/UnifiedApi/Controller/Config.pm line 238.
```

2023-06-30 13:30 UTC, jrouzierinverse requested changes

2023-06-30 13:30 UTC, jrouzierinverse commented on lib/pf/UnifiedApi/Controller/Config/Roles.pm
> +    $self->port_update($id);
This is a typo

2023-07-04 13:54 UTC, JeGoi reviewed
Please, could you address my questions points?
Thanks

2023-07-04 13:54 UTC, JeGoi commented on conf/pfsetacls/collections/requirements.yml
> +collections:
I think you should add a version there for all collections.

2023-07-04 13:54 UTC, JeGoi commented on containers/pfsetacls/Dockerfile
> +FROM golang:bullseye
Why didn't you use the pfbuild-debian-bullseye?

2023-07-04 13:54 UTC, JeGoi commented on containers/pfsetacls/Dockerfile
> +RUN apt install -y gcc g++ make git mariadb-client-10.5 python3 pip python3-openssl openssl ca-certificates curl libcurl4-openssl-dev openssh-client tini nodejs bash rsync && \
Two lines could be merged

2023-07-05 13:36 UTC, JeGoi commented
More as a reminder change that too when it is ready:
https://github.com/inverse-inc/packetfence/blob/devel/addons/dev-helpers/bin/switch_options_table.pl
Due to `PushACLs` in Switch libs

2023-07-07 15:05 UTC, satkunas commented on lib/pf/Switch.pm
> +    print STDERR Dumper($acls);
Debug that needs to be removed?

2023-07-07 15:52 UTC, merged