feature/remove-httpd-collector
inverse-inc/packetfence pull request #7667
Opened 2023-05-16 14:16 UTC by jrouzierinverse

# Description
Remove httpd collector

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* Remove unused service httpd.collector

2023-05-16 17:26 UTC, satkunas approved these changes
More UI changes pushed

2023-06-12 18:52 UTC, fdurand requested changes

2023-06-12 18:52 UTC, fdurand commented on debian/packetfence.conffiles
> -/etc/sudoers.d/packetfence
Why so many files ?

2023-06-12 18:52 UTC, fdurand commented on debian/patches/debianize.patch
> -+ExecStartPre=/usr/bin/perl -I/usr/local/pf/lib -I/usr/local/pf/lib_perl/lib/perl5 '-Mpf::services::manager::httpd_collector' -e 'pf::services::manager::httpd_collector->new()->generateConfig()'
Since it's removed i don't understand why we have to patch the file

2023-06-20 20:36 UTC, jrouzierinverse commented
done

2023-06-21 14:39 UTC, fdurand commented
Rebase please

2023-06-22 17:25 UTC, merged