feature/remove-httpd-proxy
inverse-inc/packetfence pull request #7668
Opened 2023-05-16 17:45 UTC by jrouzierinverse

# Description
Remove httpd.proxy

# Impacts
If it was used migrate to use haproxy.

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* Remove httpd.proxy service

2023-06-12 18:46 UTC, fdurand requested changes

2023-06-12 18:46 UTC, fdurand commented on debian/patches/debianize.patch
> --httpd_binary=/usr/sbin/httpd
Not related

2023-06-12 18:47 UTC, fdurand commented
You have to remove the systemd script too

2023-06-13 13:15 UTC, jrouzierinverse commented
> You have to remove the systemd script too

Would this be in the rpm/debian packaging?

2023-06-14 12:37 UTC, fdurand commented on debian/patches/debianize.patch
> --ExecStartPre=/usr/bin/rm -f /usr/local/pf/var/run/httpd.proxy.pid
The service is removed so there is no need to patch it

2023-06-14 12:39 UTC, fdurand commented
interceptproxy.pm needs to be removed too

2023-06-20 21:03 UTC, jrouzierinverse commented
done

2023-06-21 14:32 UTC, merged