Feature/upgrade to ansible 7 0
inverse-inc/packetfence pull request #7690
Opened 2023-06-02 18:14 UTC by JeGoi

# Description
Upgrade to ansible core 2.14, upgrade vagrant to 2.3.6, upgrade vagrant-libvirt to 0.12.1, upgrade cumulus to 4.3.0
The main idea is to have latest fixes from ansible and vagrant.
It will only runner on new runner with the right versions.

# Impacts
Should improve issues.

# Code / PR Dependencies
Need to be related with debops projects

# Delete branch after merge
YES

# Checklist
- [ ] Have new runner to make it work
- [ ] Have the right version on runners

2023-06-05 14:19 UTC, JeGoi commented
Need to add tags for runners per branch

2023-06-06 12:13 UTC, nqb requested changes
- Notable change: RHEL8 image has been updated too.
- One thing to have in mind also: we used Ansible not only to provision VM used for integration tests and to run Venom tests but also to:
  * build containers used to build images and packages
  * build our own Vagrant images
  * build ZEN images
  
We need to be sure there are no regressions on each of this component otherwise it's a recipe for disaster for the next release.

2023-06-06 12:13 UTC, nqb commented on addons/vagrant/Vagrantfile
> +  config.winrm.timeout = 180
I don't think we need to keep it since we have removed Windows VM.

2023-06-06 12:13 UTC, nqb commented on addons/vagrant/cumulus/Vagrantfile
> +    config.ssh.connect_timeout = 120
This value is different from `addons/vagrant/Vagrantfile`, is it expected ?

2023-06-06 12:13 UTC, nqb commented on addons/vagrant/inventory/group_vars/all/common.yml
> +switch01_api_password: CumulusLinux!
These variables are specific to Cumulus devices so they must move to a dedicated inventory group.

2023-06-06 12:13 UTC, nqb commented on addons/vagrant/inventory/group_vars/clusters/venom_local_vars.yml
> +    value: "{{ ansible_default_ipv4.address }}"
Is it mandatory ?
I'm asking because we are mixing dot syntax (`ansible_default_ipv4.address`) and bracket syntax (`ansible_date_time['tz']`)

2023-06-06 13:30 UTC, JeGoi commented on addons/vagrant/Vagrantfile
> +  config.winrm.timeout = 180
I though I removed it... My bad will do

2023-06-06 13:33 UTC, JeGoi commented on addons/vagrant/inventory/group_vars/clusters/venom_local_vars.yml
> +    value: "{{ ansible_default_ipv4.address }}"
I had a error with `ansible_default_ipv4['address']` but no error with `ansible_default_ipv4.address` and `ansible_date_time['tz']`. I did not search deep why new ansible version, new way to grab that gathering facts

2023-06-06 18:18 UTC, JeGoi commented on addons/vagrant/cumulus/Vagrantfile
> +    config.ssh.connect_timeout = 120
Yes, I found that when switch01 is short in memory it is taking more time than other VM.
It is more true with cumulus 5.5.0 which needs more 2GB of RAM than the one we had with v 3.X (~0.7GB).

2023-10-12 13:49 UTC, JeGoi commented
Merged for tests: https://github.com/inverse-inc/packetfence/pull/7855
Still open for other steps: https://github.com/inverse-inc/packetfence/issues/7858

2023-10-12 13:49 UTC, closed without merging