feature/remove-symantec-provisioner
inverse-inc/packetfence pull request #7700
Opened 2023-06-06 14:52 UTC by jrouzierinverse

# Description

Remove Symantec Provisioner

# Delete branch after merge
YES

# NEWS file entries
## Enhancements
* Remove Symantec Provisioner

2023-06-12 16:19 UTC, fdurand requested changes

2023-06-12 16:19 UTC, fdurand commented on conf/pf.conf.defaults
> -proxy_passthroughs=crl.geotrust.com,ocsp.geotrust.com,crl.thawte.com,ocsp.thawte.com,crl.comodoca.com,ocsp.comodoca.com,crl.incommon.org,ocsp.incommon.org,crl.usertrust.com,ocsp.usertrust.com,mscrl.m
Not related to symantec provisionner i think

2023-06-12 16:19 UTC, fdurand commented on t/unittest/UnifiedApi/Controller/Config/Bases.t
> -  ->json_is('/meta/proxy_passthroughs/implied', 'crl.geotrust.com,ocsp.geotrust.com,crl.thawte.com,ocsp.thawte.com,crl.comodoca.com,ocsp.comodoca.com,crl.incommon.org,ocsp.incommon.org,crl.usertrust.
Not related to symantec provisionner i think

2023-06-12 16:20 UTC, fdurand commented
We should have a upgrade script that remove or comment the symantec provisionner in the config

2023-06-12 16:51 UTC, jrouzierinverse commented
> We should have a upgrade script that remove or comment the symantec provisionner in the config

It is here.
`addons/upgrade/to-13.0-remove-provisioner.pl`

2023-06-13 14:58 UTC, satkunas approved these changes
UI changes look good.

2023-06-14 12:40 UTC, fdurand approved these changes

2023-06-14 12:41 UTC, fdurand commented
rebase and it will be merged

2023-06-14 12:48 UTC, jrouzierinverse commented
> rebase and it will be merged

done

2023-06-16 08:11 UTC, nqb requested changes
There is documentation to remove under `docs`

2023-06-16 08:13 UTC, nqb commented
I'm wrong, it's already done #7692

2023-06-16 08:13 UTC, merged