Notify admins when unexpected devices pop up on network
inverse-inc/packetfence pull request #7721
Opened 2023-06-22 07:47 UTC by nqb

# Description
Be informed (through security event) when a device pops up into a VLAN or a subnet that shouldn’t be there.

In order to trigger a security event, PacketFence must receive: DHCP traffic or RADIUS **accounting**. We don't trigger on RADIUS authentication requests.

If we receive several DHCP or RADIUS requests for the same device but IP isn't updated, security event will not be triggered again due to:

```
pfqueue(3805535) DEBUG: [mac:unknown] No recent data found for 33:33:33:33:33:33, will not trigger device profiling. Was last updated at 2023-06-21T10:17:12.067524888Z and last process timestamp is 2023-06-21T10:17:12 (pf::fingerbank::process)
```

# Issue
fixes #7529

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add unit tests

# NEWS file entries
## Enhancements
* Be informed (through security event) when a device pops up into a VLAN or a subnet that shouldn’t be there

2023-06-22 07:54 UTC, nqb commented
@satkunas, I need your help to make "Device is not" field perform a search exactly like "Device" field is doing (using `api/v1/fingerbank/all/devices/search`). I was not able to figure out how to do it.

2023-06-22 12:09 UTC, nqb commented
I just need help to finalize frontend but nothing more to do on my side.

2023-06-23 08:15 UTC, nqb commented
@jrouzierinverse I had a discussion with @satkunas and in fact, the code needs to be adjusted on backend. `pfperl-api` currently returns:

```console
# pfperl-api get -M OPTIONS /api/v1/config/security_events
[..]
"device": {                                                                                                                                                                                                                       │
            "allow_custom": false,                                                                                                                                                                                                          │
            "allowed_lookup": {                                                                                                                                                                                                             │
              "field_name": "name",                                                                                                                                                                                                         │
              "search_path": "/api/v1/fingerbank/all/devices/search",                                                                                                                                                                       │
              "value_name": "id"                                                                                                                                                                                                            │
            },               
[..]
"device_is_not": {                                                                                                                                                                                                                │
            "default": null,                                                                                                                                                                                                                │
            "implied": null,                                                                                                                                                                                                                │
            "placeholder": null,                                                                                                                                                                                                            │
            "required": false,                                                                                                                                                                                                              │
            "type": "string"                                                                                                                                                                                                                │
          },
```

I would like to have similar results for `device_is_not` but I'm not able to figure out which portion of the code should I changed.
I think the logic is under `/usr/local/pf/lib/pf/UnifiedApi/Controller/Config.pm`.
Could you provide some help @jrouzierinverse ?

2023-06-29 11:35 UTC, jrouzierinverse requested changes

2023-06-29 11:35 UTC, jrouzierinverse commented on t/unittest/security_events.t
> +
Add the following tests
```perl
# Test a security_event using network and device_is_not
@security_events = $pf::security_event::SECURITY_EVENT_FILTER_ENGINE->match_all({last_ip => "172.31.0.1", device_id => 33453});
is(@security_events, 0);
```

2023-06-29 12:42 UTC, nqb commented on t/unittest/security_events.t
> +
Done

2023-06-29 12:43 UTC, nqb commented
@jrouzierinverse, I made changes you requested in `Trigger.pm` + unit tests. Frontend behaves as it should now.
If you are happy with the state of this PR, please merge.

2023-06-30 15:34 UTC, merged

2024-06-02 20:51 UTC, mellalahmed commented
Can you help me integrate security events in PacketFence?