Fix/mac not found in db 13.x
inverse-inc/packetfence pull request #7815
Opened 2023-09-13 15:31 UTC by fdurand

# Description
Update ip4log directly from pfdhcp when the network is managed by PacketFence.

# Impacts
pfqueue + pfdhcp

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries

## Enhancements
* Update ip4log from pfdhcp when the network is managed by PacketFence

2023-09-22 12:58 UTC, jrouzierinverse requested changes

2023-09-22 12:58 UTC, jrouzierinverse commented on go/cmd/pfdhcp/utils.go
> +	MAC2IP, err := MySQLdatabase.Prepare("SELECT ip FROM ip4log WHERE mac = ? AND (end_time = " + ZeroDate + " OR ( end_time + INTERVAL 30 SECOND ) > NOW()) ORDER BY start_time DESC LIMIT 1")
Quote the Zero Date
```go
	MAC2IP, err := MySQLdatabase.Prepare("SELECT ip FROM ip4log WHERE mac = ? AND (end_time = '" + ZeroDate + "' OR ( end_time + INTERVAL 30 SECOND ) > NOW()) ORDER BY start_time DESC LIMIT 1")

 ```

2023-09-22 12:58 UTC, jrouzierinverse commented on go/cmd/pfdhcp/utils.go
> +	IP2MAC, err := MySQLdatabase.Prepare("SELECT mac FROM ip4log WHERE ip = ? AND (end_time = " + ZeroDate + " OR end_time > NOW()) ORDER BY start_time DESC")
Quote the ZeroDate
```go
	IP2MAC, err := MySQLdatabase.Prepare("SELECT mac FROM ip4log WHERE ip = ? AND (end_time = '" + ZeroDate + "' OR end_time > NOW()) ORDER BY start_time DESC")
```

2023-09-22 12:58 UTC, jrouzierinverse commented on go/cmd/pfdhcp/utils.go
> +	rows, err := MySQLdatabase.Query("select ip,mac,end_time,start_time from ip4log i where inet_aton(ip) between inet_aton(?) and inet_aton(?) and (end_time = "+ZeroDate+" OR  end_time > NOW()) and end
Quote the zero date
```go
	rows, err := MySQLdatabase.Query("select ip,mac,end_time,start_time from ip4log i where inet_aton(ip) between inet_aton(?) and inet_aton(?) and (end_time = '"+ZeroDate+"' OR  end_time > NOW()) and end_time in (select MAX(end_time) from ip4log where mac = i.mac)  ORDER BY mac,end_time desc", dhcpHandler.start.String(), ipend.String())
```

2023-09-22 12:58 UTC, jrouzierinverse commented on go/cmd/pfdhcp/utils.go
> +	IPInsert, err := MySQLdatabase.Prepare("INSERT INTO ip4log (mac, ip, start_time, end_time) VALUES (?, ?, NOW(), DATE_ADD(NOW(), INTERVAL ? SECOND)) ON DUPLICATE KEY UPDATE mac=VALUES(mac), end_time=
Also, update the start_time

2023-09-22 12:58 UTC, jrouzierinverse commented on go/cmd/pfdhcp/utils.go
> +		_, err = IPUpdate.Exec(mac, duration.Seconds(), ip)
Since IPInsert handle both insert and update remove IPUpdate

2023-10-25 13:02 UTC, fdurand commented
BUMP

2023-11-17 20:14 UTC, merged