feature/pfqueue-golang
inverse-inc/packetfence pull request #7893
Opened 2023-11-07 12:38 UTC by jrouzierinverse

# Description
Move pfqueue to go

# Issue
Fixes #ISSUE_NUMBER

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add OpenAPI specification
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* Move pfqueue to go

2023-11-07 20:30 UTC, extrafu commented on go/pfconfigdriver/structs.go
> +type Pfqueue struct {
Pfqueue -> PfQueue for consistency?

2023-11-28 20:38 UTC, fdurand requested changes
It miss the packaging code and also the modification in pf::cmd::pf::service

2023-11-28 20:38 UTC, fdurand commented on conf/systemd/packetfence-pfqueue-bankend.service
> +Description=PacketFence pfqueue Service
PacketFence pfqueue backend

2023-11-28 20:38 UTC, fdurand commented on conf/systemd/packetfence-pfqueue-bankend.service
> +# Copyright (C) Inverse inc.
not sure about the file name bankend ?!

2023-11-28 20:38 UTC, fdurand commented on conf/systemd/packetfence-pfqueue-go.service
> +Description=PacketFence pfqueue Service
pfqueue go

2023-12-05 14:23 UTC, merged