Features/inv 73 reusable
inverse-inc/packetfence pull request #7902
Opened 2023-11-13 16:40 UTC by stegar123

# Description
(REQUIRED)
Describe what the new code is used for.
CI/CD packaging rpm and deb for package packetfence-perl

2023-11-13 16:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/inverse-inc/packetfence?pullRequest=7902) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/inverse-inc/packetfence?pullRequest=7902) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/inverse-inc/packetfence?pullRequest=7902) it.</sub>

2023-11-13 18:52 UTC, fdurand commented on .github/workflows/reusable_unit_test.yml
> +          INSATALL_RPM_PACKAGE: "set -x && yum -y install findutils && find /mnt -name ${{ inputs._PACKAGE_NAME }}*.rpm -exec rpm -ivh {} \\;"
INSTALL_RPM_PACKAGE

2023-11-13 18:52 UTC, fdurand commented on .github/workflows/reusable_unit_test.yml
> +          INSALL_DEB_PACKAGE: "set -x && find /mnt -name ${{ inputs._PACKAGE_NAME }}*.deb -exec dpkg -i {} \\;"
INSTALL_DEB_PACKAGE

2023-11-13 18:52 UTC, fdurand commented on .github/workflows/reusable_unit_test.yml
> +          ${{ inputs._IMAGE_TYPE == 'rhel8' && env.INSATALL_RPM_PACKAGE  || env.INSALL_DEB_PACKAGE }}
Wrong wording

2023-11-13 18:52 UTC, fdurand commented on containers/packetfence-perl/debian/Dockerfile_debian
> +#RUN TestPerlConfig=$(perl -e exit); [[ ${TestPerlConfig} != "" ]] && export LC_CTYPE=en_US.UTF-8;  export LC_ALL=en_US.UTF-8
If not used then remove the line or add a comment before it to explain why it's here.

2023-11-13 18:52 UTC, fdurand commented on containers/packetfence-perl/rhel8/Dockerfile_rhel8
> +#RUN TestPerlConfig=$(perl -e exit); [[ ${TestPerlConfig} != "" ]] && export LC_CTYPE=en_US.UTF-8;  export LC_ALL=en_US.UTF-8
If not used then remove the line or add a comment before it to explain why it's here.

2023-11-13 18:52 UTC, fdurand commented on .github/workflows/main_packetfence-perl.yml
> +      - 'devel'   # excludes devel
Why ignoring devel ?

2023-11-13 18:52 UTC, fdurand commented on .github/workflows/packetfence-perl_build_image_package.yml
> +          command_rpm: set -e && docker run --rm -i -v ${{ github.workspace }}/addons/packetfence-perl:${{ inputs._WORKDIR }}/ rockylinux:8.8 /bin/bash -c \
Do we have to be consistent , like use real rhel8 ?

2023-11-13 18:52 UTC, fdurand commented on .github/workflows/reusable_upload_packages.yml
> +        image: rockylinux:8.8
Do we have to be consistent , like use real rhel8 ?

2023-11-13 18:52 UTC, fdurand commented on containers/packetfence-perl/debian/Dockerfile_debian
> +    apt install libmodule-signature-perl zip make build-essential \
can we do a apt upgrade here ?

2023-11-13 18:52 UTC, fdurand commented on containers/packetfence-perl/rhel8/Dockerfile_rhel8
> +
Same as Debian, can we upgrade the os ?

2023-11-13 19:10 UTC, satkunas requested changes

2023-11-13 19:10 UTC, satkunas commented on .github/workflows/main_packetfence-perl.yml
> +  buil_images_and_packages:
build_images_and_packages

2023-11-17 18:34 UTC, JeGoi requested changes
I think docker tag version should be fix. Not use the latest by default.
Some names and variables to update.
Except that it looks pretty good!

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/main_packetfence-perl.yml
> +    if: ${{ contains( github.event.head_commit.message, '[perl]') || needs.build_prepation.outputs.path_changes == 'true' && ( needs.build_prepation.outputs.branch_name == 'devel' || needs.build_prep
```suggestion
    if: ${{ contains( github.event.head_commit.message, '[perl]') || needs.build_preparation.outputs.path_changes == 'true' && ( needs.build_preparation.outputs.branch_name == 'devel' || needs.build_preparation.outputs.branch_name == 'maintenance/13.0' ) }}
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/main_packetfence-perl.yml
> +  build_prepation:
```suggestion
  build_preparation:
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/main_packetfence-perl.yml
> +    needs: ['build_prepation']
```suggestion
    needs: ['build_preparation']
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/main_packetfence-perl.yml
> +      _BRANCH_NAME: ${{ needs.build_prepation.outputs.branch_name }}
```suggestion
      _WORKDIR:  ${{needs.build_preparation.outputs.workdir}}
      _OUTPUT_DIRECTORY: ${{needs.build_preparation.outputs.output_directory}}
      _BRANCH_NAME: ${{ needs.build_preparation.outputs.branch_name }}
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/main_packetfence-perl.yml
> +    needs: ['build_prepation', 'build_images_and_packages']
```suggestion
    needs: ['build_preparation', 'build_images_and_packages']
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/main_packetfence-perl.yml
> +      _PACKAGE_NAME: ${{ needs.build_prepation.outputs.package_name }}
```suggestion
      _PACKAGE_NAME: ${{ needs.build_preparation.outputs.package_name }}
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/main_packetfence-perl.yml
> +    needs: ['build_prepation', 'build_images_and_packages', 'unit_tests_packages']
```suggestion
    needs: ['build_preparation', 'build_images_and_packages', 'unit_tests_packages']
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/main_packetfence-perl.yml
> +      _PACKAGE_NAME: ${{ needs.build_prepation.outputs.package_name }}
```suggestion
      _VOLUME_MOUNT: ${{needs.build_preparation.outputs.volume_mount}}
      _BRANCH_NAME: ${{ needs.build_preparation.outputs.branch_name }}
      _PACKAGE_NAME: ${{ needs.build_preparation.outputs.package_name }}
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/main_packetfence-perl.yml
> +    needs: ['build_prepation', 'build_images_and_packages', 'unit_tests_packages', 'sign_package']
```suggestion
    needs: ['build_preparation', 'build_images_and_packages', 'unit_tests_packages', 'sign_package']
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/main_packetfence-perl.yml
> +      _PACKAGE_NAME: ${{ needs.build_prepation.outputs.package_name }}
```suggestion
      _VOLUME_MOUNT: ${{needs.build_preparation.outputs.volume_mount}}
      _BRANCH_NAME: ${{ needs.build_preparation.outputs.branch_name }}
      _PACKAGE_NAME: ${{ needs.build_preparation.outputs.package_name }}
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/reusable_sign_packages.yml
> +name: Signe debian package
```suggestion
name: Sign Debian and REL packages
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/reusable_sign_packages.yml
> +      - name: Dwnload artifactory ${{ inputs._IMAGE_TYPE }}
```suggestion
      - name: Download artifactory ${{ inputs._IMAGE_TYPE }}
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/reusable_sign_packages.yml
> +      - name: Verifiy the signarure of package ${{ inputs._IMAGE_TYPE }}
```suggestion
      - name: Verify ${{ inputs._IMAGE_TYPE }} Package Signature
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/reusable_sign_packages.yml
> +      - name: import private key ${{ inputs._IMAGE_TYPE }}
```suggestion
      - name: Import private key ${{ inputs._IMAGE_TYPE }}
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/reusable_sign_packages.yml
> +      - name: Install debian dependenecies ${{ inputs._IMAGE_TYPE }}
```suggestion
      - name: Install Debian dependencies ${{ inputs._IMAGE_TYPE }}
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/reusable_sign_packages.yml
> +      - name: Install dependenecies ${{ inputs._IMAGE_TYPE }}
```suggestion
      - name: Install dependencies ${{ inputs._IMAGE_TYPE }}
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/reusable_sign_packages.yml
> +      - name: import private key ${{ inputs._IMAGE_TYPE }}
```suggestion
      - name: Import private key ${{ inputs._IMAGE_TYPE }}
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/reusable_sign_packages.yml
> +      - name: Verifiy the signarure of package ${{ inputs._IMAGE_TYPE }}
```suggestion
      - name: Verify ${{ inputs._IMAGE_TYPE }} Package Signature
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/reusable_unit_test.yml
> +      - name: download artifactory ${{ inputs._IMAGE_TYPE }}
```suggestion
      - name: Download artifactory ${{ inputs._IMAGE_TYPE }}
```

2023-11-17 18:34 UTC, JeGoi commented on .github/workflows/packetfence-perl_build_image_package.yml
> +      - name: "Build package ${{inputs._IMAGE_TYPE}}"
```suggestion
      - name: Build package ${{inputs._IMAGE_TYPE}}
```

2023-11-17 18:34 UTC, JeGoi commented on addons/packetfence-perl/psono.py
> +    print(value)
Not sure I will print that.
Or only with a debug enabled or a flag.

2023-11-17 18:34 UTC, JeGoi commented on containers/packetfence-perl/rhel8/Dockerfile_rhel8
> +FROM redhat/ubi8
I think we should use a specific tag, not get the latest by default.

2023-11-17 18:34 UTC, JeGoi commented on containers/packetfence-perl/debian/Dockerfile_debian
> +FROM debian:11
I think we should use a specific tag and NOT get the latest by default.

2023-11-21 14:26 UTC, merged

2023-11-21 14:38 UTC, JeGoi commented on addons/packetfence-perl/psono.py
> +    print(value)
Ok I got it! I am fine with it