Feature/Meraki switch module per version
inverse-inc/packetfence pull request #8018
Opened 2024-02-20 10:56 UTC by abprasa

# Description
The existing code has a generic Meraki module, this new code updates the existing Meraki Module, adds more modules based on the currently available releases, and maps them to the relevant versions and the features they support.

# Impacts
Making it more suitable for users to choose modules based on the version of the switch. These new modules will only have the supported features enabled

# NEW Package(s) required
No additional packages are needed. 

# Feature
The idea of updating the existing list of Meraki Modules defined based on the model number to respective versions is to make it more convenient for users to choose modules based on the version of the switch.

# Delete branch after the merge
YES 

# Checklist
- [ ] Document the feature In the Network Device Config Guide
- [ ] Migration Script
- [ ] Test the new modules on UI

# NEWS file entries
## New Features
* Updating existing switch model for the next release

2024-03-14 18:32 UTC, fdurand commented
It miss the reference of the Meraki::MS in web/constanp.pm

```
 Readonly::Scalar our $EXT_URL_MERAKI_MS             => '^/Meraki::MS';
```

2024-03-19 14:33 UTC, abprasa commented
> It miss the reference of the Meraki::MS in web/constant.pm
> 
> ```
>  Readonly::Scalar our $EXT_URL_MERAKI_MS             => '^/Meraki::MS';
> ```

Updated the web/constant.pm for Mearki MS module.

2024-03-27 13:22 UTC, fdurand requested changes

2024-03-27 13:22 UTC, fdurand commented on addons/upgrade/to-13.2-convert-merakiswitch-types.pl
> +Copyright (C) 2005-2023 Inverse inc.
2024

2024-03-27 13:22 UTC, fdurand commented on addons/upgrade/to-13.2-convert-merakiswitch-types.pl
> +use File::Copy;
remove

2024-03-27 13:22 UTC, fdurand commented on docs/network/networkdevice/meraki.asciidoc
> +This is a standared switch module designed to support all the legacy Meraki Switch series using MS version earlier than v15.x.
standared -> standard

2024-03-27 13:22 UTC, fdurand commented on docs/network/networkdevice/meraki.asciidoc
> +MS v15  module is designed for the switch series operating on MS OS v15. Furthermore, it inherits all functionalities from the old "MS220_8" module, making all the configurations below applicable to
extra space to remove

2024-03-27 13:22 UTC, fdurand commented on lib/pf/Switch/Meraki/MS.pm
> +use Try::Tiny;
remove

2024-03-27 13:22 UTC, fdurand commented on lib/pf/Switch/Meraki/MS.pm
> +    my $session_id = $self->getCiscoAvPairAttribute($radius_request, "audit-session-id");
place = like the other one

2024-04-03 16:32 UTC, merged