Feature/Remove-Merge outdated switch module
inverse-inc/packetfence pull request #8027
Opened 2024-02-22 16:21 UTC by abprasa

# Description
The existing code has a list of switch modules defined based on the switch series, this new code removes/merges such existing outdated switch modules.

# Impacts
Making it switch type list clean in the UI and suitable for users to choose modules based on the version of the switch instead of the series. 

# NEW Package(s) required
No additional packages are needed. 

# Feature
This new code removes/merges the existing outdated switch modules defined based on the switch series, making it switch type list in UI clean and for a better user experience.

# Delete branch after the merge
YES 

# Checklist
- [ ] Document the feature In the Network Device Config Guide
- [ ] Migration Script
- [ ] Test the new modules on UI

# NEWS file entries
## New Features
* Removing/Merging existing switch model defined based on switch series for the next release

2024-03-05 21:50 UTC, fdurand commented
There is still references of the cisco switches you remove in constants/switch_acls.pm

2024-03-12 09:45 UTC, abprasa commented
> There is still references of the cisco switches you remove in constants/switch_acls.pm
Removed the references

2024-03-14 17:44 UTC, fdurand commented
It miss the upgrade script in order to rename the switch module in the switches.conf (the one defined in use base)

2024-03-24 17:18 UTC, abprasa commented
> It miss the upgrade script in order to rename the switch module in the switches.conf (the one defined in use base)

Created and updated the script

2024-03-27 13:17 UTC, fdurand requested changes

2024-03-27 13:17 UTC, fdurand commented on addons/upgrade/to-13.2-convert-switch-types.pl
> +use pf::util qw(valid_ip valid_mac run_as_pf);
valid_ip and valid_mac are useless

2024-03-27 13:17 UTC, fdurand commented on addons/upgrade/to-13.2-convert-switch-types.pl
> +use File::Copy;
useless

2024-03-27 13:17 UTC, fdurand commented on addons/upgrade/to-13.2-convert-switch-types.pl
> +Copyright (C) 2005-2023 Inverse inc.
2024

2024-04-03 16:48 UTC, merged