Fix/dedicated machine account for cluster
inverse-inc/packetfence pull request #8205
Opened 2024-07-03 17:47 UTC by stgmsa

# Cluster support for domain.conf 
* allow PacketFence nodes in a cluster have their own dedicated settings in domain.conf
* adds HA support when establishing secure connections.

# Impacts
* changed the domain.conf structure - For now the section name will always be `hostname domain_id`
* changed the steps when init secure connection - perform a dns query and obtain all available domain controllers, choose one to connect.

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [ ] Add OpenAPI specification
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

## Enhancements
* allow different settings in domain.conf for each nodes in a cluster. e.g., each node has its own machine account name and password.
* supports domain controller high availibity now with a SRV query of DNS

2024-07-09 15:59 UTC, fdurand requested changes

2024-07-09 15:59 UTC, fdurand commented on addons/upgrade/to-14.0-update-domain-config-section.pl
> +Copyright (C) 2005-2023 Inverse inc.
2024

2024-07-09 15:59 UTC, fdurand commented on lib/pf/UnifiedApi/Controller/Config/Domains.pm
> +    return $self->render_error(500, "Unknown error getting item");;
double ;;

2024-07-09 15:59 UTC, fdurand commented on bin/pyntlm_auth/utils.py
> +    query_name = f'_ldap._tcp.{domain}'
We should use _ldap._tcp.dc._msdcs. instead

2024-07-09 15:59 UTC, fdurand commented on lib/pf/UnifiedApi/Controller/Config/Domains.pm
> +        return 1;
Use constant $TRUE

2024-07-09 15:59 UTC, fdurand commented on lib/pf/UnifiedApi/Controller/Config/Domains.pm
> +    return 0;
Use constant $FALSE

2024-07-16 12:44 UTC, merged

2024-07-23 16:17 UTC, leonardosecci commented
Hello,

I have seen the changes made, but in my opinion, they could create problems in the event that a domain controller becomes unavailable.
In fact, if such a scenario occurs, it would be queried cyclically, generating an error.
This scenario is not uncommon in a production environment, as domain controllers are often taken down for maintenance, but this is not evident just by reading the SRV record from DNS.
For example, Samba, using the net.finddc method, first retrieves the list of domain controllers reading SRV record but returns the information of the first one that passes the operational check.

Another issue that concerns me is the performance in a production environment.
I presume that because Samba is not declared compatible with multi-threading, you have implemented a lock that, in addition to atomicizing access to global variables, effectively serializes all requests.
Given my limited knowledge of Samba, it seems that there could be compatibility with a multi-process architecture. Wouldn't it be simpler to integrate a pre-fork system, similar to Gunicorn?

Best regards

2024-07-23 19:20 UTC, satkunas commented
@leonardosecci thank you for your feedback

We currently handle fail-over, and LB - which isn't useful due to SMB single-thread. 

We have multi-threading on our road-map that will monitor alive/dead of all hosts from SRV DNS and manage a pool used for multi-threaded LB.

2024-07-24 12:51 UTC, leonardosecci commented
Thank you @satkunas, do you have an idea when the update that will monitor the health of domain controllers and for multi-threading will be released?

Best regards

2024-07-24 16:01 UTC, satkunas commented
No ETA, but we are likely to continue to prioritizing work on Domains in the future