Parse RADIUS request attributes during Redis cache extraction
inverse-inc/packetfence pull request #8380
Opened 2024-11-05 23:04 UTC by E-ThanG

# Description
Parse RADIUS attributes  WLAN-AKM-Suite, WLAN-Group-Cipher, WLAN-Pairwise-Cipher, TLS-Cert-Expiration, TLS-Cert-Valid-Since, TLS-Client-Cert-Expiration, and TLS-Client-Cert-Valid-Since into human readable strings.

Addresses issue where WLAN AKM and Cipher suite information integer value is displayed as a float64.

Note: Parsing could be done elsewhere, however, the pfcron flush task is one of the last locations where the RADIUS information is still in JSON and not a formatted string. It's relatively easy to manipulate now. Having said that, from a resource utilization perspective it may make more sense to perform this task as a particular RADIUS log entry is requested from the Admin UI.

Also, there may be additional attributes that would be nice to have parsed. I can add more if desired. The EAP-Message is perhaps a reasonable addition.

# Impacts
Usability of information presented in Admin UI RADIUS audit log

# Issue
fixes #8358 

# Delete branch after merge
YES

# Checklist
- [n/a] Document the feature
- [n/a] Add OpenAPI specification
- [If required] Add unit tests
- [n/a] Add acceptance tests (TestLink)

## Enhancements
Added parsing of WLAN-AKM-Suite, WLAN-Group-Cipher, WLAN-Pairwise-Cipher, TLS-Cert-Expiration, TLS-Cert-Valid-Since, TLS-Client-Cert-Expiration, and TLS-Client-Cert-Valid-Since attributes.

WLAN AKM and Cipher Suite attributes are decoded and filled with the name of the AKM or suite used. Dates are presented in a human-readable format with 4-digit year.

Existing behavior with WLAN attributes is that the integers are erroneously unmarshaled as Float64 by Golang json.Unmarshal. Date's are presented as a string with 2-digit year and no field delimiters or spacing ("241025235210Z").

Example from Admin UI:
```
TLS-Cert-Expiration = "2039-04-10 17:00:00",
TLS-Cert-Valid-Since = "2019-04-10 16:51:00",
TLS-Client-Cert-Expiration = "2029-09-27 21:14:28",
TLS-Client-Cert-Valid-Since = "2024-09-27 21:04:00",
WLAN-AKM-Suite = "FT over 802.1X",
WLAN-Group-Cipher = "CCMP-128",
WLAN-Pairwise-Cipher = "CCMP-128"
```
![image](https://github.com/user-attachments/assets/50cdfa74-45e0-40cd-a3f7-07fd42287a5a)

2024-11-27 13:32 UTC, fdurand requested changes
Except the 2 typos the code works.

2024-11-27 13:32 UTC, fdurand commented on go/cron/flush_radius_audit_log_job.go
> +	akmSuiteSelector: = akmSuiteInt & 0x0000000F
typo here should be := and not : =

2024-11-27 13:32 UTC, fdurand commented on go/cron/flush_radius_audit_log_job.go
> +	cipherSuiteSelector: = cipherSuiteInt & 0x0000000F
typo here should be := and not : =

2024-11-27 22:52 UTC, E-ThanG commented on go/cron/flush_radius_audit_log_job.go
> +	akmSuiteSelector: = akmSuiteInt & 0x0000000F
Fixed and pushed changes

2024-11-27 22:52 UTC, E-ThanG commented on go/cron/flush_radius_audit_log_job.go
> +	cipherSuiteSelector: = cipherSuiteInt & 0x0000000F
Fixed and pushed changes

2024-11-27 22:53 UTC, E-ThanG commented
Can you think of other attributes that it would be handy to include parsing of?

2024-12-03 18:46 UTC, fdurand commented
> Can you think of other attributes that it would be handy to include parsing of?

Not really. At least we can keep like that and we will see if we need to add more.

2024-12-03 18:47 UTC, merged