Update documents for node-specific domain configuration file
inverse-inc/packetfence pull request #8437
Opened 2024-12-12 22:59 UTC by stgmsa

# Description
Update documentation for node-specific domain.conf.
document new domain.conf structure and how to manually join / sync domain.conf in a cluster.

# Impacts
update documents on joining a Active Directory Domain.
update migration script to rebuild domain.conf (WIP)

# Issue
fixes #8401 

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [N/A] Add OpenAPI specification
- [N/A] Add unit tests
- [N/A] Add acceptance tests (TestLink)

## Enhancements
* explained domain.conf structure changes in detail
* update migration script to make upgrade easier.

## Bug Fixes
issue #8401

2024-12-17 20:16 UTC, stgmsa commented
Needs backport.

2025-01-06 17:47 UTC, fdurand requested changes

2025-01-06 17:47 UTC, fdurand commented on docs/PacketFence_Upgrade_Guide.asciidoc
> +You will see 3 individual machine accounts on Windows Domain Controller, named `pfv14-1`, `pfv14-2` and `pfv14-3` (assuming we are using %h as machine account name).
node1, node2, node3 instead, based on the configuration file ?

2025-01-06 17:47 UTC, fdurand commented on docs/installation/authentication_mechanisms.asciidoc
> +This change allows each node in a cluster have their indivudual domain configuration. For example, a node doesn't have to use %h as part of the machine
Rephrase it.

2025-01-06 18:00 UTC, stgmsa commented on docs/PacketFence_Upgrade_Guide.asciidoc
> +You will see 3 individual machine accounts on Windows Domain Controller, named `pfv14-1`, `pfv14-2` and `pfv14-3` (assuming we are using %h as machine account name).
No, based on the assumption.
we assumes the hostnames of the 3 nodes are `pfv14-1` `pfv14-2` `pfv14-3`
use node1 node2 node3 instead ?

2025-01-08 15:11 UTC, satkunas commented on docs/PacketFence_Upgrade_Guide.asciidoc
> +You will see 3 individual machine accounts on Windows Domain Controller, named `pfv14-1`, `pfv14-2` and `pfv14-3` (assuming we are using %h as machine account name).
Use `pf-node1` `pf-node2` and `pf-node3`

2025-01-13 14:39 UTC, merged